// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/apigatewayv2"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIGatewayV2ClientPort creates a new instance of APIGatewayV2ClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIGatewayV2ClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIGatewayV2ClientPort {
	mock := &APIGatewayV2ClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIGatewayV2ClientPort is an autogenerated mock type for the APIGatewayV2ClientPort type
type APIGatewayV2ClientPort struct {
	mock.Mock
}

type APIGatewayV2ClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *APIGatewayV2ClientPort) EXPECT() *APIGatewayV2ClientPort_Expecter {
	return &APIGatewayV2ClientPort_Expecter{mock: &_m.Mock}
}

// CreateApi provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) CreateApi(ctx context.Context, input *apigatewayv2.CreateApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateApiOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateApi")
	}

	var r0 *apigatewayv2.CreateApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateApiInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateApiOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateApiInput, ...func(*apigatewayv2.Options)) *apigatewayv2.CreateApiOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateApiInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_CreateApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApi'
type APIGatewayV2ClientPort_CreateApi_Call struct {
	*mock.Call
}

// CreateApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateApiInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) CreateApi(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_CreateApi_Call {
	return &APIGatewayV2ClientPort_CreateApi_Call{Call: _e.mock.On("CreateApi",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_CreateApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateApiInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_CreateApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateApiInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateApi_Call) Return(createApiOutput *apigatewayv2.CreateApiOutput, err error) *APIGatewayV2ClientPort_CreateApi_Call {
	_c.Call.Return(createApiOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateApiOutput, error)) *APIGatewayV2ClientPort_CreateApi_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntegration provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) CreateIntegration(ctx context.Context, input *apigatewayv2.CreateIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateIntegrationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateIntegration")
	}

	var r0 *apigatewayv2.CreateIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateIntegrationInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateIntegrationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateIntegrationInput, ...func(*apigatewayv2.Options)) *apigatewayv2.CreateIntegrationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateIntegrationInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_CreateIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntegration'
type APIGatewayV2ClientPort_CreateIntegration_Call struct {
	*mock.Call
}

// CreateIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateIntegrationInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) CreateIntegration(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_CreateIntegration_Call {
	return &APIGatewayV2ClientPort_CreateIntegration_Call{Call: _e.mock.On("CreateIntegration",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_CreateIntegration_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateIntegrationInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_CreateIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateIntegrationInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateIntegration_Call) Return(createIntegrationOutput *apigatewayv2.CreateIntegrationOutput, err error) *APIGatewayV2ClientPort_CreateIntegration_Call {
	_c.Call.Return(createIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateIntegrationOutput, error)) *APIGatewayV2ClientPort_CreateIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoute provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) CreateRoute(ctx context.Context, input *apigatewayv2.CreateRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateRouteOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateRoute")
	}

	var r0 *apigatewayv2.CreateRouteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateRouteInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateRouteOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateRouteInput, ...func(*apigatewayv2.Options)) *apigatewayv2.CreateRouteOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateRouteOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateRouteInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_CreateRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoute'
type APIGatewayV2ClientPort_CreateRoute_Call struct {
	*mock.Call
}

// CreateRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateRouteInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) CreateRoute(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_CreateRoute_Call {
	return &APIGatewayV2ClientPort_CreateRoute_Call{Call: _e.mock.On("CreateRoute",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_CreateRoute_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateRouteInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_CreateRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateRouteInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateRouteInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateRoute_Call) Return(createRouteOutput *apigatewayv2.CreateRouteOutput, err error) *APIGatewayV2ClientPort_CreateRoute_Call {
	_c.Call.Return(createRouteOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateRoute_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateRouteOutput, error)) *APIGatewayV2ClientPort_CreateRoute_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStage provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) CreateStage(ctx context.Context, input *apigatewayv2.CreateStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateStageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateStage")
	}

	var r0 *apigatewayv2.CreateStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateStageInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateStageOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateStageInput, ...func(*apigatewayv2.Options)) *apigatewayv2.CreateStageOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateStageInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_CreateStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStage'
type APIGatewayV2ClientPort_CreateStage_Call struct {
	*mock.Call
}

// CreateStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateStageInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) CreateStage(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_CreateStage_Call {
	return &APIGatewayV2ClientPort_CreateStage_Call{Call: _e.mock.On("CreateStage",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_CreateStage_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateStageInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_CreateStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateStageInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateStage_Call) Return(createStageOutput *apigatewayv2.CreateStageOutput, err error) *APIGatewayV2ClientPort_CreateStage_Call {
	_c.Call.Return(createStageOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_CreateStage_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.CreateStageOutput, error)) *APIGatewayV2ClientPort_CreateStage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApi provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) DeleteApi(ctx context.Context, input *apigatewayv2.DeleteApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteApiOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteApi")
	}

	var r0 *apigatewayv2.DeleteApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteApiInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteApiOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteApiInput, ...func(*apigatewayv2.Options)) *apigatewayv2.DeleteApiOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteApiInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_DeleteApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApi'
type APIGatewayV2ClientPort_DeleteApi_Call struct {
	*mock.Call
}

// DeleteApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteApiInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) DeleteApi(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_DeleteApi_Call {
	return &APIGatewayV2ClientPort_DeleteApi_Call{Call: _e.mock.On("DeleteApi",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_DeleteApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteApiInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_DeleteApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteApiInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteApi_Call) Return(deleteApiOutput *apigatewayv2.DeleteApiOutput, err error) *APIGatewayV2ClientPort_DeleteApi_Call {
	_c.Call.Return(deleteApiOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteApiOutput, error)) *APIGatewayV2ClientPort_DeleteApi_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIntegration provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) DeleteIntegration(ctx context.Context, input *apigatewayv2.DeleteIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteIntegrationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteIntegration")
	}

	var r0 *apigatewayv2.DeleteIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteIntegrationInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteIntegrationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteIntegrationInput, ...func(*apigatewayv2.Options)) *apigatewayv2.DeleteIntegrationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteIntegrationInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_DeleteIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIntegration'
type APIGatewayV2ClientPort_DeleteIntegration_Call struct {
	*mock.Call
}

// DeleteIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteIntegrationInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) DeleteIntegration(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_DeleteIntegration_Call {
	return &APIGatewayV2ClientPort_DeleteIntegration_Call{Call: _e.mock.On("DeleteIntegration",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_DeleteIntegration_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteIntegrationInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_DeleteIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteIntegrationInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteIntegration_Call) Return(deleteIntegrationOutput *apigatewayv2.DeleteIntegrationOutput, err error) *APIGatewayV2ClientPort_DeleteIntegration_Call {
	_c.Call.Return(deleteIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteIntegrationOutput, error)) *APIGatewayV2ClientPort_DeleteIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoute provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) DeleteRoute(ctx context.Context, input *apigatewayv2.DeleteRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteRouteOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoute")
	}

	var r0 *apigatewayv2.DeleteRouteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteRouteInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteRouteOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteRouteInput, ...func(*apigatewayv2.Options)) *apigatewayv2.DeleteRouteOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteRouteOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteRouteInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_DeleteRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoute'
type APIGatewayV2ClientPort_DeleteRoute_Call struct {
	*mock.Call
}

// DeleteRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteRouteInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) DeleteRoute(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_DeleteRoute_Call {
	return &APIGatewayV2ClientPort_DeleteRoute_Call{Call: _e.mock.On("DeleteRoute",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_DeleteRoute_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteRouteInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_DeleteRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteRouteInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteRouteInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteRoute_Call) Return(deleteRouteOutput *apigatewayv2.DeleteRouteOutput, err error) *APIGatewayV2ClientPort_DeleteRoute_Call {
	_c.Call.Return(deleteRouteOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteRoute_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteRouteOutput, error)) *APIGatewayV2ClientPort_DeleteRoute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStage provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) DeleteStage(ctx context.Context, input *apigatewayv2.DeleteStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteStageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteStage")
	}

	var r0 *apigatewayv2.DeleteStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteStageInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteStageOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteStageInput, ...func(*apigatewayv2.Options)) *apigatewayv2.DeleteStageOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteStageInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_DeleteStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStage'
type APIGatewayV2ClientPort_DeleteStage_Call struct {
	*mock.Call
}

// DeleteStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteStageInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) DeleteStage(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_DeleteStage_Call {
	return &APIGatewayV2ClientPort_DeleteStage_Call{Call: _e.mock.On("DeleteStage",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_DeleteStage_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteStageInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_DeleteStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteStageInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteStage_Call) Return(deleteStageOutput *apigatewayv2.DeleteStageOutput, err error) *APIGatewayV2ClientPort_DeleteStage_Call {
	_c.Call.Return(deleteStageOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_DeleteStage_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.DeleteStageOutput, error)) *APIGatewayV2ClientPort_DeleteStage_Call {
	_c.Call.Return(run)
	return _c
}

// GetApi provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetApi(ctx context.Context, input *apigatewayv2.GetApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApiOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetApi")
	}

	var r0 *apigatewayv2.GetApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApiInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApiOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApiInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetApiOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetApiInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApi'
type APIGatewayV2ClientPort_GetApi_Call struct {
	*mock.Call
}

// GetApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetApiInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetApi(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetApi_Call {
	return &APIGatewayV2ClientPort_GetApi_Call{Call: _e.mock.On("GetApi",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetApiInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetApiInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetApi_Call) Return(getApiOutput *apigatewayv2.GetApiOutput, err error) *APIGatewayV2ClientPort_GetApi_Call {
	_c.Call.Return(getApiOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetApiInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApiOutput, error)) *APIGatewayV2ClientPort_GetApi_Call {
	_c.Call.Return(run)
	return _c
}

// GetApis provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetApis(ctx context.Context, input *apigatewayv2.GetApisInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApisOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetApis")
	}

	var r0 *apigatewayv2.GetApisOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApisInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApisOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApisInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetApisOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetApisOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetApisInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetApis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApis'
type APIGatewayV2ClientPort_GetApis_Call struct {
	*mock.Call
}

// GetApis is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetApisInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetApis(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetApis_Call {
	return &APIGatewayV2ClientPort_GetApis_Call{Call: _e.mock.On("GetApis",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetApis_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetApisInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetApis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetApisInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetApisInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetApis_Call) Return(getApisOutput *apigatewayv2.GetApisOutput, err error) *APIGatewayV2ClientPort_GetApis_Call {
	_c.Call.Return(getApisOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetApis_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetApisInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetApisOutput, error)) *APIGatewayV2ClientPort_GetApis_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntegrations provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetIntegrations(ctx context.Context, input *apigatewayv2.GetIntegrationsInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetIntegrationsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetIntegrations")
	}

	var r0 *apigatewayv2.GetIntegrationsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetIntegrationsInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetIntegrationsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetIntegrationsInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetIntegrationsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetIntegrationsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetIntegrationsInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetIntegrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntegrations'
type APIGatewayV2ClientPort_GetIntegrations_Call struct {
	*mock.Call
}

// GetIntegrations is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetIntegrationsInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetIntegrations(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetIntegrations_Call {
	return &APIGatewayV2ClientPort_GetIntegrations_Call{Call: _e.mock.On("GetIntegrations",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetIntegrations_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetIntegrationsInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetIntegrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetIntegrationsInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetIntegrationsInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetIntegrations_Call) Return(getIntegrationsOutput *apigatewayv2.GetIntegrationsOutput, err error) *APIGatewayV2ClientPort_GetIntegrations_Call {
	_c.Call.Return(getIntegrationsOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetIntegrations_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetIntegrationsInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetIntegrationsOutput, error)) *APIGatewayV2ClientPort_GetIntegrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoutes provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetRoutes(ctx context.Context, input *apigatewayv2.GetRoutesInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetRoutesOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRoutes")
	}

	var r0 *apigatewayv2.GetRoutesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetRoutesInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetRoutesOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetRoutesInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetRoutesOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetRoutesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetRoutesInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoutes'
type APIGatewayV2ClientPort_GetRoutes_Call struct {
	*mock.Call
}

// GetRoutes is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetRoutesInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetRoutes(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetRoutes_Call {
	return &APIGatewayV2ClientPort_GetRoutes_Call{Call: _e.mock.On("GetRoutes",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetRoutes_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetRoutesInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetRoutesInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetRoutesInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetRoutes_Call) Return(getRoutesOutput *apigatewayv2.GetRoutesOutput, err error) *APIGatewayV2ClientPort_GetRoutes_Call {
	_c.Call.Return(getRoutesOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetRoutes_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetRoutesInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetRoutesOutput, error)) *APIGatewayV2ClientPort_GetRoutes_Call {
	_c.Call.Return(run)
	return _c
}

// GetStage provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetStage(ctx context.Context, input *apigatewayv2.GetStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetStage")
	}

	var r0 *apigatewayv2.GetStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetStageInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStageOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetStageInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetStageOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetStageInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStage'
type APIGatewayV2ClientPort_GetStage_Call struct {
	*mock.Call
}

// GetStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetStageInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetStage(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetStage_Call {
	return &APIGatewayV2ClientPort_GetStage_Call{Call: _e.mock.On("GetStage",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetStage_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetStageInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetStageInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetStage_Call) Return(getStageOutput *apigatewayv2.GetStageOutput, err error) *APIGatewayV2ClientPort_GetStage_Call {
	_c.Call.Return(getStageOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetStage_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStageOutput, error)) *APIGatewayV2ClientPort_GetStage_Call {
	_c.Call.Return(run)
	return _c
}

// GetStages provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) GetStages(ctx context.Context, input *apigatewayv2.GetStagesInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStagesOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetStages")
	}

	var r0 *apigatewayv2.GetStagesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetStagesInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStagesOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetStagesInput, ...func(*apigatewayv2.Options)) *apigatewayv2.GetStagesOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetStagesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetStagesInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_GetStages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStages'
type APIGatewayV2ClientPort_GetStages_Call struct {
	*mock.Call
}

// GetStages is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetStagesInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) GetStages(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_GetStages_Call {
	return &APIGatewayV2ClientPort_GetStages_Call{Call: _e.mock.On("GetStages",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_GetStages_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetStagesInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_GetStages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetStagesInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetStagesInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_GetStages_Call) Return(getStagesOutput *apigatewayv2.GetStagesOutput, err error) *APIGatewayV2ClientPort_GetStages_Call {
	_c.Call.Return(getStagesOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_GetStages_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetStagesInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.GetStagesOutput, error)) *APIGatewayV2ClientPort_GetStages_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateIntegration provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) UpdateIntegration(ctx context.Context, input *apigatewayv2.UpdateIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateIntegrationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateIntegration")
	}

	var r0 *apigatewayv2.UpdateIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateIntegrationInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateIntegrationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateIntegrationInput, ...func(*apigatewayv2.Options)) *apigatewayv2.UpdateIntegrationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.UpdateIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.UpdateIntegrationInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_UpdateIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateIntegration'
type APIGatewayV2ClientPort_UpdateIntegration_Call struct {
	*mock.Call
}

// UpdateIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.UpdateIntegrationInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) UpdateIntegration(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_UpdateIntegration_Call {
	return &APIGatewayV2ClientPort_UpdateIntegration_Call{Call: _e.mock.On("UpdateIntegration",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_UpdateIntegration_Call) Run(run func(ctx context.Context, input *apigatewayv2.UpdateIntegrationInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_UpdateIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.UpdateIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.UpdateIntegrationInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateIntegration_Call) Return(updateIntegrationOutput *apigatewayv2.UpdateIntegrationOutput, err error) *APIGatewayV2ClientPort_UpdateIntegration_Call {
	_c.Call.Return(updateIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.UpdateIntegrationInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateIntegrationOutput, error)) *APIGatewayV2ClientPort_UpdateIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRoute provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) UpdateRoute(ctx context.Context, input *apigatewayv2.UpdateRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateRouteOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateRoute")
	}

	var r0 *apigatewayv2.UpdateRouteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateRouteInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateRouteOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateRouteInput, ...func(*apigatewayv2.Options)) *apigatewayv2.UpdateRouteOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.UpdateRouteOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.UpdateRouteInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_UpdateRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRoute'
type APIGatewayV2ClientPort_UpdateRoute_Call struct {
	*mock.Call
}

// UpdateRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.UpdateRouteInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) UpdateRoute(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_UpdateRoute_Call {
	return &APIGatewayV2ClientPort_UpdateRoute_Call{Call: _e.mock.On("UpdateRoute",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_UpdateRoute_Call) Run(run func(ctx context.Context, input *apigatewayv2.UpdateRouteInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_UpdateRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.UpdateRouteInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.UpdateRouteInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateRoute_Call) Return(updateRouteOutput *apigatewayv2.UpdateRouteOutput, err error) *APIGatewayV2ClientPort_UpdateRoute_Call {
	_c.Call.Return(updateRouteOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateRoute_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.UpdateRouteInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateRouteOutput, error)) *APIGatewayV2ClientPort_UpdateRoute_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStage provides a mock function for the type APIGatewayV2ClientPort
func (_mock *APIGatewayV2ClientPort) UpdateStage(ctx context.Context, input *apigatewayv2.UpdateStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateStageOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateStage")
	}

	var r0 *apigatewayv2.UpdateStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateStageInput, ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateStageOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.UpdateStageInput, ...func(*apigatewayv2.Options)) *apigatewayv2.UpdateStageOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.UpdateStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.UpdateStageInput, ...func(*apigatewayv2.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2ClientPort_UpdateStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStage'
type APIGatewayV2ClientPort_UpdateStage_Call struct {
	*mock.Call
}

// UpdateStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.UpdateStageInput
//   - opts ...func(*apigatewayv2.Options)
func (_e *APIGatewayV2ClientPort_Expecter) UpdateStage(ctx interface{}, input interface{}, opts ...interface{}) *APIGatewayV2ClientPort_UpdateStage_Call {
	return &APIGatewayV2ClientPort_UpdateStage_Call{Call: _e.mock.On("UpdateStage",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *APIGatewayV2ClientPort_UpdateStage_Call) Run(run func(ctx context.Context, input *apigatewayv2.UpdateStageInput, opts ...func(*apigatewayv2.Options))) *APIGatewayV2ClientPort_UpdateStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.UpdateStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.UpdateStageInput)
		}
		var arg2 []func(*apigatewayv2.Options)
		var variadicArgs []func(*apigatewayv2.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*apigatewayv2.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateStage_Call) Return(updateStageOutput *apigatewayv2.UpdateStageOutput, err error) *APIGatewayV2ClientPort_UpdateStage_Call {
	_c.Call.Return(updateStageOutput, err)
	return _c
}

func (_c *APIGatewayV2ClientPort_UpdateStage_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.UpdateStageInput, opts ...func(*apigatewayv2.Options)) (*apigatewayv2.UpdateStageOutput, error)) *APIGatewayV2ClientPort_UpdateStage_Call {
	_c.Call.Return(run)
	return _c
}
