// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/apigateway"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIGatewayPort creates a new instance of APIGatewayPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIGatewayPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIGatewayPort {
	mock := &APIGatewayPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIGatewayPort is an autogenerated mock type for the APIGatewayPort type
type APIGatewayPort struct {
	mock.Mock
}

type APIGatewayPort_Expecter struct {
	mock *mock.Mock
}

func (_m *APIGatewayPort) EXPECT() *APIGatewayPort_Expecter {
	return &APIGatewayPort_Expecter{mock: &_m.Mock}
}

// CreateDeployment provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) CreateDeployment(ctx context.Context, input *apigateway.CreateDeploymentInput) (*apigateway.CreateDeploymentOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateDeployment")
	}

	var r0 *apigateway.CreateDeploymentOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateDeploymentInput) (*apigateway.CreateDeploymentOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateDeploymentInput) *apigateway.CreateDeploymentOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.CreateDeploymentOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.CreateDeploymentInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_CreateDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDeployment'
type APIGatewayPort_CreateDeployment_Call struct {
	*mock.Call
}

// CreateDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.CreateDeploymentInput
func (_e *APIGatewayPort_Expecter) CreateDeployment(ctx interface{}, input interface{}) *APIGatewayPort_CreateDeployment_Call {
	return &APIGatewayPort_CreateDeployment_Call{Call: _e.mock.On("CreateDeployment", ctx, input)}
}

func (_c *APIGatewayPort_CreateDeployment_Call) Run(run func(ctx context.Context, input *apigateway.CreateDeploymentInput)) *APIGatewayPort_CreateDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.CreateDeploymentInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.CreateDeploymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_CreateDeployment_Call) Return(createDeploymentOutput *apigateway.CreateDeploymentOutput, err error) *APIGatewayPort_CreateDeployment_Call {
	_c.Call.Return(createDeploymentOutput, err)
	return _c
}

func (_c *APIGatewayPort_CreateDeployment_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.CreateDeploymentInput) (*apigateway.CreateDeploymentOutput, error)) *APIGatewayPort_CreateDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateResource provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) CreateResource(ctx context.Context, input *apigateway.CreateResourceInput) (*apigateway.CreateResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateResource")
	}

	var r0 *apigateway.CreateResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateResourceInput) (*apigateway.CreateResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateResourceInput) *apigateway.CreateResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.CreateResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.CreateResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_CreateResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateResource'
type APIGatewayPort_CreateResource_Call struct {
	*mock.Call
}

// CreateResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.CreateResourceInput
func (_e *APIGatewayPort_Expecter) CreateResource(ctx interface{}, input interface{}) *APIGatewayPort_CreateResource_Call {
	return &APIGatewayPort_CreateResource_Call{Call: _e.mock.On("CreateResource", ctx, input)}
}

func (_c *APIGatewayPort_CreateResource_Call) Run(run func(ctx context.Context, input *apigateway.CreateResourceInput)) *APIGatewayPort_CreateResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.CreateResourceInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.CreateResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_CreateResource_Call) Return(createResourceOutput *apigateway.CreateResourceOutput, err error) *APIGatewayPort_CreateResource_Call {
	_c.Call.Return(createResourceOutput, err)
	return _c
}

func (_c *APIGatewayPort_CreateResource_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.CreateResourceInput) (*apigateway.CreateResourceOutput, error)) *APIGatewayPort_CreateResource_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRestApi provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) CreateRestApi(ctx context.Context, input *apigateway.CreateRestApiInput) (*apigateway.CreateRestApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateRestApi")
	}

	var r0 *apigateway.CreateRestApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateRestApiInput) (*apigateway.CreateRestApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateRestApiInput) *apigateway.CreateRestApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.CreateRestApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.CreateRestApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_CreateRestApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRestApi'
type APIGatewayPort_CreateRestApi_Call struct {
	*mock.Call
}

// CreateRestApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.CreateRestApiInput
func (_e *APIGatewayPort_Expecter) CreateRestApi(ctx interface{}, input interface{}) *APIGatewayPort_CreateRestApi_Call {
	return &APIGatewayPort_CreateRestApi_Call{Call: _e.mock.On("CreateRestApi", ctx, input)}
}

func (_c *APIGatewayPort_CreateRestApi_Call) Run(run func(ctx context.Context, input *apigateway.CreateRestApiInput)) *APIGatewayPort_CreateRestApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.CreateRestApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.CreateRestApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_CreateRestApi_Call) Return(createRestApiOutput *apigateway.CreateRestApiOutput, err error) *APIGatewayPort_CreateRestApi_Call {
	_c.Call.Return(createRestApiOutput, err)
	return _c
}

func (_c *APIGatewayPort_CreateRestApi_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.CreateRestApiInput) (*apigateway.CreateRestApiOutput, error)) *APIGatewayPort_CreateRestApi_Call {
	_c.Call.Return(run)
	return _c
}

// CreateStage provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) CreateStage(ctx context.Context, input *apigateway.CreateStageInput) (*apigateway.CreateStageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateStage")
	}

	var r0 *apigateway.CreateStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateStageInput) (*apigateway.CreateStageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.CreateStageInput) *apigateway.CreateStageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.CreateStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.CreateStageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_CreateStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStage'
type APIGatewayPort_CreateStage_Call struct {
	*mock.Call
}

// CreateStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.CreateStageInput
func (_e *APIGatewayPort_Expecter) CreateStage(ctx interface{}, input interface{}) *APIGatewayPort_CreateStage_Call {
	return &APIGatewayPort_CreateStage_Call{Call: _e.mock.On("CreateStage", ctx, input)}
}

func (_c *APIGatewayPort_CreateStage_Call) Run(run func(ctx context.Context, input *apigateway.CreateStageInput)) *APIGatewayPort_CreateStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.CreateStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.CreateStageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_CreateStage_Call) Return(createStageOutput *apigateway.CreateStageOutput, err error) *APIGatewayPort_CreateStage_Call {
	_c.Call.Return(createStageOutput, err)
	return _c
}

func (_c *APIGatewayPort_CreateStage_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.CreateStageInput) (*apigateway.CreateStageOutput, error)) *APIGatewayPort_CreateStage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDeployment provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteDeployment(ctx context.Context, input *apigateway.DeleteDeploymentInput) (*apigateway.DeleteDeploymentOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteDeployment")
	}

	var r0 *apigateway.DeleteDeploymentOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteDeploymentInput) (*apigateway.DeleteDeploymentOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteDeploymentInput) *apigateway.DeleteDeploymentOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteDeploymentOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteDeploymentInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteDeployment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDeployment'
type APIGatewayPort_DeleteDeployment_Call struct {
	*mock.Call
}

// DeleteDeployment is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteDeploymentInput
func (_e *APIGatewayPort_Expecter) DeleteDeployment(ctx interface{}, input interface{}) *APIGatewayPort_DeleteDeployment_Call {
	return &APIGatewayPort_DeleteDeployment_Call{Call: _e.mock.On("DeleteDeployment", ctx, input)}
}

func (_c *APIGatewayPort_DeleteDeployment_Call) Run(run func(ctx context.Context, input *apigateway.DeleteDeploymentInput)) *APIGatewayPort_DeleteDeployment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteDeploymentInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteDeploymentInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteDeployment_Call) Return(deleteDeploymentOutput *apigateway.DeleteDeploymentOutput, err error) *APIGatewayPort_DeleteDeployment_Call {
	_c.Call.Return(deleteDeploymentOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteDeployment_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteDeploymentInput) (*apigateway.DeleteDeploymentOutput, error)) *APIGatewayPort_DeleteDeployment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteIntegration provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteIntegration(ctx context.Context, input *apigateway.DeleteIntegrationInput) (*apigateway.DeleteIntegrationOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteIntegration")
	}

	var r0 *apigateway.DeleteIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteIntegrationInput) (*apigateway.DeleteIntegrationOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteIntegrationInput) *apigateway.DeleteIntegrationOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteIntegrationInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteIntegration'
type APIGatewayPort_DeleteIntegration_Call struct {
	*mock.Call
}

// DeleteIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteIntegrationInput
func (_e *APIGatewayPort_Expecter) DeleteIntegration(ctx interface{}, input interface{}) *APIGatewayPort_DeleteIntegration_Call {
	return &APIGatewayPort_DeleteIntegration_Call{Call: _e.mock.On("DeleteIntegration", ctx, input)}
}

func (_c *APIGatewayPort_DeleteIntegration_Call) Run(run func(ctx context.Context, input *apigateway.DeleteIntegrationInput)) *APIGatewayPort_DeleteIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteIntegrationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteIntegration_Call) Return(deleteIntegrationOutput *apigateway.DeleteIntegrationOutput, err error) *APIGatewayPort_DeleteIntegration_Call {
	_c.Call.Return(deleteIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteIntegrationInput) (*apigateway.DeleteIntegrationOutput, error)) *APIGatewayPort_DeleteIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMethod provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteMethod(ctx context.Context, input *apigateway.DeleteMethodInput) (*apigateway.DeleteMethodOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMethod")
	}

	var r0 *apigateway.DeleteMethodOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteMethodInput) (*apigateway.DeleteMethodOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteMethodInput) *apigateway.DeleteMethodOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteMethodOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteMethodInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMethod'
type APIGatewayPort_DeleteMethod_Call struct {
	*mock.Call
}

// DeleteMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteMethodInput
func (_e *APIGatewayPort_Expecter) DeleteMethod(ctx interface{}, input interface{}) *APIGatewayPort_DeleteMethod_Call {
	return &APIGatewayPort_DeleteMethod_Call{Call: _e.mock.On("DeleteMethod", ctx, input)}
}

func (_c *APIGatewayPort_DeleteMethod_Call) Run(run func(ctx context.Context, input *apigateway.DeleteMethodInput)) *APIGatewayPort_DeleteMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteMethodInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteMethodInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteMethod_Call) Return(deleteMethodOutput *apigateway.DeleteMethodOutput, err error) *APIGatewayPort_DeleteMethod_Call {
	_c.Call.Return(deleteMethodOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteMethod_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteMethodInput) (*apigateway.DeleteMethodOutput, error)) *APIGatewayPort_DeleteMethod_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteResource provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteResource(ctx context.Context, input *apigateway.DeleteResourceInput) (*apigateway.DeleteResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteResource")
	}

	var r0 *apigateway.DeleteResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteResourceInput) (*apigateway.DeleteResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteResourceInput) *apigateway.DeleteResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteResource'
type APIGatewayPort_DeleteResource_Call struct {
	*mock.Call
}

// DeleteResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteResourceInput
func (_e *APIGatewayPort_Expecter) DeleteResource(ctx interface{}, input interface{}) *APIGatewayPort_DeleteResource_Call {
	return &APIGatewayPort_DeleteResource_Call{Call: _e.mock.On("DeleteResource", ctx, input)}
}

func (_c *APIGatewayPort_DeleteResource_Call) Run(run func(ctx context.Context, input *apigateway.DeleteResourceInput)) *APIGatewayPort_DeleteResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteResourceInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteResource_Call) Return(deleteResourceOutput *apigateway.DeleteResourceOutput, err error) *APIGatewayPort_DeleteResource_Call {
	_c.Call.Return(deleteResourceOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteResource_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteResourceInput) (*apigateway.DeleteResourceOutput, error)) *APIGatewayPort_DeleteResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRestApi provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteRestApi(ctx context.Context, input *apigateway.DeleteRestApiInput) (*apigateway.DeleteRestApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRestApi")
	}

	var r0 *apigateway.DeleteRestApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteRestApiInput) (*apigateway.DeleteRestApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteRestApiInput) *apigateway.DeleteRestApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteRestApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteRestApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteRestApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRestApi'
type APIGatewayPort_DeleteRestApi_Call struct {
	*mock.Call
}

// DeleteRestApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteRestApiInput
func (_e *APIGatewayPort_Expecter) DeleteRestApi(ctx interface{}, input interface{}) *APIGatewayPort_DeleteRestApi_Call {
	return &APIGatewayPort_DeleteRestApi_Call{Call: _e.mock.On("DeleteRestApi", ctx, input)}
}

func (_c *APIGatewayPort_DeleteRestApi_Call) Run(run func(ctx context.Context, input *apigateway.DeleteRestApiInput)) *APIGatewayPort_DeleteRestApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteRestApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteRestApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteRestApi_Call) Return(deleteRestApiOutput *apigateway.DeleteRestApiOutput, err error) *APIGatewayPort_DeleteRestApi_Call {
	_c.Call.Return(deleteRestApiOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteRestApi_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteRestApiInput) (*apigateway.DeleteRestApiOutput, error)) *APIGatewayPort_DeleteRestApi_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStage provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) DeleteStage(ctx context.Context, input *apigateway.DeleteStageInput) (*apigateway.DeleteStageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStage")
	}

	var r0 *apigateway.DeleteStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteStageInput) (*apigateway.DeleteStageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.DeleteStageInput) *apigateway.DeleteStageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.DeleteStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.DeleteStageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_DeleteStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStage'
type APIGatewayPort_DeleteStage_Call struct {
	*mock.Call
}

// DeleteStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.DeleteStageInput
func (_e *APIGatewayPort_Expecter) DeleteStage(ctx interface{}, input interface{}) *APIGatewayPort_DeleteStage_Call {
	return &APIGatewayPort_DeleteStage_Call{Call: _e.mock.On("DeleteStage", ctx, input)}
}

func (_c *APIGatewayPort_DeleteStage_Call) Run(run func(ctx context.Context, input *apigateway.DeleteStageInput)) *APIGatewayPort_DeleteStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.DeleteStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.DeleteStageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_DeleteStage_Call) Return(deleteStageOutput *apigateway.DeleteStageOutput, err error) *APIGatewayPort_DeleteStage_Call {
	_c.Call.Return(deleteStageOutput, err)
	return _c
}

func (_c *APIGatewayPort_DeleteStage_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.DeleteStageInput) (*apigateway.DeleteStageOutput, error)) *APIGatewayPort_DeleteStage_Call {
	_c.Call.Return(run)
	return _c
}

// GetDeployments provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetDeployments(ctx context.Context, input *apigateway.GetDeploymentsInput) (*apigateway.GetDeploymentsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetDeployments")
	}

	var r0 *apigateway.GetDeploymentsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetDeploymentsInput) (*apigateway.GetDeploymentsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetDeploymentsInput) *apigateway.GetDeploymentsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetDeploymentsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetDeploymentsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetDeployments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDeployments'
type APIGatewayPort_GetDeployments_Call struct {
	*mock.Call
}

// GetDeployments is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetDeploymentsInput
func (_e *APIGatewayPort_Expecter) GetDeployments(ctx interface{}, input interface{}) *APIGatewayPort_GetDeployments_Call {
	return &APIGatewayPort_GetDeployments_Call{Call: _e.mock.On("GetDeployments", ctx, input)}
}

func (_c *APIGatewayPort_GetDeployments_Call) Run(run func(ctx context.Context, input *apigateway.GetDeploymentsInput)) *APIGatewayPort_GetDeployments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetDeploymentsInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetDeploymentsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetDeployments_Call) Return(getDeploymentsOutput *apigateway.GetDeploymentsOutput, err error) *APIGatewayPort_GetDeployments_Call {
	_c.Call.Return(getDeploymentsOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetDeployments_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetDeploymentsInput) (*apigateway.GetDeploymentsOutput, error)) *APIGatewayPort_GetDeployments_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntegration provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetIntegration(ctx context.Context, input *apigateway.GetIntegrationInput) (*apigateway.GetIntegrationOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetIntegration")
	}

	var r0 *apigateway.GetIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetIntegrationInput) (*apigateway.GetIntegrationOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetIntegrationInput) *apigateway.GetIntegrationOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetIntegrationInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntegration'
type APIGatewayPort_GetIntegration_Call struct {
	*mock.Call
}

// GetIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetIntegrationInput
func (_e *APIGatewayPort_Expecter) GetIntegration(ctx interface{}, input interface{}) *APIGatewayPort_GetIntegration_Call {
	return &APIGatewayPort_GetIntegration_Call{Call: _e.mock.On("GetIntegration", ctx, input)}
}

func (_c *APIGatewayPort_GetIntegration_Call) Run(run func(ctx context.Context, input *apigateway.GetIntegrationInput)) *APIGatewayPort_GetIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetIntegrationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetIntegration_Call) Return(getIntegrationOutput *apigateway.GetIntegrationOutput, err error) *APIGatewayPort_GetIntegration_Call {
	_c.Call.Return(getIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetIntegrationInput) (*apigateway.GetIntegrationOutput, error)) *APIGatewayPort_GetIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// GetMethod provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetMethod(ctx context.Context, input *apigateway.GetMethodInput) (*apigateway.GetMethodOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetMethod")
	}

	var r0 *apigateway.GetMethodOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetMethodInput) (*apigateway.GetMethodOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetMethodInput) *apigateway.GetMethodOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetMethodOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetMethodInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMethod'
type APIGatewayPort_GetMethod_Call struct {
	*mock.Call
}

// GetMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetMethodInput
func (_e *APIGatewayPort_Expecter) GetMethod(ctx interface{}, input interface{}) *APIGatewayPort_GetMethod_Call {
	return &APIGatewayPort_GetMethod_Call{Call: _e.mock.On("GetMethod", ctx, input)}
}

func (_c *APIGatewayPort_GetMethod_Call) Run(run func(ctx context.Context, input *apigateway.GetMethodInput)) *APIGatewayPort_GetMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetMethodInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetMethodInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetMethod_Call) Return(getMethodOutput *apigateway.GetMethodOutput, err error) *APIGatewayPort_GetMethod_Call {
	_c.Call.Return(getMethodOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetMethod_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetMethodInput) (*apigateway.GetMethodOutput, error)) *APIGatewayPort_GetMethod_Call {
	_c.Call.Return(run)
	return _c
}

// GetResource provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetResource(ctx context.Context, input *apigateway.GetResourceInput) (*apigateway.GetResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetResource")
	}

	var r0 *apigateway.GetResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetResourceInput) (*apigateway.GetResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetResourceInput) *apigateway.GetResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResource'
type APIGatewayPort_GetResource_Call struct {
	*mock.Call
}

// GetResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetResourceInput
func (_e *APIGatewayPort_Expecter) GetResource(ctx interface{}, input interface{}) *APIGatewayPort_GetResource_Call {
	return &APIGatewayPort_GetResource_Call{Call: _e.mock.On("GetResource", ctx, input)}
}

func (_c *APIGatewayPort_GetResource_Call) Run(run func(ctx context.Context, input *apigateway.GetResourceInput)) *APIGatewayPort_GetResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetResourceInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetResource_Call) Return(getResourceOutput *apigateway.GetResourceOutput, err error) *APIGatewayPort_GetResource_Call {
	_c.Call.Return(getResourceOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetResource_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetResourceInput) (*apigateway.GetResourceOutput, error)) *APIGatewayPort_GetResource_Call {
	_c.Call.Return(run)
	return _c
}

// GetResources provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetResources(ctx context.Context, input *apigateway.GetResourcesInput) (*apigateway.GetResourcesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetResources")
	}

	var r0 *apigateway.GetResourcesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetResourcesInput) (*apigateway.GetResourcesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetResourcesInput) *apigateway.GetResourcesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetResourcesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetResourcesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetResources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetResources'
type APIGatewayPort_GetResources_Call struct {
	*mock.Call
}

// GetResources is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetResourcesInput
func (_e *APIGatewayPort_Expecter) GetResources(ctx interface{}, input interface{}) *APIGatewayPort_GetResources_Call {
	return &APIGatewayPort_GetResources_Call{Call: _e.mock.On("GetResources", ctx, input)}
}

func (_c *APIGatewayPort_GetResources_Call) Run(run func(ctx context.Context, input *apigateway.GetResourcesInput)) *APIGatewayPort_GetResources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetResourcesInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetResourcesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetResources_Call) Return(getResourcesOutput *apigateway.GetResourcesOutput, err error) *APIGatewayPort_GetResources_Call {
	_c.Call.Return(getResourcesOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetResources_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetResourcesInput) (*apigateway.GetResourcesOutput, error)) *APIGatewayPort_GetResources_Call {
	_c.Call.Return(run)
	return _c
}

// GetRestApi provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetRestApi(ctx context.Context, input *apigateway.GetRestApiInput) (*apigateway.GetRestApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRestApi")
	}

	var r0 *apigateway.GetRestApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetRestApiInput) (*apigateway.GetRestApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetRestApiInput) *apigateway.GetRestApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetRestApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetRestApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetRestApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestApi'
type APIGatewayPort_GetRestApi_Call struct {
	*mock.Call
}

// GetRestApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetRestApiInput
func (_e *APIGatewayPort_Expecter) GetRestApi(ctx interface{}, input interface{}) *APIGatewayPort_GetRestApi_Call {
	return &APIGatewayPort_GetRestApi_Call{Call: _e.mock.On("GetRestApi", ctx, input)}
}

func (_c *APIGatewayPort_GetRestApi_Call) Run(run func(ctx context.Context, input *apigateway.GetRestApiInput)) *APIGatewayPort_GetRestApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetRestApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetRestApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetRestApi_Call) Return(getRestApiOutput *apigateway.GetRestApiOutput, err error) *APIGatewayPort_GetRestApi_Call {
	_c.Call.Return(getRestApiOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetRestApi_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetRestApiInput) (*apigateway.GetRestApiOutput, error)) *APIGatewayPort_GetRestApi_Call {
	_c.Call.Return(run)
	return _c
}

// GetRestApis provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetRestApis(ctx context.Context, input *apigateway.GetRestApisInput) (*apigateway.GetRestApisOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRestApis")
	}

	var r0 *apigateway.GetRestApisOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetRestApisInput) (*apigateway.GetRestApisOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetRestApisInput) *apigateway.GetRestApisOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetRestApisOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetRestApisInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetRestApis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRestApis'
type APIGatewayPort_GetRestApis_Call struct {
	*mock.Call
}

// GetRestApis is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetRestApisInput
func (_e *APIGatewayPort_Expecter) GetRestApis(ctx interface{}, input interface{}) *APIGatewayPort_GetRestApis_Call {
	return &APIGatewayPort_GetRestApis_Call{Call: _e.mock.On("GetRestApis", ctx, input)}
}

func (_c *APIGatewayPort_GetRestApis_Call) Run(run func(ctx context.Context, input *apigateway.GetRestApisInput)) *APIGatewayPort_GetRestApis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetRestApisInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetRestApisInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetRestApis_Call) Return(getRestApisOutput *apigateway.GetRestApisOutput, err error) *APIGatewayPort_GetRestApis_Call {
	_c.Call.Return(getRestApisOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetRestApis_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetRestApisInput) (*apigateway.GetRestApisOutput, error)) *APIGatewayPort_GetRestApis_Call {
	_c.Call.Return(run)
	return _c
}

// GetStages provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) GetStages(ctx context.Context, input *apigateway.GetStagesInput) (*apigateway.GetStagesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetStages")
	}

	var r0 *apigateway.GetStagesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetStagesInput) (*apigateway.GetStagesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.GetStagesInput) *apigateway.GetStagesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.GetStagesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.GetStagesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_GetStages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStages'
type APIGatewayPort_GetStages_Call struct {
	*mock.Call
}

// GetStages is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.GetStagesInput
func (_e *APIGatewayPort_Expecter) GetStages(ctx interface{}, input interface{}) *APIGatewayPort_GetStages_Call {
	return &APIGatewayPort_GetStages_Call{Call: _e.mock.On("GetStages", ctx, input)}
}

func (_c *APIGatewayPort_GetStages_Call) Run(run func(ctx context.Context, input *apigateway.GetStagesInput)) *APIGatewayPort_GetStages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.GetStagesInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.GetStagesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_GetStages_Call) Return(getStagesOutput *apigateway.GetStagesOutput, err error) *APIGatewayPort_GetStages_Call {
	_c.Call.Return(getStagesOutput, err)
	return _c
}

func (_c *APIGatewayPort_GetStages_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.GetStagesInput) (*apigateway.GetStagesOutput, error)) *APIGatewayPort_GetStages_Call {
	_c.Call.Return(run)
	return _c
}

// ImportRestApi provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) ImportRestApi(ctx context.Context, input *apigateway.ImportRestApiInput) (*apigateway.ImportRestApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ImportRestApi")
	}

	var r0 *apigateway.ImportRestApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.ImportRestApiInput) (*apigateway.ImportRestApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.ImportRestApiInput) *apigateway.ImportRestApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.ImportRestApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.ImportRestApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_ImportRestApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportRestApi'
type APIGatewayPort_ImportRestApi_Call struct {
	*mock.Call
}

// ImportRestApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.ImportRestApiInput
func (_e *APIGatewayPort_Expecter) ImportRestApi(ctx interface{}, input interface{}) *APIGatewayPort_ImportRestApi_Call {
	return &APIGatewayPort_ImportRestApi_Call{Call: _e.mock.On("ImportRestApi", ctx, input)}
}

func (_c *APIGatewayPort_ImportRestApi_Call) Run(run func(ctx context.Context, input *apigateway.ImportRestApiInput)) *APIGatewayPort_ImportRestApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.ImportRestApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.ImportRestApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_ImportRestApi_Call) Return(importRestApiOutput *apigateway.ImportRestApiOutput, err error) *APIGatewayPort_ImportRestApi_Call {
	_c.Call.Return(importRestApiOutput, err)
	return _c
}

func (_c *APIGatewayPort_ImportRestApi_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.ImportRestApiInput) (*apigateway.ImportRestApiOutput, error)) *APIGatewayPort_ImportRestApi_Call {
	_c.Call.Return(run)
	return _c
}

// PutIntegration provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) PutIntegration(ctx context.Context, input *apigateway.PutIntegrationInput) (*apigateway.PutIntegrationOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutIntegration")
	}

	var r0 *apigateway.PutIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.PutIntegrationInput) (*apigateway.PutIntegrationOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.PutIntegrationInput) *apigateway.PutIntegrationOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.PutIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.PutIntegrationInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_PutIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutIntegration'
type APIGatewayPort_PutIntegration_Call struct {
	*mock.Call
}

// PutIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.PutIntegrationInput
func (_e *APIGatewayPort_Expecter) PutIntegration(ctx interface{}, input interface{}) *APIGatewayPort_PutIntegration_Call {
	return &APIGatewayPort_PutIntegration_Call{Call: _e.mock.On("PutIntegration", ctx, input)}
}

func (_c *APIGatewayPort_PutIntegration_Call) Run(run func(ctx context.Context, input *apigateway.PutIntegrationInput)) *APIGatewayPort_PutIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.PutIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.PutIntegrationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_PutIntegration_Call) Return(putIntegrationOutput *apigateway.PutIntegrationOutput, err error) *APIGatewayPort_PutIntegration_Call {
	_c.Call.Return(putIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayPort_PutIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.PutIntegrationInput) (*apigateway.PutIntegrationOutput, error)) *APIGatewayPort_PutIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// PutMethod provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) PutMethod(ctx context.Context, input *apigateway.PutMethodInput) (*apigateway.PutMethodOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutMethod")
	}

	var r0 *apigateway.PutMethodOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.PutMethodInput) (*apigateway.PutMethodOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.PutMethodInput) *apigateway.PutMethodOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.PutMethodOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.PutMethodInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_PutMethod_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutMethod'
type APIGatewayPort_PutMethod_Call struct {
	*mock.Call
}

// PutMethod is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.PutMethodInput
func (_e *APIGatewayPort_Expecter) PutMethod(ctx interface{}, input interface{}) *APIGatewayPort_PutMethod_Call {
	return &APIGatewayPort_PutMethod_Call{Call: _e.mock.On("PutMethod", ctx, input)}
}

func (_c *APIGatewayPort_PutMethod_Call) Run(run func(ctx context.Context, input *apigateway.PutMethodInput)) *APIGatewayPort_PutMethod_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.PutMethodInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.PutMethodInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_PutMethod_Call) Return(putMethodOutput *apigateway.PutMethodOutput, err error) *APIGatewayPort_PutMethod_Call {
	_c.Call.Return(putMethodOutput, err)
	return _c
}

func (_c *APIGatewayPort_PutMethod_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.PutMethodInput) (*apigateway.PutMethodOutput, error)) *APIGatewayPort_PutMethod_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateRestApi provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) UpdateRestApi(ctx context.Context, input *apigateway.UpdateRestApiInput) (*apigateway.UpdateRestApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateRestApi")
	}

	var r0 *apigateway.UpdateRestApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.UpdateRestApiInput) (*apigateway.UpdateRestApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.UpdateRestApiInput) *apigateway.UpdateRestApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.UpdateRestApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.UpdateRestApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_UpdateRestApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateRestApi'
type APIGatewayPort_UpdateRestApi_Call struct {
	*mock.Call
}

// UpdateRestApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.UpdateRestApiInput
func (_e *APIGatewayPort_Expecter) UpdateRestApi(ctx interface{}, input interface{}) *APIGatewayPort_UpdateRestApi_Call {
	return &APIGatewayPort_UpdateRestApi_Call{Call: _e.mock.On("UpdateRestApi", ctx, input)}
}

func (_c *APIGatewayPort_UpdateRestApi_Call) Run(run func(ctx context.Context, input *apigateway.UpdateRestApiInput)) *APIGatewayPort_UpdateRestApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.UpdateRestApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.UpdateRestApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_UpdateRestApi_Call) Return(updateRestApiOutput *apigateway.UpdateRestApiOutput, err error) *APIGatewayPort_UpdateRestApi_Call {
	_c.Call.Return(updateRestApiOutput, err)
	return _c
}

func (_c *APIGatewayPort_UpdateRestApi_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.UpdateRestApiInput) (*apigateway.UpdateRestApiOutput, error)) *APIGatewayPort_UpdateRestApi_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateStage provides a mock function for the type APIGatewayPort
func (_mock *APIGatewayPort) UpdateStage(ctx context.Context, input *apigateway.UpdateStageInput) (*apigateway.UpdateStageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateStage")
	}

	var r0 *apigateway.UpdateStageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.UpdateStageInput) (*apigateway.UpdateStageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigateway.UpdateStageInput) *apigateway.UpdateStageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigateway.UpdateStageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigateway.UpdateStageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayPort_UpdateStage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateStage'
type APIGatewayPort_UpdateStage_Call struct {
	*mock.Call
}

// UpdateStage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigateway.UpdateStageInput
func (_e *APIGatewayPort_Expecter) UpdateStage(ctx interface{}, input interface{}) *APIGatewayPort_UpdateStage_Call {
	return &APIGatewayPort_UpdateStage_Call{Call: _e.mock.On("UpdateStage", ctx, input)}
}

func (_c *APIGatewayPort_UpdateStage_Call) Run(run func(ctx context.Context, input *apigateway.UpdateStageInput)) *APIGatewayPort_UpdateStage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigateway.UpdateStageInput
		if args[1] != nil {
			arg1 = args[1].(*apigateway.UpdateStageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayPort_UpdateStage_Call) Return(updateStageOutput *apigateway.UpdateStageOutput, err error) *APIGatewayPort_UpdateStage_Call {
	_c.Call.Return(updateStageOutput, err)
	return _c
}

func (_c *APIGatewayPort_UpdateStage_Call) RunAndReturn(run func(ctx context.Context, input *apigateway.UpdateStageInput) (*apigateway.UpdateStageOutput, error)) *APIGatewayPort_UpdateStage_Call {
	_c.Call.Return(run)
	return _c
}
