// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/apigatewayv2"
	mock "github.com/stretchr/testify/mock"
)

// NewAPIGatewayV2Port creates a new instance of APIGatewayV2Port. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAPIGatewayV2Port(t interface {
	mock.TestingT
	Cleanup(func())
}) *APIGatewayV2Port {
	mock := &APIGatewayV2Port{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// APIGatewayV2Port is an autogenerated mock type for the APIGatewayV2Port type
type APIGatewayV2Port struct {
	mock.Mock
}

type APIGatewayV2Port_Expecter struct {
	mock *mock.Mock
}

func (_m *APIGatewayV2Port) EXPECT() *APIGatewayV2Port_Expecter {
	return &APIGatewayV2Port_Expecter{mock: &_m.Mock}
}

// CreateApi provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) CreateApi(ctx context.Context, input *apigatewayv2.CreateApiInput) (*apigatewayv2.CreateApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateApi")
	}

	var r0 *apigatewayv2.CreateApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateApiInput) (*apigatewayv2.CreateApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateApiInput) *apigatewayv2.CreateApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_CreateApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateApi'
type APIGatewayV2Port_CreateApi_Call struct {
	*mock.Call
}

// CreateApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateApiInput
func (_e *APIGatewayV2Port_Expecter) CreateApi(ctx interface{}, input interface{}) *APIGatewayV2Port_CreateApi_Call {
	return &APIGatewayV2Port_CreateApi_Call{Call: _e.mock.On("CreateApi", ctx, input)}
}

func (_c *APIGatewayV2Port_CreateApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateApiInput)) *APIGatewayV2Port_CreateApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_CreateApi_Call) Return(createApiOutput *apigatewayv2.CreateApiOutput, err error) *APIGatewayV2Port_CreateApi_Call {
	_c.Call.Return(createApiOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_CreateApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateApiInput) (*apigatewayv2.CreateApiOutput, error)) *APIGatewayV2Port_CreateApi_Call {
	_c.Call.Return(run)
	return _c
}

// CreateIntegration provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) CreateIntegration(ctx context.Context, input *apigatewayv2.CreateIntegrationInput) (*apigatewayv2.CreateIntegrationOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateIntegration")
	}

	var r0 *apigatewayv2.CreateIntegrationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateIntegrationInput) (*apigatewayv2.CreateIntegrationOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateIntegrationInput) *apigatewayv2.CreateIntegrationOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateIntegrationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateIntegrationInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_CreateIntegration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateIntegration'
type APIGatewayV2Port_CreateIntegration_Call struct {
	*mock.Call
}

// CreateIntegration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateIntegrationInput
func (_e *APIGatewayV2Port_Expecter) CreateIntegration(ctx interface{}, input interface{}) *APIGatewayV2Port_CreateIntegration_Call {
	return &APIGatewayV2Port_CreateIntegration_Call{Call: _e.mock.On("CreateIntegration", ctx, input)}
}

func (_c *APIGatewayV2Port_CreateIntegration_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateIntegrationInput)) *APIGatewayV2Port_CreateIntegration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateIntegrationInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateIntegrationInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_CreateIntegration_Call) Return(createIntegrationOutput *apigatewayv2.CreateIntegrationOutput, err error) *APIGatewayV2Port_CreateIntegration_Call {
	_c.Call.Return(createIntegrationOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_CreateIntegration_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateIntegrationInput) (*apigatewayv2.CreateIntegrationOutput, error)) *APIGatewayV2Port_CreateIntegration_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRoute provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) CreateRoute(ctx context.Context, input *apigatewayv2.CreateRouteInput) (*apigatewayv2.CreateRouteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateRoute")
	}

	var r0 *apigatewayv2.CreateRouteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateRouteInput) (*apigatewayv2.CreateRouteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.CreateRouteInput) *apigatewayv2.CreateRouteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.CreateRouteOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.CreateRouteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_CreateRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRoute'
type APIGatewayV2Port_CreateRoute_Call struct {
	*mock.Call
}

// CreateRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.CreateRouteInput
func (_e *APIGatewayV2Port_Expecter) CreateRoute(ctx interface{}, input interface{}) *APIGatewayV2Port_CreateRoute_Call {
	return &APIGatewayV2Port_CreateRoute_Call{Call: _e.mock.On("CreateRoute", ctx, input)}
}

func (_c *APIGatewayV2Port_CreateRoute_Call) Run(run func(ctx context.Context, input *apigatewayv2.CreateRouteInput)) *APIGatewayV2Port_CreateRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.CreateRouteInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.CreateRouteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_CreateRoute_Call) Return(createRouteOutput *apigatewayv2.CreateRouteOutput, err error) *APIGatewayV2Port_CreateRoute_Call {
	_c.Call.Return(createRouteOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_CreateRoute_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.CreateRouteInput) (*apigatewayv2.CreateRouteOutput, error)) *APIGatewayV2Port_CreateRoute_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteApi provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) DeleteApi(ctx context.Context, input *apigatewayv2.DeleteApiInput) (*apigatewayv2.DeleteApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteApi")
	}

	var r0 *apigatewayv2.DeleteApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteApiInput) (*apigatewayv2.DeleteApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteApiInput) *apigatewayv2.DeleteApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_DeleteApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteApi'
type APIGatewayV2Port_DeleteApi_Call struct {
	*mock.Call
}

// DeleteApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteApiInput
func (_e *APIGatewayV2Port_Expecter) DeleteApi(ctx interface{}, input interface{}) *APIGatewayV2Port_DeleteApi_Call {
	return &APIGatewayV2Port_DeleteApi_Call{Call: _e.mock.On("DeleteApi", ctx, input)}
}

func (_c *APIGatewayV2Port_DeleteApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteApiInput)) *APIGatewayV2Port_DeleteApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_DeleteApi_Call) Return(deleteApiOutput *apigatewayv2.DeleteApiOutput, err error) *APIGatewayV2Port_DeleteApi_Call {
	_c.Call.Return(deleteApiOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_DeleteApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteApiInput) (*apigatewayv2.DeleteApiOutput, error)) *APIGatewayV2Port_DeleteApi_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRoute provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) DeleteRoute(ctx context.Context, input *apigatewayv2.DeleteRouteInput) (*apigatewayv2.DeleteRouteOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRoute")
	}

	var r0 *apigatewayv2.DeleteRouteOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteRouteInput) (*apigatewayv2.DeleteRouteOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.DeleteRouteInput) *apigatewayv2.DeleteRouteOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.DeleteRouteOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.DeleteRouteInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_DeleteRoute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRoute'
type APIGatewayV2Port_DeleteRoute_Call struct {
	*mock.Call
}

// DeleteRoute is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.DeleteRouteInput
func (_e *APIGatewayV2Port_Expecter) DeleteRoute(ctx interface{}, input interface{}) *APIGatewayV2Port_DeleteRoute_Call {
	return &APIGatewayV2Port_DeleteRoute_Call{Call: _e.mock.On("DeleteRoute", ctx, input)}
}

func (_c *APIGatewayV2Port_DeleteRoute_Call) Run(run func(ctx context.Context, input *apigatewayv2.DeleteRouteInput)) *APIGatewayV2Port_DeleteRoute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.DeleteRouteInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.DeleteRouteInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_DeleteRoute_Call) Return(deleteRouteOutput *apigatewayv2.DeleteRouteOutput, err error) *APIGatewayV2Port_DeleteRoute_Call {
	_c.Call.Return(deleteRouteOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_DeleteRoute_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.DeleteRouteInput) (*apigatewayv2.DeleteRouteOutput, error)) *APIGatewayV2Port_DeleteRoute_Call {
	_c.Call.Return(run)
	return _c
}

// GetApi provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) GetApi(ctx context.Context, input *apigatewayv2.GetApiInput) (*apigatewayv2.GetApiOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetApi")
	}

	var r0 *apigatewayv2.GetApiOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApiInput) (*apigatewayv2.GetApiOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApiInput) *apigatewayv2.GetApiOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetApiOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetApiInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_GetApi_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApi'
type APIGatewayV2Port_GetApi_Call struct {
	*mock.Call
}

// GetApi is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetApiInput
func (_e *APIGatewayV2Port_Expecter) GetApi(ctx interface{}, input interface{}) *APIGatewayV2Port_GetApi_Call {
	return &APIGatewayV2Port_GetApi_Call{Call: _e.mock.On("GetApi", ctx, input)}
}

func (_c *APIGatewayV2Port_GetApi_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetApiInput)) *APIGatewayV2Port_GetApi_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetApiInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetApiInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_GetApi_Call) Return(getApiOutput *apigatewayv2.GetApiOutput, err error) *APIGatewayV2Port_GetApi_Call {
	_c.Call.Return(getApiOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_GetApi_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetApiInput) (*apigatewayv2.GetApiOutput, error)) *APIGatewayV2Port_GetApi_Call {
	_c.Call.Return(run)
	return _c
}

// GetApis provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) GetApis(ctx context.Context, input *apigatewayv2.GetApisInput) (*apigatewayv2.GetApisOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetApis")
	}

	var r0 *apigatewayv2.GetApisOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApisInput) (*apigatewayv2.GetApisOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetApisInput) *apigatewayv2.GetApisOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetApisOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetApisInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_GetApis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApis'
type APIGatewayV2Port_GetApis_Call struct {
	*mock.Call
}

// GetApis is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetApisInput
func (_e *APIGatewayV2Port_Expecter) GetApis(ctx interface{}, input interface{}) *APIGatewayV2Port_GetApis_Call {
	return &APIGatewayV2Port_GetApis_Call{Call: _e.mock.On("GetApis", ctx, input)}
}

func (_c *APIGatewayV2Port_GetApis_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetApisInput)) *APIGatewayV2Port_GetApis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetApisInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetApisInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_GetApis_Call) Return(getApisOutput *apigatewayv2.GetApisOutput, err error) *APIGatewayV2Port_GetApis_Call {
	_c.Call.Return(getApisOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_GetApis_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetApisInput) (*apigatewayv2.GetApisOutput, error)) *APIGatewayV2Port_GetApis_Call {
	_c.Call.Return(run)
	return _c
}

// GetIntegrations provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) GetIntegrations(ctx context.Context, input *apigatewayv2.GetIntegrationsInput) (*apigatewayv2.GetIntegrationsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetIntegrations")
	}

	var r0 *apigatewayv2.GetIntegrationsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetIntegrationsInput) (*apigatewayv2.GetIntegrationsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetIntegrationsInput) *apigatewayv2.GetIntegrationsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetIntegrationsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetIntegrationsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_GetIntegrations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIntegrations'
type APIGatewayV2Port_GetIntegrations_Call struct {
	*mock.Call
}

// GetIntegrations is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetIntegrationsInput
func (_e *APIGatewayV2Port_Expecter) GetIntegrations(ctx interface{}, input interface{}) *APIGatewayV2Port_GetIntegrations_Call {
	return &APIGatewayV2Port_GetIntegrations_Call{Call: _e.mock.On("GetIntegrations", ctx, input)}
}

func (_c *APIGatewayV2Port_GetIntegrations_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetIntegrationsInput)) *APIGatewayV2Port_GetIntegrations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetIntegrationsInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetIntegrationsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_GetIntegrations_Call) Return(getIntegrationsOutput *apigatewayv2.GetIntegrationsOutput, err error) *APIGatewayV2Port_GetIntegrations_Call {
	_c.Call.Return(getIntegrationsOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_GetIntegrations_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetIntegrationsInput) (*apigatewayv2.GetIntegrationsOutput, error)) *APIGatewayV2Port_GetIntegrations_Call {
	_c.Call.Return(run)
	return _c
}

// GetRoutes provides a mock function for the type APIGatewayV2Port
func (_mock *APIGatewayV2Port) GetRoutes(ctx context.Context, input *apigatewayv2.GetRoutesInput) (*apigatewayv2.GetRoutesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRoutes")
	}

	var r0 *apigatewayv2.GetRoutesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetRoutesInput) (*apigatewayv2.GetRoutesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *apigatewayv2.GetRoutesInput) *apigatewayv2.GetRoutesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*apigatewayv2.GetRoutesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *apigatewayv2.GetRoutesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// APIGatewayV2Port_GetRoutes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRoutes'
type APIGatewayV2Port_GetRoutes_Call struct {
	*mock.Call
}

// GetRoutes is a helper method to define mock.On call
//   - ctx context.Context
//   - input *apigatewayv2.GetRoutesInput
func (_e *APIGatewayV2Port_Expecter) GetRoutes(ctx interface{}, input interface{}) *APIGatewayV2Port_GetRoutes_Call {
	return &APIGatewayV2Port_GetRoutes_Call{Call: _e.mock.On("GetRoutes", ctx, input)}
}

func (_c *APIGatewayV2Port_GetRoutes_Call) Run(run func(ctx context.Context, input *apigatewayv2.GetRoutesInput)) *APIGatewayV2Port_GetRoutes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *apigatewayv2.GetRoutesInput
		if args[1] != nil {
			arg1 = args[1].(*apigatewayv2.GetRoutesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *APIGatewayV2Port_GetRoutes_Call) Return(getRoutesOutput *apigatewayv2.GetRoutesOutput, err error) *APIGatewayV2Port_GetRoutes_Call {
	_c.Call.Return(getRoutesOutput, err)
	return _c
}

func (_c *APIGatewayV2Port_GetRoutes_Call) RunAndReturn(run func(ctx context.Context, input *apigatewayv2.GetRoutesInput) (*apigatewayv2.GetRoutesOutput, error)) *APIGatewayV2Port_GetRoutes_Call {
	_c.Call.Return(run)
	return _c
}
