// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/beabys/ayotl"
	"github.com/my-devstack/mydevstack-proxy/internal/config"
	"github.com/my-devstack/mydevstack-proxy/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewConfigPort creates a new instance of ConfigPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewConfigPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *ConfigPort {
	mock := &ConfigPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ConfigPort is an autogenerated mock type for the ConfigPort type
type ConfigPort struct {
	mock.Mock
}

type ConfigPort_Expecter struct {
	mock *mock.Mock
}

func (_m *ConfigPort) EXPECT() *ConfigPort_Expecter {
	return &ConfigPort_Expecter{mock: &_m.Mock}
}

// GetConfigs provides a mock function for the type ConfigPort
func (_mock *ConfigPort) GetConfigs() *configloader.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfigs")
	}

	var r0 *configloader.Config
	if returnFunc, ok := ret.Get(0).(func() *configloader.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configloader.Config)
		}
	}
	return r0
}

// ConfigPort_GetConfigs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfigs'
type ConfigPort_GetConfigs_Call struct {
	*mock.Call
}

// GetConfigs is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) GetConfigs() *ConfigPort_GetConfigs_Call {
	return &ConfigPort_GetConfigs_Call{Call: _e.mock.On("GetConfigs")}
}

func (_c *ConfigPort_GetConfigs_Call) Run(run func()) *ConfigPort_GetConfigs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_GetConfigs_Call) Return(config *configloader.Config) *ConfigPort_GetConfigs_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *ConfigPort_GetConfigs_Call) RunAndReturn(run func() *configloader.Config) *ConfigPort_GetConfigs_Call {
	_c.Call.Return(run)
	return _c
}

// LoadConfig provides a mock function for the type ConfigPort
func (_mock *ConfigPort) LoadConfig(ctx context.Context) (ports.ConfigPort, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for LoadConfig")
	}

	var r0 ports.ConfigPort
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (ports.ConfigPort, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) ports.ConfigPort); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.ConfigPort)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// ConfigPort_LoadConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LoadConfig'
type ConfigPort_LoadConfig_Call struct {
	*mock.Call
}

// LoadConfig is a helper method to define mock.On call
//   - ctx context.Context
func (_e *ConfigPort_Expecter) LoadConfig(ctx interface{}) *ConfigPort_LoadConfig_Call {
	return &ConfigPort_LoadConfig_Call{Call: _e.mock.On("LoadConfig", ctx)}
}

func (_c *ConfigPort_LoadConfig_Call) Run(run func(ctx context.Context)) *ConfigPort_LoadConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ConfigPort_LoadConfig_Call) Return(configPort ports.ConfigPort, err error) *ConfigPort_LoadConfig_Call {
	_c.Call.Return(configPort, err)
	return _c
}

func (_c *ConfigPort_LoadConfig_Call) RunAndReturn(run func(ctx context.Context) (ports.ConfigPort, error)) *ConfigPort_LoadConfig_Call {
	_c.Call.Return(run)
	return _c
}

// SetDefaults provides a mock function for the type ConfigPort
func (_mock *ConfigPort) SetDefaults() config.ConfigMap {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetDefaults")
	}

	var r0 config.ConfigMap
	if returnFunc, ok := ret.Get(0).(func() config.ConfigMap); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ConfigMap)
		}
	}
	return r0
}

// ConfigPort_SetDefaults_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDefaults'
type ConfigPort_SetDefaults_Call struct {
	*mock.Call
}

// SetDefaults is a helper method to define mock.On call
func (_e *ConfigPort_Expecter) SetDefaults() *ConfigPort_SetDefaults_Call {
	return &ConfigPort_SetDefaults_Call{Call: _e.mock.On("SetDefaults")}
}

func (_c *ConfigPort_SetDefaults_Call) Run(run func()) *ConfigPort_SetDefaults_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ConfigPort_SetDefaults_Call) Return(configMap config.ConfigMap) *ConfigPort_SetDefaults_Call {
	_c.Call.Return(configMap)
	return _c
}

func (_c *ConfigPort_SetDefaults_Call) RunAndReturn(run func() config.ConfigMap) *ConfigPort_SetDefaults_Call {
	_c.Call.Return(run)
	return _c
}
