// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// NewDynamoDBPort creates a new instance of DynamoDBPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoDBPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoDBPort {
	mock := &DynamoDBPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DynamoDBPort is an autogenerated mock type for the DynamoDBPort type
type DynamoDBPort struct {
	mock.Mock
}

type DynamoDBPort_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamoDBPort) EXPECT() *DynamoDBPort_Expecter {
	return &DynamoDBPort_Expecter{mock: &_m.Mock}
}

// BatchGetItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) BatchGetItem(ctx context.Context, input *dynamodb.BatchGetItemInput) (*dynamodb.BatchGetItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for BatchGetItem")
	}

	var r0 *dynamodb.BatchGetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchGetItemInput) (*dynamodb.BatchGetItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchGetItemInput) *dynamodb.BatchGetItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchGetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.BatchGetItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_BatchGetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchGetItem'
type DynamoDBPort_BatchGetItem_Call struct {
	*mock.Call
}

// BatchGetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.BatchGetItemInput
func (_e *DynamoDBPort_Expecter) BatchGetItem(ctx interface{}, input interface{}) *DynamoDBPort_BatchGetItem_Call {
	return &DynamoDBPort_BatchGetItem_Call{Call: _e.mock.On("BatchGetItem", ctx, input)}
}

func (_c *DynamoDBPort_BatchGetItem_Call) Run(run func(ctx context.Context, input *dynamodb.BatchGetItemInput)) *DynamoDBPort_BatchGetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.BatchGetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.BatchGetItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_BatchGetItem_Call) Return(batchGetItemOutput *dynamodb.BatchGetItemOutput, err error) *DynamoDBPort_BatchGetItem_Call {
	_c.Call.Return(batchGetItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_BatchGetItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.BatchGetItemInput) (*dynamodb.BatchGetItemOutput, error)) *DynamoDBPort_BatchGetItem_Call {
	_c.Call.Return(run)
	return _c
}

// BatchWriteItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) BatchWriteItem(ctx context.Context, input *dynamodb.BatchWriteItemInput) (*dynamodb.BatchWriteItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for BatchWriteItem")
	}

	var r0 *dynamodb.BatchWriteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput) (*dynamodb.BatchWriteItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput) *dynamodb.BatchWriteItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchWriteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.BatchWriteItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_BatchWriteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchWriteItem'
type DynamoDBPort_BatchWriteItem_Call struct {
	*mock.Call
}

// BatchWriteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.BatchWriteItemInput
func (_e *DynamoDBPort_Expecter) BatchWriteItem(ctx interface{}, input interface{}) *DynamoDBPort_BatchWriteItem_Call {
	return &DynamoDBPort_BatchWriteItem_Call{Call: _e.mock.On("BatchWriteItem", ctx, input)}
}

func (_c *DynamoDBPort_BatchWriteItem_Call) Run(run func(ctx context.Context, input *dynamodb.BatchWriteItemInput)) *DynamoDBPort_BatchWriteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.BatchWriteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.BatchWriteItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_BatchWriteItem_Call) Return(batchWriteItemOutput *dynamodb.BatchWriteItemOutput, err error) *DynamoDBPort_BatchWriteItem_Call {
	_c.Call.Return(batchWriteItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_BatchWriteItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.BatchWriteItemInput) (*dynamodb.BatchWriteItemOutput, error)) *DynamoDBPort_BatchWriteItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTable provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) CreateTable(ctx context.Context, input *dynamodb.CreateTableInput) (*dynamodb.CreateTableOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateTable")
	}

	var r0 *dynamodb.CreateTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput) (*dynamodb.CreateTableOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput) *dynamodb.CreateTableOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.CreateTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.CreateTableInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_CreateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTable'
type DynamoDBPort_CreateTable_Call struct {
	*mock.Call
}

// CreateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.CreateTableInput
func (_e *DynamoDBPort_Expecter) CreateTable(ctx interface{}, input interface{}) *DynamoDBPort_CreateTable_Call {
	return &DynamoDBPort_CreateTable_Call{Call: _e.mock.On("CreateTable", ctx, input)}
}

func (_c *DynamoDBPort_CreateTable_Call) Run(run func(ctx context.Context, input *dynamodb.CreateTableInput)) *DynamoDBPort_CreateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.CreateTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.CreateTableInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_CreateTable_Call) Return(createTableOutput *dynamodb.CreateTableOutput, err error) *DynamoDBPort_CreateTable_Call {
	_c.Call.Return(createTableOutput, err)
	return _c
}

func (_c *DynamoDBPort_CreateTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.CreateTableInput) (*dynamodb.CreateTableOutput, error)) *DynamoDBPort_CreateTable_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) DeleteItem(ctx context.Context, input *dynamodb.DeleteItemInput) (*dynamodb.DeleteItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *dynamodb.DeleteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput) (*dynamodb.DeleteItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput) *dynamodb.DeleteItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type DynamoDBPort_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DeleteItemInput
func (_e *DynamoDBPort_Expecter) DeleteItem(ctx interface{}, input interface{}) *DynamoDBPort_DeleteItem_Call {
	return &DynamoDBPort_DeleteItem_Call{Call: _e.mock.On("DeleteItem", ctx, input)}
}

func (_c *DynamoDBPort_DeleteItem_Call) Run(run func(ctx context.Context, input *dynamodb.DeleteItemInput)) *DynamoDBPort_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_DeleteItem_Call) Return(deleteItemOutput *dynamodb.DeleteItemOutput, err error) *DynamoDBPort_DeleteItem_Call {
	_c.Call.Return(deleteItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DeleteItemInput) (*dynamodb.DeleteItemOutput, error)) *DynamoDBPort_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTable provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) DeleteTable(ctx context.Context, input *dynamodb.DeleteTableInput) (*dynamodb.DeleteTableOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteTable")
	}

	var r0 *dynamodb.DeleteTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteTableInput) (*dynamodb.DeleteTableOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteTableInput) *dynamodb.DeleteTableOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteTableInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_DeleteTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTable'
type DynamoDBPort_DeleteTable_Call struct {
	*mock.Call
}

// DeleteTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DeleteTableInput
func (_e *DynamoDBPort_Expecter) DeleteTable(ctx interface{}, input interface{}) *DynamoDBPort_DeleteTable_Call {
	return &DynamoDBPort_DeleteTable_Call{Call: _e.mock.On("DeleteTable", ctx, input)}
}

func (_c *DynamoDBPort_DeleteTable_Call) Run(run func(ctx context.Context, input *dynamodb.DeleteTableInput)) *DynamoDBPort_DeleteTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteTableInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_DeleteTable_Call) Return(deleteTableOutput *dynamodb.DeleteTableOutput, err error) *DynamoDBPort_DeleteTable_Call {
	_c.Call.Return(deleteTableOutput, err)
	return _c
}

func (_c *DynamoDBPort_DeleteTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DeleteTableInput) (*dynamodb.DeleteTableOutput, error)) *DynamoDBPort_DeleteTable_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTable provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) DescribeTable(ctx context.Context, input *dynamodb.DescribeTableInput) (*dynamodb.DescribeTableOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeTable")
	}

	var r0 *dynamodb.DescribeTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput) (*dynamodb.DescribeTableOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput) *dynamodb.DescribeTableOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTableInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_DescribeTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTable'
type DynamoDBPort_DescribeTable_Call struct {
	*mock.Call
}

// DescribeTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DescribeTableInput
func (_e *DynamoDBPort_Expecter) DescribeTable(ctx interface{}, input interface{}) *DynamoDBPort_DescribeTable_Call {
	return &DynamoDBPort_DescribeTable_Call{Call: _e.mock.On("DescribeTable", ctx, input)}
}

func (_c *DynamoDBPort_DescribeTable_Call) Run(run func(ctx context.Context, input *dynamodb.DescribeTableInput)) *DynamoDBPort_DescribeTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTableInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_DescribeTable_Call) Return(describeTableOutput *dynamodb.DescribeTableOutput, err error) *DynamoDBPort_DescribeTable_Call {
	_c.Call.Return(describeTableOutput, err)
	return _c
}

func (_c *DynamoDBPort_DescribeTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DescribeTableInput) (*dynamodb.DescribeTableOutput, error)) *DynamoDBPort_DescribeTable_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTimeToLive provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) DescribeTimeToLive(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput) (*dynamodb.DescribeTimeToLiveOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeTimeToLive")
	}

	var r0 *dynamodb.DescribeTimeToLiveOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTimeToLiveInput) (*dynamodb.DescribeTimeToLiveOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTimeToLiveInput) *dynamodb.DescribeTimeToLiveOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTimeToLiveOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTimeToLiveInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_DescribeTimeToLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTimeToLive'
type DynamoDBPort_DescribeTimeToLive_Call struct {
	*mock.Call
}

// DescribeTimeToLive is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DescribeTimeToLiveInput
func (_e *DynamoDBPort_Expecter) DescribeTimeToLive(ctx interface{}, input interface{}) *DynamoDBPort_DescribeTimeToLive_Call {
	return &DynamoDBPort_DescribeTimeToLive_Call{Call: _e.mock.On("DescribeTimeToLive", ctx, input)}
}

func (_c *DynamoDBPort_DescribeTimeToLive_Call) Run(run func(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput)) *DynamoDBPort_DescribeTimeToLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTimeToLiveInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTimeToLiveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_DescribeTimeToLive_Call) Return(describeTimeToLiveOutput *dynamodb.DescribeTimeToLiveOutput, err error) *DynamoDBPort_DescribeTimeToLive_Call {
	_c.Call.Return(describeTimeToLiveOutput, err)
	return _c
}

func (_c *DynamoDBPort_DescribeTimeToLive_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput) (*dynamodb.DescribeTimeToLiveOutput, error)) *DynamoDBPort_DescribeTimeToLive_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) GetItem(ctx context.Context, input *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput) *dynamodb.GetItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type DynamoDBPort_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.GetItemInput
func (_e *DynamoDBPort_Expecter) GetItem(ctx interface{}, input interface{}) *DynamoDBPort_GetItem_Call {
	return &DynamoDBPort_GetItem_Call{Call: _e.mock.On("GetItem", ctx, input)}
}

func (_c *DynamoDBPort_GetItem_Call) Run(run func(ctx context.Context, input *dynamodb.GetItemInput)) *DynamoDBPort_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.GetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.GetItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_GetItem_Call) Return(getItemOutput *dynamodb.GetItemOutput, err error) *DynamoDBPort_GetItem_Call {
	_c.Call.Return(getItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_GetItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.GetItemInput) (*dynamodb.GetItemOutput, error)) *DynamoDBPort_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) ListTables(ctx context.Context, input *dynamodb.ListTablesInput) (*dynamodb.ListTablesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 *dynamodb.ListTablesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput) (*dynamodb.ListTablesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput) *dynamodb.ListTablesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ListTablesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ListTablesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type DynamoDBPort_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.ListTablesInput
func (_e *DynamoDBPort_Expecter) ListTables(ctx interface{}, input interface{}) *DynamoDBPort_ListTables_Call {
	return &DynamoDBPort_ListTables_Call{Call: _e.mock.On("ListTables", ctx, input)}
}

func (_c *DynamoDBPort_ListTables_Call) Run(run func(ctx context.Context, input *dynamodb.ListTablesInput)) *DynamoDBPort_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ListTablesInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ListTablesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_ListTables_Call) Return(listTablesOutput *dynamodb.ListTablesOutput, err error) *DynamoDBPort_ListTables_Call {
	_c.Call.Return(listTablesOutput, err)
	return _c
}

func (_c *DynamoDBPort_ListTables_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.ListTablesInput) (*dynamodb.ListTablesOutput, error)) *DynamoDBPort_ListTables_Call {
	_c.Call.Return(run)
	return _c
}

// PutItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) PutItem(ctx context.Context, input *dynamodb.PutItemInput) (*dynamodb.PutItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type DynamoDBPort_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.PutItemInput
func (_e *DynamoDBPort_Expecter) PutItem(ctx interface{}, input interface{}) *DynamoDBPort_PutItem_Call {
	return &DynamoDBPort_PutItem_Call{Call: _e.mock.On("PutItem", ctx, input)}
}

func (_c *DynamoDBPort_PutItem_Call) Run(run func(ctx context.Context, input *dynamodb.PutItemInput)) *DynamoDBPort_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *DynamoDBPort_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_PutItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.PutItemInput) (*dynamodb.PutItemOutput, error)) *DynamoDBPort_PutItem_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) Query(ctx context.Context, input *dynamodb.QueryInput) (*dynamodb.QueryOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput) (*dynamodb.QueryOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput) *dynamodb.QueryOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DynamoDBPort_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.QueryInput
func (_e *DynamoDBPort_Expecter) Query(ctx interface{}, input interface{}) *DynamoDBPort_Query_Call {
	return &DynamoDBPort_Query_Call{Call: _e.mock.On("Query", ctx, input)}
}

func (_c *DynamoDBPort_Query_Call) Run(run func(ctx context.Context, input *dynamodb.QueryInput)) *DynamoDBPort_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.QueryInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.QueryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_Query_Call) Return(queryOutput *dynamodb.QueryOutput, err error) *DynamoDBPort_Query_Call {
	_c.Call.Return(queryOutput, err)
	return _c
}

func (_c *DynamoDBPort_Query_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.QueryInput) (*dynamodb.QueryOutput, error)) *DynamoDBPort_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) Scan(ctx context.Context, input *dynamodb.ScanInput) (*dynamodb.ScanOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *dynamodb.ScanOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput) (*dynamodb.ScanOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput) *dynamodb.ScanOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ScanOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ScanInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type DynamoDBPort_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.ScanInput
func (_e *DynamoDBPort_Expecter) Scan(ctx interface{}, input interface{}) *DynamoDBPort_Scan_Call {
	return &DynamoDBPort_Scan_Call{Call: _e.mock.On("Scan", ctx, input)}
}

func (_c *DynamoDBPort_Scan_Call) Run(run func(ctx context.Context, input *dynamodb.ScanInput)) *DynamoDBPort_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ScanInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ScanInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_Scan_Call) Return(scanOutput *dynamodb.ScanOutput, err error) *DynamoDBPort_Scan_Call {
	_c.Call.Return(scanOutput, err)
	return _c
}

func (_c *DynamoDBPort_Scan_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.ScanInput) (*dynamodb.ScanOutput, error)) *DynamoDBPort_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) UpdateItem(ctx context.Context, input *dynamodb.UpdateItemInput) (*dynamodb.UpdateItemOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *dynamodb.UpdateItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput) (*dynamodb.UpdateItemOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput) *dynamodb.UpdateItemOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateItemInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type DynamoDBPort_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateItemInput
func (_e *DynamoDBPort_Expecter) UpdateItem(ctx interface{}, input interface{}) *DynamoDBPort_UpdateItem_Call {
	return &DynamoDBPort_UpdateItem_Call{Call: _e.mock.On("UpdateItem", ctx, input)}
}

func (_c *DynamoDBPort_UpdateItem_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateItemInput)) *DynamoDBPort_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateItemInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_UpdateItem_Call) Return(updateItemOutput *dynamodb.UpdateItemOutput, err error) *DynamoDBPort_UpdateItem_Call {
	_c.Call.Return(updateItemOutput, err)
	return _c
}

func (_c *DynamoDBPort_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateItemInput) (*dynamodb.UpdateItemOutput, error)) *DynamoDBPort_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTable provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) UpdateTable(ctx context.Context, input *dynamodb.UpdateTableInput) (*dynamodb.UpdateTableOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTable")
	}

	var r0 *dynamodb.UpdateTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTableInput) (*dynamodb.UpdateTableOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTableInput) *dynamodb.UpdateTableOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateTableInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_UpdateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTable'
type DynamoDBPort_UpdateTable_Call struct {
	*mock.Call
}

// UpdateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateTableInput
func (_e *DynamoDBPort_Expecter) UpdateTable(ctx interface{}, input interface{}) *DynamoDBPort_UpdateTable_Call {
	return &DynamoDBPort_UpdateTable_Call{Call: _e.mock.On("UpdateTable", ctx, input)}
}

func (_c *DynamoDBPort_UpdateTable_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateTableInput)) *DynamoDBPort_UpdateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateTableInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_UpdateTable_Call) Return(updateTableOutput *dynamodb.UpdateTableOutput, err error) *DynamoDBPort_UpdateTable_Call {
	_c.Call.Return(updateTableOutput, err)
	return _c
}

func (_c *DynamoDBPort_UpdateTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateTableInput) (*dynamodb.UpdateTableOutput, error)) *DynamoDBPort_UpdateTable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTimeToLive provides a mock function for the type DynamoDBPort
func (_mock *DynamoDBPort) UpdateTimeToLive(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput) (*dynamodb.UpdateTimeToLiveOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimeToLive")
	}

	var r0 *dynamodb.UpdateTimeToLiveOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTimeToLiveInput) (*dynamodb.UpdateTimeToLiveOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTimeToLiveInput) *dynamodb.UpdateTimeToLiveOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateTimeToLiveOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateTimeToLiveInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBPort_UpdateTimeToLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTimeToLive'
type DynamoDBPort_UpdateTimeToLive_Call struct {
	*mock.Call
}

// UpdateTimeToLive is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateTimeToLiveInput
func (_e *DynamoDBPort_Expecter) UpdateTimeToLive(ctx interface{}, input interface{}) *DynamoDBPort_UpdateTimeToLive_Call {
	return &DynamoDBPort_UpdateTimeToLive_Call{Call: _e.mock.On("UpdateTimeToLive", ctx, input)}
}

func (_c *DynamoDBPort_UpdateTimeToLive_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput)) *DynamoDBPort_UpdateTimeToLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateTimeToLiveInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateTimeToLiveInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *DynamoDBPort_UpdateTimeToLive_Call) Return(updateTimeToLiveOutput *dynamodb.UpdateTimeToLiveOutput, err error) *DynamoDBPort_UpdateTimeToLive_Call {
	_c.Call.Return(updateTimeToLiveOutput, err)
	return _c
}

func (_c *DynamoDBPort_UpdateTimeToLive_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput) (*dynamodb.UpdateTimeToLiveOutput, error)) *DynamoDBPort_UpdateTimeToLive_Call {
	_c.Call.Return(run)
	return _c
}
