// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb"
	mock "github.com/stretchr/testify/mock"
)

// NewDynamoDBClientPort creates a new instance of DynamoDBClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDynamoDBClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *DynamoDBClientPort {
	mock := &DynamoDBClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// DynamoDBClientPort is an autogenerated mock type for the DynamoDBClientPort type
type DynamoDBClientPort struct {
	mock.Mock
}

type DynamoDBClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *DynamoDBClientPort) EXPECT() *DynamoDBClientPort_Expecter {
	return &DynamoDBClientPort_Expecter{mock: &_m.Mock}
}

// BatchGetItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) BatchGetItem(ctx context.Context, input *dynamodb.BatchGetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.BatchGetItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchGetItem")
	}

	var r0 *dynamodb.BatchGetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchGetItemInput, ...func(*dynamodb.Options)) (*dynamodb.BatchGetItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchGetItemInput, ...func(*dynamodb.Options)) *dynamodb.BatchGetItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchGetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.BatchGetItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_BatchGetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchGetItem'
type DynamoDBClientPort_BatchGetItem_Call struct {
	*mock.Call
}

// BatchGetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.BatchGetItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) BatchGetItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_BatchGetItem_Call {
	return &DynamoDBClientPort_BatchGetItem_Call{Call: _e.mock.On("BatchGetItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_BatchGetItem_Call) Run(run func(ctx context.Context, input *dynamodb.BatchGetItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_BatchGetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.BatchGetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.BatchGetItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_BatchGetItem_Call) Return(batchGetItemOutput *dynamodb.BatchGetItemOutput, err error) *DynamoDBClientPort_BatchGetItem_Call {
	_c.Call.Return(batchGetItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_BatchGetItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.BatchGetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.BatchGetItemOutput, error)) *DynamoDBClientPort_BatchGetItem_Call {
	_c.Call.Return(run)
	return _c
}

// BatchWriteItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) BatchWriteItem(ctx context.Context, input *dynamodb.BatchWriteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for BatchWriteItem")
	}

	var r0 *dynamodb.BatchWriteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) *dynamodb.BatchWriteItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.BatchWriteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.BatchWriteItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_BatchWriteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchWriteItem'
type DynamoDBClientPort_BatchWriteItem_Call struct {
	*mock.Call
}

// BatchWriteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.BatchWriteItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) BatchWriteItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_BatchWriteItem_Call {
	return &DynamoDBClientPort_BatchWriteItem_Call{Call: _e.mock.On("BatchWriteItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_BatchWriteItem_Call) Run(run func(ctx context.Context, input *dynamodb.BatchWriteItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_BatchWriteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.BatchWriteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.BatchWriteItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_BatchWriteItem_Call) Return(batchWriteItemOutput *dynamodb.BatchWriteItemOutput, err error) *DynamoDBClientPort_BatchWriteItem_Call {
	_c.Call.Return(batchWriteItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_BatchWriteItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.BatchWriteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.BatchWriteItemOutput, error)) *DynamoDBClientPort_BatchWriteItem_Call {
	_c.Call.Return(run)
	return _c
}

// CreateTable provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) CreateTable(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateTable")
	}

	var r0 *dynamodb.CreateTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) *dynamodb.CreateTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.CreateTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.CreateTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_CreateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateTable'
type DynamoDBClientPort_CreateTable_Call struct {
	*mock.Call
}

// CreateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.CreateTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) CreateTable(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_CreateTable_Call {
	return &DynamoDBClientPort_CreateTable_Call{Call: _e.mock.On("CreateTable",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_CreateTable_Call) Run(run func(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_CreateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.CreateTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.CreateTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_CreateTable_Call) Return(createTableOutput *dynamodb.CreateTableOutput, err error) *DynamoDBClientPort_CreateTable_Call {
	_c.Call.Return(createTableOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_CreateTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.CreateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.CreateTableOutput, error)) *DynamoDBClientPort_CreateTable_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) DeleteItem(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteItem")
	}

	var r0 *dynamodb.DeleteItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) *dynamodb.DeleteItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_DeleteItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteItem'
type DynamoDBClientPort_DeleteItem_Call struct {
	*mock.Call
}

// DeleteItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DeleteItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) DeleteItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_DeleteItem_Call {
	return &DynamoDBClientPort_DeleteItem_Call{Call: _e.mock.On("DeleteItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_DeleteItem_Call) Run(run func(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_DeleteItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_DeleteItem_Call) Return(deleteItemOutput *dynamodb.DeleteItemOutput, err error) *DynamoDBClientPort_DeleteItem_Call {
	_c.Call.Return(deleteItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_DeleteItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DeleteItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteItemOutput, error)) *DynamoDBClientPort_DeleteItem_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteTable provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) DeleteTable(ctx context.Context, input *dynamodb.DeleteTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteTable")
	}

	var r0 *dynamodb.DeleteTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteTableInput, ...func(*dynamodb.Options)) (*dynamodb.DeleteTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DeleteTableInput, ...func(*dynamodb.Options)) *dynamodb.DeleteTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DeleteTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DeleteTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_DeleteTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteTable'
type DynamoDBClientPort_DeleteTable_Call struct {
	*mock.Call
}

// DeleteTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DeleteTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) DeleteTable(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_DeleteTable_Call {
	return &DynamoDBClientPort_DeleteTable_Call{Call: _e.mock.On("DeleteTable",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_DeleteTable_Call) Run(run func(ctx context.Context, input *dynamodb.DeleteTableInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_DeleteTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DeleteTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DeleteTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_DeleteTable_Call) Return(deleteTableOutput *dynamodb.DeleteTableOutput, err error) *DynamoDBClientPort_DeleteTable_Call {
	_c.Call.Return(deleteTableOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_DeleteTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DeleteTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DeleteTableOutput, error)) *DynamoDBClientPort_DeleteTable_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTable provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) DescribeTable(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeTable")
	}

	var r0 *dynamodb.DescribeTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) *dynamodb.DescribeTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_DescribeTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTable'
type DynamoDBClientPort_DescribeTable_Call struct {
	*mock.Call
}

// DescribeTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DescribeTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) DescribeTable(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_DescribeTable_Call {
	return &DynamoDBClientPort_DescribeTable_Call{Call: _e.mock.On("DescribeTable",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_DescribeTable_Call) Run(run func(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_DescribeTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_DescribeTable_Call) Return(describeTableOutput *dynamodb.DescribeTableOutput, err error) *DynamoDBClientPort_DescribeTable_Call {
	_c.Call.Return(describeTableOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_DescribeTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DescribeTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTableOutput, error)) *DynamoDBClientPort_DescribeTable_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeTimeToLive provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) DescribeTimeToLive(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTimeToLiveOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeTimeToLive")
	}

	var r0 *dynamodb.DescribeTimeToLiveOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTimeToLiveInput, ...func(*dynamodb.Options)) (*dynamodb.DescribeTimeToLiveOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.DescribeTimeToLiveInput, ...func(*dynamodb.Options)) *dynamodb.DescribeTimeToLiveOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.DescribeTimeToLiveOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.DescribeTimeToLiveInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_DescribeTimeToLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeTimeToLive'
type DynamoDBClientPort_DescribeTimeToLive_Call struct {
	*mock.Call
}

// DescribeTimeToLive is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.DescribeTimeToLiveInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) DescribeTimeToLive(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_DescribeTimeToLive_Call {
	return &DynamoDBClientPort_DescribeTimeToLive_Call{Call: _e.mock.On("DescribeTimeToLive",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_DescribeTimeToLive_Call) Run(run func(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_DescribeTimeToLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.DescribeTimeToLiveInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.DescribeTimeToLiveInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_DescribeTimeToLive_Call) Return(describeTimeToLiveOutput *dynamodb.DescribeTimeToLiveOutput, err error) *DynamoDBClientPort_DescribeTimeToLive_Call {
	_c.Call.Return(describeTimeToLiveOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_DescribeTimeToLive_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.DescribeTimeToLiveInput, opts ...func(*dynamodb.Options)) (*dynamodb.DescribeTimeToLiveOutput, error)) *DynamoDBClientPort_DescribeTimeToLive_Call {
	_c.Call.Return(run)
	return _c
}

// GetItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) GetItem(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetItem")
	}

	var r0 *dynamodb.GetItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) *dynamodb.GetItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.GetItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.GetItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_GetItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetItem'
type DynamoDBClientPort_GetItem_Call struct {
	*mock.Call
}

// GetItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.GetItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) GetItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_GetItem_Call {
	return &DynamoDBClientPort_GetItem_Call{Call: _e.mock.On("GetItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_GetItem_Call) Run(run func(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_GetItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.GetItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.GetItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_GetItem_Call) Return(getItemOutput *dynamodb.GetItemOutput, err error) *DynamoDBClientPort_GetItem_Call {
	_c.Call.Return(getItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_GetItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.GetItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.GetItemOutput, error)) *DynamoDBClientPort_GetItem_Call {
	_c.Call.Return(run)
	return _c
}

// ListTables provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) ListTables(ctx context.Context, input *dynamodb.ListTablesInput, opts ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListTables")
	}

	var r0 *dynamodb.ListTablesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) *dynamodb.ListTablesOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ListTablesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ListTablesInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_ListTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTables'
type DynamoDBClientPort_ListTables_Call struct {
	*mock.Call
}

// ListTables is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.ListTablesInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) ListTables(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_ListTables_Call {
	return &DynamoDBClientPort_ListTables_Call{Call: _e.mock.On("ListTables",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_ListTables_Call) Run(run func(ctx context.Context, input *dynamodb.ListTablesInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_ListTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ListTablesInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ListTablesInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_ListTables_Call) Return(listTablesOutput *dynamodb.ListTablesOutput, err error) *DynamoDBClientPort_ListTables_Call {
	_c.Call.Return(listTablesOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_ListTables_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.ListTablesInput, opts ...func(*dynamodb.Options)) (*dynamodb.ListTablesOutput, error)) *DynamoDBClientPort_ListTables_Call {
	_c.Call.Return(run)
	return _c
}

// PutItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) PutItem(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutItem")
	}

	var r0 *dynamodb.PutItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) *dynamodb.PutItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.PutItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.PutItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_PutItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutItem'
type DynamoDBClientPort_PutItem_Call struct {
	*mock.Call
}

// PutItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.PutItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) PutItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_PutItem_Call {
	return &DynamoDBClientPort_PutItem_Call{Call: _e.mock.On("PutItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_PutItem_Call) Run(run func(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_PutItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.PutItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.PutItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_PutItem_Call) Return(putItemOutput *dynamodb.PutItemOutput, err error) *DynamoDBClientPort_PutItem_Call {
	_c.Call.Return(putItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_PutItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.PutItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.PutItemOutput, error)) *DynamoDBClientPort_PutItem_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) Query(ctx context.Context, input *dynamodb.QueryInput, opts ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 *dynamodb.QueryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) *dynamodb.QueryOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.QueryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.QueryInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type DynamoDBClientPort_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.QueryInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) Query(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_Query_Call {
	return &DynamoDBClientPort_Query_Call{Call: _e.mock.On("Query",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_Query_Call) Run(run func(ctx context.Context, input *dynamodb.QueryInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.QueryInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.QueryInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_Query_Call) Return(queryOutput *dynamodb.QueryOutput, err error) *DynamoDBClientPort_Query_Call {
	_c.Call.Return(queryOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_Query_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.QueryInput, opts ...func(*dynamodb.Options)) (*dynamodb.QueryOutput, error)) *DynamoDBClientPort_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Scan provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) Scan(ctx context.Context, input *dynamodb.ScanInput, opts ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 *dynamodb.ScanOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) *dynamodb.ScanOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.ScanOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.ScanInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_Scan_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scan'
type DynamoDBClientPort_Scan_Call struct {
	*mock.Call
}

// Scan is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.ScanInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) Scan(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_Scan_Call {
	return &DynamoDBClientPort_Scan_Call{Call: _e.mock.On("Scan",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_Scan_Call) Run(run func(ctx context.Context, input *dynamodb.ScanInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_Scan_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.ScanInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.ScanInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_Scan_Call) Return(scanOutput *dynamodb.ScanOutput, err error) *DynamoDBClientPort_Scan_Call {
	_c.Call.Return(scanOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_Scan_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.ScanInput, opts ...func(*dynamodb.Options)) (*dynamodb.ScanOutput, error)) *DynamoDBClientPort_Scan_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateItem provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) UpdateItem(ctx context.Context, input *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateItem")
	}

	var r0 *dynamodb.UpdateItemOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) *dynamodb.UpdateItemOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateItemOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateItemInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_UpdateItem_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateItem'
type DynamoDBClientPort_UpdateItem_Call struct {
	*mock.Call
}

// UpdateItem is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateItemInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) UpdateItem(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_UpdateItem_Call {
	return &DynamoDBClientPort_UpdateItem_Call{Call: _e.mock.On("UpdateItem",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_UpdateItem_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_UpdateItem_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateItemInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateItemInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_UpdateItem_Call) Return(updateItemOutput *dynamodb.UpdateItemOutput, err error) *DynamoDBClientPort_UpdateItem_Call {
	_c.Call.Return(updateItemOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_UpdateItem_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateItemInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateItemOutput, error)) *DynamoDBClientPort_UpdateItem_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTable provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) UpdateTable(ctx context.Context, input *dynamodb.UpdateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateTableOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTable")
	}

	var r0 *dynamodb.UpdateTableOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTableInput, ...func(*dynamodb.Options)) (*dynamodb.UpdateTableOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTableInput, ...func(*dynamodb.Options)) *dynamodb.UpdateTableOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateTableOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateTableInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_UpdateTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTable'
type DynamoDBClientPort_UpdateTable_Call struct {
	*mock.Call
}

// UpdateTable is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateTableInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) UpdateTable(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_UpdateTable_Call {
	return &DynamoDBClientPort_UpdateTable_Call{Call: _e.mock.On("UpdateTable",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_UpdateTable_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateTableInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_UpdateTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateTableInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateTableInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_UpdateTable_Call) Return(updateTableOutput *dynamodb.UpdateTableOutput, err error) *DynamoDBClientPort_UpdateTable_Call {
	_c.Call.Return(updateTableOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_UpdateTable_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateTableInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateTableOutput, error)) *DynamoDBClientPort_UpdateTable_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateTimeToLive provides a mock function for the type DynamoDBClientPort
func (_mock *DynamoDBClientPort) UpdateTimeToLive(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateTimeToLiveOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateTimeToLive")
	}

	var r0 *dynamodb.UpdateTimeToLiveOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTimeToLiveInput, ...func(*dynamodb.Options)) (*dynamodb.UpdateTimeToLiveOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *dynamodb.UpdateTimeToLiveInput, ...func(*dynamodb.Options)) *dynamodb.UpdateTimeToLiveOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dynamodb.UpdateTimeToLiveOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *dynamodb.UpdateTimeToLiveInput, ...func(*dynamodb.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// DynamoDBClientPort_UpdateTimeToLive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateTimeToLive'
type DynamoDBClientPort_UpdateTimeToLive_Call struct {
	*mock.Call
}

// UpdateTimeToLive is a helper method to define mock.On call
//   - ctx context.Context
//   - input *dynamodb.UpdateTimeToLiveInput
//   - opts ...func(*dynamodb.Options)
func (_e *DynamoDBClientPort_Expecter) UpdateTimeToLive(ctx interface{}, input interface{}, opts ...interface{}) *DynamoDBClientPort_UpdateTimeToLive_Call {
	return &DynamoDBClientPort_UpdateTimeToLive_Call{Call: _e.mock.On("UpdateTimeToLive",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *DynamoDBClientPort_UpdateTimeToLive_Call) Run(run func(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput, opts ...func(*dynamodb.Options))) *DynamoDBClientPort_UpdateTimeToLive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *dynamodb.UpdateTimeToLiveInput
		if args[1] != nil {
			arg1 = args[1].(*dynamodb.UpdateTimeToLiveInput)
		}
		var arg2 []func(*dynamodb.Options)
		var variadicArgs []func(*dynamodb.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*dynamodb.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *DynamoDBClientPort_UpdateTimeToLive_Call) Return(updateTimeToLiveOutput *dynamodb.UpdateTimeToLiveOutput, err error) *DynamoDBClientPort_UpdateTimeToLive_Call {
	_c.Call.Return(updateTimeToLiveOutput, err)
	return _c
}

func (_c *DynamoDBClientPort_UpdateTimeToLive_Call) RunAndReturn(run func(ctx context.Context, input *dynamodb.UpdateTimeToLiveInput, opts ...func(*dynamodb.Options)) (*dynamodb.UpdateTimeToLiveOutput, error)) *DynamoDBClientPort_UpdateTimeToLive_Call {
	_c.Call.Return(run)
	return _c
}
