// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/kinesis"
	mock "github.com/stretchr/testify/mock"
)

// NewKinesisPort creates a new instance of KinesisPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewKinesisPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *KinesisPort {
	mock := &KinesisPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// KinesisPort is an autogenerated mock type for the KinesisPort type
type KinesisPort struct {
	mock.Mock
}

type KinesisPort_Expecter struct {
	mock *mock.Mock
}

func (_m *KinesisPort) EXPECT() *KinesisPort_Expecter {
	return &KinesisPort_Expecter{mock: &_m.Mock}
}

// CreateStream provides a mock function for the type KinesisPort
func (_mock *KinesisPort) CreateStream(ctx context.Context, input *kinesis.CreateStreamInput) (*kinesis.CreateStreamOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateStream")
	}

	var r0 *kinesis.CreateStreamOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.CreateStreamInput) (*kinesis.CreateStreamOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.CreateStreamInput) *kinesis.CreateStreamOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.CreateStreamOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.CreateStreamInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_CreateStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateStream'
type KinesisPort_CreateStream_Call struct {
	*mock.Call
}

// CreateStream is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.CreateStreamInput
func (_e *KinesisPort_Expecter) CreateStream(ctx interface{}, input interface{}) *KinesisPort_CreateStream_Call {
	return &KinesisPort_CreateStream_Call{Call: _e.mock.On("CreateStream", ctx, input)}
}

func (_c *KinesisPort_CreateStream_Call) Run(run func(ctx context.Context, input *kinesis.CreateStreamInput)) *KinesisPort_CreateStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.CreateStreamInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.CreateStreamInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_CreateStream_Call) Return(createStreamOutput *kinesis.CreateStreamOutput, err error) *KinesisPort_CreateStream_Call {
	_c.Call.Return(createStreamOutput, err)
	return _c
}

func (_c *KinesisPort_CreateStream_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.CreateStreamInput) (*kinesis.CreateStreamOutput, error)) *KinesisPort_CreateStream_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteStream provides a mock function for the type KinesisPort
func (_mock *KinesisPort) DeleteStream(ctx context.Context, input *kinesis.DeleteStreamInput) (*kinesis.DeleteStreamOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteStream")
	}

	var r0 *kinesis.DeleteStreamOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DeleteStreamInput) (*kinesis.DeleteStreamOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DeleteStreamInput) *kinesis.DeleteStreamOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.DeleteStreamOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.DeleteStreamInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_DeleteStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteStream'
type KinesisPort_DeleteStream_Call struct {
	*mock.Call
}

// DeleteStream is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.DeleteStreamInput
func (_e *KinesisPort_Expecter) DeleteStream(ctx interface{}, input interface{}) *KinesisPort_DeleteStream_Call {
	return &KinesisPort_DeleteStream_Call{Call: _e.mock.On("DeleteStream", ctx, input)}
}

func (_c *KinesisPort_DeleteStream_Call) Run(run func(ctx context.Context, input *kinesis.DeleteStreamInput)) *KinesisPort_DeleteStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.DeleteStreamInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.DeleteStreamInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_DeleteStream_Call) Return(deleteStreamOutput *kinesis.DeleteStreamOutput, err error) *KinesisPort_DeleteStream_Call {
	_c.Call.Return(deleteStreamOutput, err)
	return _c
}

func (_c *KinesisPort_DeleteStream_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.DeleteStreamInput) (*kinesis.DeleteStreamOutput, error)) *KinesisPort_DeleteStream_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeStream provides a mock function for the type KinesisPort
func (_mock *KinesisPort) DescribeStream(ctx context.Context, input *kinesis.DescribeStreamInput) (*kinesis.DescribeStreamOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeStream")
	}

	var r0 *kinesis.DescribeStreamOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DescribeStreamInput) (*kinesis.DescribeStreamOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DescribeStreamInput) *kinesis.DescribeStreamOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.DescribeStreamOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.DescribeStreamInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_DescribeStream_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeStream'
type KinesisPort_DescribeStream_Call struct {
	*mock.Call
}

// DescribeStream is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.DescribeStreamInput
func (_e *KinesisPort_Expecter) DescribeStream(ctx interface{}, input interface{}) *KinesisPort_DescribeStream_Call {
	return &KinesisPort_DescribeStream_Call{Call: _e.mock.On("DescribeStream", ctx, input)}
}

func (_c *KinesisPort_DescribeStream_Call) Run(run func(ctx context.Context, input *kinesis.DescribeStreamInput)) *KinesisPort_DescribeStream_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.DescribeStreamInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.DescribeStreamInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_DescribeStream_Call) Return(describeStreamOutput *kinesis.DescribeStreamOutput, err error) *KinesisPort_DescribeStream_Call {
	_c.Call.Return(describeStreamOutput, err)
	return _c
}

func (_c *KinesisPort_DescribeStream_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.DescribeStreamInput) (*kinesis.DescribeStreamOutput, error)) *KinesisPort_DescribeStream_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeStreamSummary provides a mock function for the type KinesisPort
func (_mock *KinesisPort) DescribeStreamSummary(ctx context.Context, input *kinesis.DescribeStreamSummaryInput) (*kinesis.DescribeStreamSummaryOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeStreamSummary")
	}

	var r0 *kinesis.DescribeStreamSummaryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DescribeStreamSummaryInput) (*kinesis.DescribeStreamSummaryOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DescribeStreamSummaryInput) *kinesis.DescribeStreamSummaryOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.DescribeStreamSummaryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.DescribeStreamSummaryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_DescribeStreamSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeStreamSummary'
type KinesisPort_DescribeStreamSummary_Call struct {
	*mock.Call
}

// DescribeStreamSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.DescribeStreamSummaryInput
func (_e *KinesisPort_Expecter) DescribeStreamSummary(ctx interface{}, input interface{}) *KinesisPort_DescribeStreamSummary_Call {
	return &KinesisPort_DescribeStreamSummary_Call{Call: _e.mock.On("DescribeStreamSummary", ctx, input)}
}

func (_c *KinesisPort_DescribeStreamSummary_Call) Run(run func(ctx context.Context, input *kinesis.DescribeStreamSummaryInput)) *KinesisPort_DescribeStreamSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.DescribeStreamSummaryInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.DescribeStreamSummaryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_DescribeStreamSummary_Call) Return(describeStreamSummaryOutput *kinesis.DescribeStreamSummaryOutput, err error) *KinesisPort_DescribeStreamSummary_Call {
	_c.Call.Return(describeStreamSummaryOutput, err)
	return _c
}

func (_c *KinesisPort_DescribeStreamSummary_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.DescribeStreamSummaryInput) (*kinesis.DescribeStreamSummaryOutput, error)) *KinesisPort_DescribeStreamSummary_Call {
	_c.Call.Return(run)
	return _c
}

// DisableEnhancedMonitoring provides a mock function for the type KinesisPort
func (_mock *KinesisPort) DisableEnhancedMonitoring(ctx context.Context, input *kinesis.DisableEnhancedMonitoringInput) (*kinesis.DisableEnhancedMonitoringOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DisableEnhancedMonitoring")
	}

	var r0 *kinesis.DisableEnhancedMonitoringOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DisableEnhancedMonitoringInput) (*kinesis.DisableEnhancedMonitoringOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.DisableEnhancedMonitoringInput) *kinesis.DisableEnhancedMonitoringOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.DisableEnhancedMonitoringOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.DisableEnhancedMonitoringInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_DisableEnhancedMonitoring_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisableEnhancedMonitoring'
type KinesisPort_DisableEnhancedMonitoring_Call struct {
	*mock.Call
}

// DisableEnhancedMonitoring is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.DisableEnhancedMonitoringInput
func (_e *KinesisPort_Expecter) DisableEnhancedMonitoring(ctx interface{}, input interface{}) *KinesisPort_DisableEnhancedMonitoring_Call {
	return &KinesisPort_DisableEnhancedMonitoring_Call{Call: _e.mock.On("DisableEnhancedMonitoring", ctx, input)}
}

func (_c *KinesisPort_DisableEnhancedMonitoring_Call) Run(run func(ctx context.Context, input *kinesis.DisableEnhancedMonitoringInput)) *KinesisPort_DisableEnhancedMonitoring_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.DisableEnhancedMonitoringInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.DisableEnhancedMonitoringInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_DisableEnhancedMonitoring_Call) Return(disableEnhancedMonitoringOutput *kinesis.DisableEnhancedMonitoringOutput, err error) *KinesisPort_DisableEnhancedMonitoring_Call {
	_c.Call.Return(disableEnhancedMonitoringOutput, err)
	return _c
}

func (_c *KinesisPort_DisableEnhancedMonitoring_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.DisableEnhancedMonitoringInput) (*kinesis.DisableEnhancedMonitoringOutput, error)) *KinesisPort_DisableEnhancedMonitoring_Call {
	_c.Call.Return(run)
	return _c
}

// EnableEnhancedMonitoring provides a mock function for the type KinesisPort
func (_mock *KinesisPort) EnableEnhancedMonitoring(ctx context.Context, input *kinesis.EnableEnhancedMonitoringInput) (*kinesis.EnableEnhancedMonitoringOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for EnableEnhancedMonitoring")
	}

	var r0 *kinesis.EnableEnhancedMonitoringOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.EnableEnhancedMonitoringInput) (*kinesis.EnableEnhancedMonitoringOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.EnableEnhancedMonitoringInput) *kinesis.EnableEnhancedMonitoringOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.EnableEnhancedMonitoringOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.EnableEnhancedMonitoringInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_EnableEnhancedMonitoring_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnableEnhancedMonitoring'
type KinesisPort_EnableEnhancedMonitoring_Call struct {
	*mock.Call
}

// EnableEnhancedMonitoring is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.EnableEnhancedMonitoringInput
func (_e *KinesisPort_Expecter) EnableEnhancedMonitoring(ctx interface{}, input interface{}) *KinesisPort_EnableEnhancedMonitoring_Call {
	return &KinesisPort_EnableEnhancedMonitoring_Call{Call: _e.mock.On("EnableEnhancedMonitoring", ctx, input)}
}

func (_c *KinesisPort_EnableEnhancedMonitoring_Call) Run(run func(ctx context.Context, input *kinesis.EnableEnhancedMonitoringInput)) *KinesisPort_EnableEnhancedMonitoring_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.EnableEnhancedMonitoringInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.EnableEnhancedMonitoringInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_EnableEnhancedMonitoring_Call) Return(enableEnhancedMonitoringOutput *kinesis.EnableEnhancedMonitoringOutput, err error) *KinesisPort_EnableEnhancedMonitoring_Call {
	_c.Call.Return(enableEnhancedMonitoringOutput, err)
	return _c
}

func (_c *KinesisPort_EnableEnhancedMonitoring_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.EnableEnhancedMonitoringInput) (*kinesis.EnableEnhancedMonitoringOutput, error)) *KinesisPort_EnableEnhancedMonitoring_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecords provides a mock function for the type KinesisPort
func (_mock *KinesisPort) GetRecords(ctx context.Context, input *kinesis.GetRecordsInput) (*kinesis.GetRecordsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRecords")
	}

	var r0 *kinesis.GetRecordsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.GetRecordsInput) (*kinesis.GetRecordsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.GetRecordsInput) *kinesis.GetRecordsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.GetRecordsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.GetRecordsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_GetRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecords'
type KinesisPort_GetRecords_Call struct {
	*mock.Call
}

// GetRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.GetRecordsInput
func (_e *KinesisPort_Expecter) GetRecords(ctx interface{}, input interface{}) *KinesisPort_GetRecords_Call {
	return &KinesisPort_GetRecords_Call{Call: _e.mock.On("GetRecords", ctx, input)}
}

func (_c *KinesisPort_GetRecords_Call) Run(run func(ctx context.Context, input *kinesis.GetRecordsInput)) *KinesisPort_GetRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.GetRecordsInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.GetRecordsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_GetRecords_Call) Return(getRecordsOutput *kinesis.GetRecordsOutput, err error) *KinesisPort_GetRecords_Call {
	_c.Call.Return(getRecordsOutput, err)
	return _c
}

func (_c *KinesisPort_GetRecords_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.GetRecordsInput) (*kinesis.GetRecordsOutput, error)) *KinesisPort_GetRecords_Call {
	_c.Call.Return(run)
	return _c
}

// GetShardIterator provides a mock function for the type KinesisPort
func (_mock *KinesisPort) GetShardIterator(ctx context.Context, input *kinesis.GetShardIteratorInput) (*kinesis.GetShardIteratorOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetShardIterator")
	}

	var r0 *kinesis.GetShardIteratorOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.GetShardIteratorInput) (*kinesis.GetShardIteratorOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.GetShardIteratorInput) *kinesis.GetShardIteratorOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.GetShardIteratorOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.GetShardIteratorInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_GetShardIterator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShardIterator'
type KinesisPort_GetShardIterator_Call struct {
	*mock.Call
}

// GetShardIterator is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.GetShardIteratorInput
func (_e *KinesisPort_Expecter) GetShardIterator(ctx interface{}, input interface{}) *KinesisPort_GetShardIterator_Call {
	return &KinesisPort_GetShardIterator_Call{Call: _e.mock.On("GetShardIterator", ctx, input)}
}

func (_c *KinesisPort_GetShardIterator_Call) Run(run func(ctx context.Context, input *kinesis.GetShardIteratorInput)) *KinesisPort_GetShardIterator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.GetShardIteratorInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.GetShardIteratorInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_GetShardIterator_Call) Return(getShardIteratorOutput *kinesis.GetShardIteratorOutput, err error) *KinesisPort_GetShardIterator_Call {
	_c.Call.Return(getShardIteratorOutput, err)
	return _c
}

func (_c *KinesisPort_GetShardIterator_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.GetShardIteratorInput) (*kinesis.GetShardIteratorOutput, error)) *KinesisPort_GetShardIterator_Call {
	_c.Call.Return(run)
	return _c
}

// ListShards provides a mock function for the type KinesisPort
func (_mock *KinesisPort) ListShards(ctx context.Context, input *kinesis.ListShardsInput) (*kinesis.ListShardsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListShards")
	}

	var r0 *kinesis.ListShardsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.ListShardsInput) (*kinesis.ListShardsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.ListShardsInput) *kinesis.ListShardsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.ListShardsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.ListShardsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_ListShards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListShards'
type KinesisPort_ListShards_Call struct {
	*mock.Call
}

// ListShards is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.ListShardsInput
func (_e *KinesisPort_Expecter) ListShards(ctx interface{}, input interface{}) *KinesisPort_ListShards_Call {
	return &KinesisPort_ListShards_Call{Call: _e.mock.On("ListShards", ctx, input)}
}

func (_c *KinesisPort_ListShards_Call) Run(run func(ctx context.Context, input *kinesis.ListShardsInput)) *KinesisPort_ListShards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.ListShardsInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.ListShardsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_ListShards_Call) Return(listShardsOutput *kinesis.ListShardsOutput, err error) *KinesisPort_ListShards_Call {
	_c.Call.Return(listShardsOutput, err)
	return _c
}

func (_c *KinesisPort_ListShards_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.ListShardsInput) (*kinesis.ListShardsOutput, error)) *KinesisPort_ListShards_Call {
	_c.Call.Return(run)
	return _c
}

// ListStreams provides a mock function for the type KinesisPort
func (_mock *KinesisPort) ListStreams(ctx context.Context, input *kinesis.ListStreamsInput) (*kinesis.ListStreamsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListStreams")
	}

	var r0 *kinesis.ListStreamsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.ListStreamsInput) (*kinesis.ListStreamsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.ListStreamsInput) *kinesis.ListStreamsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.ListStreamsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.ListStreamsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_ListStreams_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStreams'
type KinesisPort_ListStreams_Call struct {
	*mock.Call
}

// ListStreams is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.ListStreamsInput
func (_e *KinesisPort_Expecter) ListStreams(ctx interface{}, input interface{}) *KinesisPort_ListStreams_Call {
	return &KinesisPort_ListStreams_Call{Call: _e.mock.On("ListStreams", ctx, input)}
}

func (_c *KinesisPort_ListStreams_Call) Run(run func(ctx context.Context, input *kinesis.ListStreamsInput)) *KinesisPort_ListStreams_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.ListStreamsInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.ListStreamsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_ListStreams_Call) Return(listStreamsOutput *kinesis.ListStreamsOutput, err error) *KinesisPort_ListStreams_Call {
	_c.Call.Return(listStreamsOutput, err)
	return _c
}

func (_c *KinesisPort_ListStreams_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.ListStreamsInput) (*kinesis.ListStreamsOutput, error)) *KinesisPort_ListStreams_Call {
	_c.Call.Return(run)
	return _c
}

// MergeShards provides a mock function for the type KinesisPort
func (_mock *KinesisPort) MergeShards(ctx context.Context, input *kinesis.MergeShardsInput) (*kinesis.MergeShardsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for MergeShards")
	}

	var r0 *kinesis.MergeShardsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.MergeShardsInput) (*kinesis.MergeShardsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.MergeShardsInput) *kinesis.MergeShardsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.MergeShardsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.MergeShardsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_MergeShards_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeShards'
type KinesisPort_MergeShards_Call struct {
	*mock.Call
}

// MergeShards is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.MergeShardsInput
func (_e *KinesisPort_Expecter) MergeShards(ctx interface{}, input interface{}) *KinesisPort_MergeShards_Call {
	return &KinesisPort_MergeShards_Call{Call: _e.mock.On("MergeShards", ctx, input)}
}

func (_c *KinesisPort_MergeShards_Call) Run(run func(ctx context.Context, input *kinesis.MergeShardsInput)) *KinesisPort_MergeShards_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.MergeShardsInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.MergeShardsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_MergeShards_Call) Return(mergeShardsOutput *kinesis.MergeShardsOutput, err error) *KinesisPort_MergeShards_Call {
	_c.Call.Return(mergeShardsOutput, err)
	return _c
}

func (_c *KinesisPort_MergeShards_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.MergeShardsInput) (*kinesis.MergeShardsOutput, error)) *KinesisPort_MergeShards_Call {
	_c.Call.Return(run)
	return _c
}

// PutRecord provides a mock function for the type KinesisPort
func (_mock *KinesisPort) PutRecord(ctx context.Context, input *kinesis.PutRecordInput) (*kinesis.PutRecordOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutRecord")
	}

	var r0 *kinesis.PutRecordOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.PutRecordInput) (*kinesis.PutRecordOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.PutRecordInput) *kinesis.PutRecordOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.PutRecordOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.PutRecordInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_PutRecord_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRecord'
type KinesisPort_PutRecord_Call struct {
	*mock.Call
}

// PutRecord is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.PutRecordInput
func (_e *KinesisPort_Expecter) PutRecord(ctx interface{}, input interface{}) *KinesisPort_PutRecord_Call {
	return &KinesisPort_PutRecord_Call{Call: _e.mock.On("PutRecord", ctx, input)}
}

func (_c *KinesisPort_PutRecord_Call) Run(run func(ctx context.Context, input *kinesis.PutRecordInput)) *KinesisPort_PutRecord_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.PutRecordInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.PutRecordInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_PutRecord_Call) Return(putRecordOutput *kinesis.PutRecordOutput, err error) *KinesisPort_PutRecord_Call {
	_c.Call.Return(putRecordOutput, err)
	return _c
}

func (_c *KinesisPort_PutRecord_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.PutRecordInput) (*kinesis.PutRecordOutput, error)) *KinesisPort_PutRecord_Call {
	_c.Call.Return(run)
	return _c
}

// PutRecords provides a mock function for the type KinesisPort
func (_mock *KinesisPort) PutRecords(ctx context.Context, input *kinesis.PutRecordsInput) (*kinesis.PutRecordsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutRecords")
	}

	var r0 *kinesis.PutRecordsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.PutRecordsInput) (*kinesis.PutRecordsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.PutRecordsInput) *kinesis.PutRecordsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.PutRecordsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.PutRecordsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_PutRecords_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutRecords'
type KinesisPort_PutRecords_Call struct {
	*mock.Call
}

// PutRecords is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.PutRecordsInput
func (_e *KinesisPort_Expecter) PutRecords(ctx interface{}, input interface{}) *KinesisPort_PutRecords_Call {
	return &KinesisPort_PutRecords_Call{Call: _e.mock.On("PutRecords", ctx, input)}
}

func (_c *KinesisPort_PutRecords_Call) Run(run func(ctx context.Context, input *kinesis.PutRecordsInput)) *KinesisPort_PutRecords_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.PutRecordsInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.PutRecordsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_PutRecords_Call) Return(putRecordsOutput *kinesis.PutRecordsOutput, err error) *KinesisPort_PutRecords_Call {
	_c.Call.Return(putRecordsOutput, err)
	return _c
}

func (_c *KinesisPort_PutRecords_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.PutRecordsInput) (*kinesis.PutRecordsOutput, error)) *KinesisPort_PutRecords_Call {
	_c.Call.Return(run)
	return _c
}

// SplitShard provides a mock function for the type KinesisPort
func (_mock *KinesisPort) SplitShard(ctx context.Context, input *kinesis.SplitShardInput) (*kinesis.SplitShardOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SplitShard")
	}

	var r0 *kinesis.SplitShardOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.SplitShardInput) (*kinesis.SplitShardOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.SplitShardInput) *kinesis.SplitShardOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.SplitShardOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.SplitShardInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_SplitShard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SplitShard'
type KinesisPort_SplitShard_Call struct {
	*mock.Call
}

// SplitShard is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.SplitShardInput
func (_e *KinesisPort_Expecter) SplitShard(ctx interface{}, input interface{}) *KinesisPort_SplitShard_Call {
	return &KinesisPort_SplitShard_Call{Call: _e.mock.On("SplitShard", ctx, input)}
}

func (_c *KinesisPort_SplitShard_Call) Run(run func(ctx context.Context, input *kinesis.SplitShardInput)) *KinesisPort_SplitShard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.SplitShardInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.SplitShardInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_SplitShard_Call) Return(splitShardOutput *kinesis.SplitShardOutput, err error) *KinesisPort_SplitShard_Call {
	_c.Call.Return(splitShardOutput, err)
	return _c
}

func (_c *KinesisPort_SplitShard_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.SplitShardInput) (*kinesis.SplitShardOutput, error)) *KinesisPort_SplitShard_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateShardCount provides a mock function for the type KinesisPort
func (_mock *KinesisPort) UpdateShardCount(ctx context.Context, input *kinesis.UpdateShardCountInput) (*kinesis.UpdateShardCountOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateShardCount")
	}

	var r0 *kinesis.UpdateShardCountOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.UpdateShardCountInput) (*kinesis.UpdateShardCountOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *kinesis.UpdateShardCountInput) *kinesis.UpdateShardCountOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*kinesis.UpdateShardCountOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *kinesis.UpdateShardCountInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// KinesisPort_UpdateShardCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateShardCount'
type KinesisPort_UpdateShardCount_Call struct {
	*mock.Call
}

// UpdateShardCount is a helper method to define mock.On call
//   - ctx context.Context
//   - input *kinesis.UpdateShardCountInput
func (_e *KinesisPort_Expecter) UpdateShardCount(ctx interface{}, input interface{}) *KinesisPort_UpdateShardCount_Call {
	return &KinesisPort_UpdateShardCount_Call{Call: _e.mock.On("UpdateShardCount", ctx, input)}
}

func (_c *KinesisPort_UpdateShardCount_Call) Run(run func(ctx context.Context, input *kinesis.UpdateShardCountInput)) *KinesisPort_UpdateShardCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *kinesis.UpdateShardCountInput
		if args[1] != nil {
			arg1 = args[1].(*kinesis.UpdateShardCountInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *KinesisPort_UpdateShardCount_Call) Return(updateShardCountOutput *kinesis.UpdateShardCountOutput, err error) *KinesisPort_UpdateShardCount_Call {
	_c.Call.Return(updateShardCountOutput, err)
	return _c
}

func (_c *KinesisPort_UpdateShardCount_Call) RunAndReturn(run func(ctx context.Context, input *kinesis.UpdateShardCountInput) (*kinesis.UpdateShardCountOutput, error)) *KinesisPort_UpdateShardCount_Call {
	_c.Call.Return(run)
	return _c
}
