// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/lambda"
	mock "github.com/stretchr/testify/mock"
)

// NewLambdaClientPort creates a new instance of LambdaClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewLambdaClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *LambdaClientPort {
	mock := &LambdaClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// LambdaClientPort is an autogenerated mock type for the LambdaClientPort type
type LambdaClientPort struct {
	mock.Mock
}

type LambdaClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *LambdaClientPort) EXPECT() *LambdaClientPort_Expecter {
	return &LambdaClientPort_Expecter{mock: &_m.Mock}
}

// CreateFunction provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) CreateFunction(ctx context.Context, input *lambda.CreateFunctionInput, opts ...func(*lambda.Options)) (*lambda.CreateFunctionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateFunction")
	}

	var r0 *lambda.CreateFunctionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.CreateFunctionInput, ...func(*lambda.Options)) (*lambda.CreateFunctionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.CreateFunctionInput, ...func(*lambda.Options)) *lambda.CreateFunctionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.CreateFunctionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.CreateFunctionInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_CreateFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateFunction'
type LambdaClientPort_CreateFunction_Call struct {
	*mock.Call
}

// CreateFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.CreateFunctionInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) CreateFunction(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_CreateFunction_Call {
	return &LambdaClientPort_CreateFunction_Call{Call: _e.mock.On("CreateFunction",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_CreateFunction_Call) Run(run func(ctx context.Context, input *lambda.CreateFunctionInput, opts ...func(*lambda.Options))) *LambdaClientPort_CreateFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.CreateFunctionInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.CreateFunctionInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_CreateFunction_Call) Return(createFunctionOutput *lambda.CreateFunctionOutput, err error) *LambdaClientPort_CreateFunction_Call {
	_c.Call.Return(createFunctionOutput, err)
	return _c
}

func (_c *LambdaClientPort_CreateFunction_Call) RunAndReturn(run func(ctx context.Context, input *lambda.CreateFunctionInput, opts ...func(*lambda.Options)) (*lambda.CreateFunctionOutput, error)) *LambdaClientPort_CreateFunction_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteFunction provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) DeleteFunction(ctx context.Context, input *lambda.DeleteFunctionInput, opts ...func(*lambda.Options)) (*lambda.DeleteFunctionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteFunction")
	}

	var r0 *lambda.DeleteFunctionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.DeleteFunctionInput, ...func(*lambda.Options)) (*lambda.DeleteFunctionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.DeleteFunctionInput, ...func(*lambda.Options)) *lambda.DeleteFunctionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.DeleteFunctionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.DeleteFunctionInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_DeleteFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteFunction'
type LambdaClientPort_DeleteFunction_Call struct {
	*mock.Call
}

// DeleteFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.DeleteFunctionInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) DeleteFunction(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_DeleteFunction_Call {
	return &LambdaClientPort_DeleteFunction_Call{Call: _e.mock.On("DeleteFunction",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_DeleteFunction_Call) Run(run func(ctx context.Context, input *lambda.DeleteFunctionInput, opts ...func(*lambda.Options))) *LambdaClientPort_DeleteFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.DeleteFunctionInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.DeleteFunctionInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_DeleteFunction_Call) Return(deleteFunctionOutput *lambda.DeleteFunctionOutput, err error) *LambdaClientPort_DeleteFunction_Call {
	_c.Call.Return(deleteFunctionOutput, err)
	return _c
}

func (_c *LambdaClientPort_DeleteFunction_Call) RunAndReturn(run func(ctx context.Context, input *lambda.DeleteFunctionInput, opts ...func(*lambda.Options)) (*lambda.DeleteFunctionOutput, error)) *LambdaClientPort_DeleteFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunction provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) GetFunction(ctx context.Context, input *lambda.GetFunctionInput, opts ...func(*lambda.Options)) (*lambda.GetFunctionOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFunction")
	}

	var r0 *lambda.GetFunctionOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.GetFunctionInput, ...func(*lambda.Options)) (*lambda.GetFunctionOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.GetFunctionInput, ...func(*lambda.Options)) *lambda.GetFunctionOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.GetFunctionOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.GetFunctionInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_GetFunction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunction'
type LambdaClientPort_GetFunction_Call struct {
	*mock.Call
}

// GetFunction is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.GetFunctionInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) GetFunction(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_GetFunction_Call {
	return &LambdaClientPort_GetFunction_Call{Call: _e.mock.On("GetFunction",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_GetFunction_Call) Run(run func(ctx context.Context, input *lambda.GetFunctionInput, opts ...func(*lambda.Options))) *LambdaClientPort_GetFunction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.GetFunctionInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.GetFunctionInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_GetFunction_Call) Return(getFunctionOutput *lambda.GetFunctionOutput, err error) *LambdaClientPort_GetFunction_Call {
	_c.Call.Return(getFunctionOutput, err)
	return _c
}

func (_c *LambdaClientPort_GetFunction_Call) RunAndReturn(run func(ctx context.Context, input *lambda.GetFunctionInput, opts ...func(*lambda.Options)) (*lambda.GetFunctionOutput, error)) *LambdaClientPort_GetFunction_Call {
	_c.Call.Return(run)
	return _c
}

// GetFunctionConfiguration provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) GetFunctionConfiguration(ctx context.Context, input *lambda.GetFunctionConfigurationInput, opts ...func(*lambda.Options)) (*lambda.GetFunctionConfigurationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFunctionConfiguration")
	}

	var r0 *lambda.GetFunctionConfigurationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.GetFunctionConfigurationInput, ...func(*lambda.Options)) (*lambda.GetFunctionConfigurationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.GetFunctionConfigurationInput, ...func(*lambda.Options)) *lambda.GetFunctionConfigurationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.GetFunctionConfigurationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.GetFunctionConfigurationInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_GetFunctionConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFunctionConfiguration'
type LambdaClientPort_GetFunctionConfiguration_Call struct {
	*mock.Call
}

// GetFunctionConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.GetFunctionConfigurationInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) GetFunctionConfiguration(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_GetFunctionConfiguration_Call {
	return &LambdaClientPort_GetFunctionConfiguration_Call{Call: _e.mock.On("GetFunctionConfiguration",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_GetFunctionConfiguration_Call) Run(run func(ctx context.Context, input *lambda.GetFunctionConfigurationInput, opts ...func(*lambda.Options))) *LambdaClientPort_GetFunctionConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.GetFunctionConfigurationInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.GetFunctionConfigurationInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_GetFunctionConfiguration_Call) Return(getFunctionConfigurationOutput *lambda.GetFunctionConfigurationOutput, err error) *LambdaClientPort_GetFunctionConfiguration_Call {
	_c.Call.Return(getFunctionConfigurationOutput, err)
	return _c
}

func (_c *LambdaClientPort_GetFunctionConfiguration_Call) RunAndReturn(run func(ctx context.Context, input *lambda.GetFunctionConfigurationInput, opts ...func(*lambda.Options)) (*lambda.GetFunctionConfigurationOutput, error)) *LambdaClientPort_GetFunctionConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// Invoke provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) Invoke(ctx context.Context, input *lambda.InvokeInput, opts ...func(*lambda.Options)) (*lambda.InvokeOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Invoke")
	}

	var r0 *lambda.InvokeOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) (*lambda.InvokeOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) *lambda.InvokeOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.InvokeOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.InvokeInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_Invoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Invoke'
type LambdaClientPort_Invoke_Call struct {
	*mock.Call
}

// Invoke is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.InvokeInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) Invoke(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_Invoke_Call {
	return &LambdaClientPort_Invoke_Call{Call: _e.mock.On("Invoke",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_Invoke_Call) Run(run func(ctx context.Context, input *lambda.InvokeInput, opts ...func(*lambda.Options))) *LambdaClientPort_Invoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.InvokeInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.InvokeInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_Invoke_Call) Return(invokeOutput *lambda.InvokeOutput, err error) *LambdaClientPort_Invoke_Call {
	_c.Call.Return(invokeOutput, err)
	return _c
}

func (_c *LambdaClientPort_Invoke_Call) RunAndReturn(run func(ctx context.Context, input *lambda.InvokeInput, opts ...func(*lambda.Options)) (*lambda.InvokeOutput, error)) *LambdaClientPort_Invoke_Call {
	_c.Call.Return(run)
	return _c
}

// ListFunctions provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) ListFunctions(ctx context.Context, input *lambda.ListFunctionsInput, opts ...func(*lambda.Options)) (*lambda.ListFunctionsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListFunctions")
	}

	var r0 *lambda.ListFunctionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.ListFunctionsInput, ...func(*lambda.Options)) (*lambda.ListFunctionsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.ListFunctionsInput, ...func(*lambda.Options)) *lambda.ListFunctionsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.ListFunctionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.ListFunctionsInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_ListFunctions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFunctions'
type LambdaClientPort_ListFunctions_Call struct {
	*mock.Call
}

// ListFunctions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.ListFunctionsInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) ListFunctions(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_ListFunctions_Call {
	return &LambdaClientPort_ListFunctions_Call{Call: _e.mock.On("ListFunctions",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_ListFunctions_Call) Run(run func(ctx context.Context, input *lambda.ListFunctionsInput, opts ...func(*lambda.Options))) *LambdaClientPort_ListFunctions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.ListFunctionsInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.ListFunctionsInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_ListFunctions_Call) Return(listFunctionsOutput *lambda.ListFunctionsOutput, err error) *LambdaClientPort_ListFunctions_Call {
	_c.Call.Return(listFunctionsOutput, err)
	return _c
}

func (_c *LambdaClientPort_ListFunctions_Call) RunAndReturn(run func(ctx context.Context, input *lambda.ListFunctionsInput, opts ...func(*lambda.Options)) (*lambda.ListFunctionsOutput, error)) *LambdaClientPort_ListFunctions_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFunctionCode provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) UpdateFunctionCode(ctx context.Context, input *lambda.UpdateFunctionCodeInput, opts ...func(*lambda.Options)) (*lambda.UpdateFunctionCodeOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateFunctionCode")
	}

	var r0 *lambda.UpdateFunctionCodeOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.UpdateFunctionCodeInput, ...func(*lambda.Options)) (*lambda.UpdateFunctionCodeOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.UpdateFunctionCodeInput, ...func(*lambda.Options)) *lambda.UpdateFunctionCodeOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.UpdateFunctionCodeOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.UpdateFunctionCodeInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_UpdateFunctionCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFunctionCode'
type LambdaClientPort_UpdateFunctionCode_Call struct {
	*mock.Call
}

// UpdateFunctionCode is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.UpdateFunctionCodeInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) UpdateFunctionCode(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_UpdateFunctionCode_Call {
	return &LambdaClientPort_UpdateFunctionCode_Call{Call: _e.mock.On("UpdateFunctionCode",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_UpdateFunctionCode_Call) Run(run func(ctx context.Context, input *lambda.UpdateFunctionCodeInput, opts ...func(*lambda.Options))) *LambdaClientPort_UpdateFunctionCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.UpdateFunctionCodeInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.UpdateFunctionCodeInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_UpdateFunctionCode_Call) Return(updateFunctionCodeOutput *lambda.UpdateFunctionCodeOutput, err error) *LambdaClientPort_UpdateFunctionCode_Call {
	_c.Call.Return(updateFunctionCodeOutput, err)
	return _c
}

func (_c *LambdaClientPort_UpdateFunctionCode_Call) RunAndReturn(run func(ctx context.Context, input *lambda.UpdateFunctionCodeInput, opts ...func(*lambda.Options)) (*lambda.UpdateFunctionCodeOutput, error)) *LambdaClientPort_UpdateFunctionCode_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateFunctionConfiguration provides a mock function for the type LambdaClientPort
func (_mock *LambdaClientPort) UpdateFunctionConfiguration(ctx context.Context, input *lambda.UpdateFunctionConfigurationInput, opts ...func(*lambda.Options)) (*lambda.UpdateFunctionConfigurationOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateFunctionConfiguration")
	}

	var r0 *lambda.UpdateFunctionConfigurationOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.UpdateFunctionConfigurationInput, ...func(*lambda.Options)) (*lambda.UpdateFunctionConfigurationOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *lambda.UpdateFunctionConfigurationInput, ...func(*lambda.Options)) *lambda.UpdateFunctionConfigurationOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lambda.UpdateFunctionConfigurationOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *lambda.UpdateFunctionConfigurationInput, ...func(*lambda.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// LambdaClientPort_UpdateFunctionConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateFunctionConfiguration'
type LambdaClientPort_UpdateFunctionConfiguration_Call struct {
	*mock.Call
}

// UpdateFunctionConfiguration is a helper method to define mock.On call
//   - ctx context.Context
//   - input *lambda.UpdateFunctionConfigurationInput
//   - opts ...func(*lambda.Options)
func (_e *LambdaClientPort_Expecter) UpdateFunctionConfiguration(ctx interface{}, input interface{}, opts ...interface{}) *LambdaClientPort_UpdateFunctionConfiguration_Call {
	return &LambdaClientPort_UpdateFunctionConfiguration_Call{Call: _e.mock.On("UpdateFunctionConfiguration",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *LambdaClientPort_UpdateFunctionConfiguration_Call) Run(run func(ctx context.Context, input *lambda.UpdateFunctionConfigurationInput, opts ...func(*lambda.Options))) *LambdaClientPort_UpdateFunctionConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *lambda.UpdateFunctionConfigurationInput
		if args[1] != nil {
			arg1 = args[1].(*lambda.UpdateFunctionConfigurationInput)
		}
		var arg2 []func(*lambda.Options)
		var variadicArgs []func(*lambda.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*lambda.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *LambdaClientPort_UpdateFunctionConfiguration_Call) Return(updateFunctionConfigurationOutput *lambda.UpdateFunctionConfigurationOutput, err error) *LambdaClientPort_UpdateFunctionConfiguration_Call {
	_c.Call.Return(updateFunctionConfigurationOutput, err)
	return _c
}

func (_c *LambdaClientPort_UpdateFunctionConfiguration_Call) RunAndReturn(run func(ctx context.Context, input *lambda.UpdateFunctionConfigurationInput, opts ...func(*lambda.Options)) (*lambda.UpdateFunctionConfigurationOutput, error)) *LambdaClientPort_UpdateFunctionConfiguration_Call {
	_c.Call.Return(run)
	return _c
}
