// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"github.com/my-devstack/mydevstack-proxy/internal/config"
	"github.com/my-devstack/mydevstack-proxy/internal/ports"
	mock "github.com/stretchr/testify/mock"
)

// NewProxyService creates a new instance of ProxyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProxyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProxyService {
	mock := &ProxyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// ProxyService is an autogenerated mock type for the ProxyService type
type ProxyService struct {
	mock.Mock
}

type ProxyService_Expecter struct {
	mock *mock.Mock
}

func (_m *ProxyService) EXPECT() *ProxyService_Expecter {
	return &ProxyService_Expecter{mock: &_m.Mock}
}

// APIGateway provides a mock function for the type ProxyService
func (_mock *ProxyService) APIGateway() ports.APIGatewayPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIGateway")
	}

	var r0 ports.APIGatewayPort
	if returnFunc, ok := ret.Get(0).(func() ports.APIGatewayPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.APIGatewayPort)
		}
	}
	return r0
}

// ProxyService_APIGateway_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIGateway'
type ProxyService_APIGateway_Call struct {
	*mock.Call
}

// APIGateway is a helper method to define mock.On call
func (_e *ProxyService_Expecter) APIGateway() *ProxyService_APIGateway_Call {
	return &ProxyService_APIGateway_Call{Call: _e.mock.On("APIGateway")}
}

func (_c *ProxyService_APIGateway_Call) Run(run func()) *ProxyService_APIGateway_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_APIGateway_Call) Return(aPIGatewayPort ports.APIGatewayPort) *ProxyService_APIGateway_Call {
	_c.Call.Return(aPIGatewayPort)
	return _c
}

func (_c *ProxyService_APIGateway_Call) RunAndReturn(run func() ports.APIGatewayPort) *ProxyService_APIGateway_Call {
	_c.Call.Return(run)
	return _c
}

// APIGatewayV2 provides a mock function for the type ProxyService
func (_mock *ProxyService) APIGatewayV2() ports.APIGatewayV2Port {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for APIGatewayV2")
	}

	var r0 ports.APIGatewayV2Port
	if returnFunc, ok := ret.Get(0).(func() ports.APIGatewayV2Port); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.APIGatewayV2Port)
		}
	}
	return r0
}

// ProxyService_APIGatewayV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'APIGatewayV2'
type ProxyService_APIGatewayV2_Call struct {
	*mock.Call
}

// APIGatewayV2 is a helper method to define mock.On call
func (_e *ProxyService_Expecter) APIGatewayV2() *ProxyService_APIGatewayV2_Call {
	return &ProxyService_APIGatewayV2_Call{Call: _e.mock.On("APIGatewayV2")}
}

func (_c *ProxyService_APIGatewayV2_Call) Run(run func()) *ProxyService_APIGatewayV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_APIGatewayV2_Call) Return(aPIGatewayV2Port ports.APIGatewayV2Port) *ProxyService_APIGatewayV2_Call {
	_c.Call.Return(aPIGatewayV2Port)
	return _c
}

func (_c *ProxyService_APIGatewayV2_Call) RunAndReturn(run func() ports.APIGatewayV2Port) *ProxyService_APIGatewayV2_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type ProxyService
func (_mock *ProxyService) Config() *configloader.Config {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 *configloader.Config
	if returnFunc, ok := ret.Get(0).(func() *configloader.Config); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*configloader.Config)
		}
	}
	return r0
}

// ProxyService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type ProxyService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *ProxyService_Expecter) Config() *ProxyService_Config_Call {
	return &ProxyService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *ProxyService_Config_Call) Run(run func()) *ProxyService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_Config_Call) Return(config *configloader.Config) *ProxyService_Config_Call {
	_c.Call.Return(config)
	return _c
}

func (_c *ProxyService_Config_Call) RunAndReturn(run func() *configloader.Config) *ProxyService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// DynamoDB provides a mock function for the type ProxyService
func (_mock *ProxyService) DynamoDB() ports.DynamoDBPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DynamoDB")
	}

	var r0 ports.DynamoDBPort
	if returnFunc, ok := ret.Get(0).(func() ports.DynamoDBPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.DynamoDBPort)
		}
	}
	return r0
}

// ProxyService_DynamoDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DynamoDB'
type ProxyService_DynamoDB_Call struct {
	*mock.Call
}

// DynamoDB is a helper method to define mock.On call
func (_e *ProxyService_Expecter) DynamoDB() *ProxyService_DynamoDB_Call {
	return &ProxyService_DynamoDB_Call{Call: _e.mock.On("DynamoDB")}
}

func (_c *ProxyService_DynamoDB_Call) Run(run func()) *ProxyService_DynamoDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_DynamoDB_Call) Return(dynamoDBPort ports.DynamoDBPort) *ProxyService_DynamoDB_Call {
	_c.Call.Return(dynamoDBPort)
	return _c
}

func (_c *ProxyService_DynamoDB_Call) RunAndReturn(run func() ports.DynamoDBPort) *ProxyService_DynamoDB_Call {
	_c.Call.Return(run)
	return _c
}

// ElastiCache provides a mock function for the type ProxyService
func (_mock *ProxyService) ElastiCache() ports.ElastiCachePort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ElastiCache")
	}

	var r0 ports.ElastiCachePort
	if returnFunc, ok := ret.Get(0).(func() ports.ElastiCachePort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.ElastiCachePort)
		}
	}
	return r0
}

// ProxyService_ElastiCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ElastiCache'
type ProxyService_ElastiCache_Call struct {
	*mock.Call
}

// ElastiCache is a helper method to define mock.On call
func (_e *ProxyService_Expecter) ElastiCache() *ProxyService_ElastiCache_Call {
	return &ProxyService_ElastiCache_Call{Call: _e.mock.On("ElastiCache")}
}

func (_c *ProxyService_ElastiCache_Call) Run(run func()) *ProxyService_ElastiCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_ElastiCache_Call) Return(elastiCachePort ports.ElastiCachePort) *ProxyService_ElastiCache_Call {
	_c.Call.Return(elastiCachePort)
	return _c
}

func (_c *ProxyService_ElastiCache_Call) RunAndReturn(run func() ports.ElastiCachePort) *ProxyService_ElastiCache_Call {
	_c.Call.Return(run)
	return _c
}

// IAM provides a mock function for the type ProxyService
func (_mock *ProxyService) IAM() ports.IAMPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IAM")
	}

	var r0 ports.IAMPort
	if returnFunc, ok := ret.Get(0).(func() ports.IAMPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.IAMPort)
		}
	}
	return r0
}

// ProxyService_IAM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IAM'
type ProxyService_IAM_Call struct {
	*mock.Call
}

// IAM is a helper method to define mock.On call
func (_e *ProxyService_Expecter) IAM() *ProxyService_IAM_Call {
	return &ProxyService_IAM_Call{Call: _e.mock.On("IAM")}
}

func (_c *ProxyService_IAM_Call) Run(run func()) *ProxyService_IAM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_IAM_Call) Return(iAMPort ports.IAMPort) *ProxyService_IAM_Call {
	_c.Call.Return(iAMPort)
	return _c
}

func (_c *ProxyService_IAM_Call) RunAndReturn(run func() ports.IAMPort) *ProxyService_IAM_Call {
	_c.Call.Return(run)
	return _c
}

// KMS provides a mock function for the type ProxyService
func (_mock *ProxyService) KMS() ports.KMSPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for KMS")
	}

	var r0 ports.KMSPort
	if returnFunc, ok := ret.Get(0).(func() ports.KMSPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.KMSPort)
		}
	}
	return r0
}

// ProxyService_KMS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'KMS'
type ProxyService_KMS_Call struct {
	*mock.Call
}

// KMS is a helper method to define mock.On call
func (_e *ProxyService_Expecter) KMS() *ProxyService_KMS_Call {
	return &ProxyService_KMS_Call{Call: _e.mock.On("KMS")}
}

func (_c *ProxyService_KMS_Call) Run(run func()) *ProxyService_KMS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_KMS_Call) Return(kMSPort ports.KMSPort) *ProxyService_KMS_Call {
	_c.Call.Return(kMSPort)
	return _c
}

func (_c *ProxyService_KMS_Call) RunAndReturn(run func() ports.KMSPort) *ProxyService_KMS_Call {
	_c.Call.Return(run)
	return _c
}

// Kinesis provides a mock function for the type ProxyService
func (_mock *ProxyService) Kinesis() ports.KinesisPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Kinesis")
	}

	var r0 ports.KinesisPort
	if returnFunc, ok := ret.Get(0).(func() ports.KinesisPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.KinesisPort)
		}
	}
	return r0
}

// ProxyService_Kinesis_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Kinesis'
type ProxyService_Kinesis_Call struct {
	*mock.Call
}

// Kinesis is a helper method to define mock.On call
func (_e *ProxyService_Expecter) Kinesis() *ProxyService_Kinesis_Call {
	return &ProxyService_Kinesis_Call{Call: _e.mock.On("Kinesis")}
}

func (_c *ProxyService_Kinesis_Call) Run(run func()) *ProxyService_Kinesis_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_Kinesis_Call) Return(kinesisPort ports.KinesisPort) *ProxyService_Kinesis_Call {
	_c.Call.Return(kinesisPort)
	return _c
}

func (_c *ProxyService_Kinesis_Call) RunAndReturn(run func() ports.KinesisPort) *ProxyService_Kinesis_Call {
	_c.Call.Return(run)
	return _c
}

// Lambda provides a mock function for the type ProxyService
func (_mock *ProxyService) Lambda() ports.LambdaPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Lambda")
	}

	var r0 ports.LambdaPort
	if returnFunc, ok := ret.Get(0).(func() ports.LambdaPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.LambdaPort)
		}
	}
	return r0
}

// ProxyService_Lambda_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Lambda'
type ProxyService_Lambda_Call struct {
	*mock.Call
}

// Lambda is a helper method to define mock.On call
func (_e *ProxyService_Expecter) Lambda() *ProxyService_Lambda_Call {
	return &ProxyService_Lambda_Call{Call: _e.mock.On("Lambda")}
}

func (_c *ProxyService_Lambda_Call) Run(run func()) *ProxyService_Lambda_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_Lambda_Call) Return(lambdaPort ports.LambdaPort) *ProxyService_Lambda_Call {
	_c.Call.Return(lambdaPort)
	return _c
}

func (_c *ProxyService_Lambda_Call) RunAndReturn(run func() ports.LambdaPort) *ProxyService_Lambda_Call {
	_c.Call.Return(run)
	return _c
}

// RDS provides a mock function for the type ProxyService
func (_mock *ProxyService) RDS() ports.RDSPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RDS")
	}

	var r0 ports.RDSPort
	if returnFunc, ok := ret.Get(0).(func() ports.RDSPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.RDSPort)
		}
	}
	return r0
}

// ProxyService_RDS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RDS'
type ProxyService_RDS_Call struct {
	*mock.Call
}

// RDS is a helper method to define mock.On call
func (_e *ProxyService_Expecter) RDS() *ProxyService_RDS_Call {
	return &ProxyService_RDS_Call{Call: _e.mock.On("RDS")}
}

func (_c *ProxyService_RDS_Call) Run(run func()) *ProxyService_RDS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_RDS_Call) Return(rDSPort ports.RDSPort) *ProxyService_RDS_Call {
	_c.Call.Return(rDSPort)
	return _c
}

func (_c *ProxyService_RDS_Call) RunAndReturn(run func() ports.RDSPort) *ProxyService_RDS_Call {
	_c.Call.Return(run)
	return _c
}

// Region provides a mock function for the type ProxyService
func (_mock *ProxyService) Region() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Region")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// ProxyService_Region_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Region'
type ProxyService_Region_Call struct {
	*mock.Call
}

// Region is a helper method to define mock.On call
func (_e *ProxyService_Expecter) Region() *ProxyService_Region_Call {
	return &ProxyService_Region_Call{Call: _e.mock.On("Region")}
}

func (_c *ProxyService_Region_Call) Run(run func()) *ProxyService_Region_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_Region_Call) Return(s string) *ProxyService_Region_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *ProxyService_Region_Call) RunAndReturn(run func() string) *ProxyService_Region_Call {
	_c.Call.Return(run)
	return _c
}

// S3 provides a mock function for the type ProxyService
func (_mock *ProxyService) S3() ports.S3Port {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for S3")
	}

	var r0 ports.S3Port
	if returnFunc, ok := ret.Get(0).(func() ports.S3Port); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.S3Port)
		}
	}
	return r0
}

// ProxyService_S3_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'S3'
type ProxyService_S3_Call struct {
	*mock.Call
}

// S3 is a helper method to define mock.On call
func (_e *ProxyService_Expecter) S3() *ProxyService_S3_Call {
	return &ProxyService_S3_Call{Call: _e.mock.On("S3")}
}

func (_c *ProxyService_S3_Call) Run(run func()) *ProxyService_S3_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_S3_Call) Return(s3Port ports.S3Port) *ProxyService_S3_Call {
	_c.Call.Return(s3Port)
	return _c
}

func (_c *ProxyService_S3_Call) RunAndReturn(run func() ports.S3Port) *ProxyService_S3_Call {
	_c.Call.Return(run)
	return _c
}

// SNS provides a mock function for the type ProxyService
func (_mock *ProxyService) SNS() ports.SNSPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SNS")
	}

	var r0 ports.SNSPort
	if returnFunc, ok := ret.Get(0).(func() ports.SNSPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SNSPort)
		}
	}
	return r0
}

// ProxyService_SNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SNS'
type ProxyService_SNS_Call struct {
	*mock.Call
}

// SNS is a helper method to define mock.On call
func (_e *ProxyService_Expecter) SNS() *ProxyService_SNS_Call {
	return &ProxyService_SNS_Call{Call: _e.mock.On("SNS")}
}

func (_c *ProxyService_SNS_Call) Run(run func()) *ProxyService_SNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_SNS_Call) Return(sNSPort ports.SNSPort) *ProxyService_SNS_Call {
	_c.Call.Return(sNSPort)
	return _c
}

func (_c *ProxyService_SNS_Call) RunAndReturn(run func() ports.SNSPort) *ProxyService_SNS_Call {
	_c.Call.Return(run)
	return _c
}

// SQS provides a mock function for the type ProxyService
func (_mock *ProxyService) SQS() ports.SQSPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SQS")
	}

	var r0 ports.SQSPort
	if returnFunc, ok := ret.Get(0).(func() ports.SQSPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SQSPort)
		}
	}
	return r0
}

// ProxyService_SQS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SQS'
type ProxyService_SQS_Call struct {
	*mock.Call
}

// SQS is a helper method to define mock.On call
func (_e *ProxyService_Expecter) SQS() *ProxyService_SQS_Call {
	return &ProxyService_SQS_Call{Call: _e.mock.On("SQS")}
}

func (_c *ProxyService_SQS_Call) Run(run func()) *ProxyService_SQS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_SQS_Call) Return(sQSPort ports.SQSPort) *ProxyService_SQS_Call {
	_c.Call.Return(sQSPort)
	return _c
}

func (_c *ProxyService_SQS_Call) RunAndReturn(run func() ports.SQSPort) *ProxyService_SQS_Call {
	_c.Call.Return(run)
	return _c
}

// SSM provides a mock function for the type ProxyService
func (_mock *ProxyService) SSM() ports.SSMPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SSM")
	}

	var r0 ports.SSMPort
	if returnFunc, ok := ret.Get(0).(func() ports.SSMPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SSMPort)
		}
	}
	return r0
}

// ProxyService_SSM_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SSM'
type ProxyService_SSM_Call struct {
	*mock.Call
}

// SSM is a helper method to define mock.On call
func (_e *ProxyService_Expecter) SSM() *ProxyService_SSM_Call {
	return &ProxyService_SSM_Call{Call: _e.mock.On("SSM")}
}

func (_c *ProxyService_SSM_Call) Run(run func()) *ProxyService_SSM_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_SSM_Call) Return(sSMPort ports.SSMPort) *ProxyService_SSM_Call {
	_c.Call.Return(sSMPort)
	return _c
}

func (_c *ProxyService_SSM_Call) RunAndReturn(run func() ports.SSMPort) *ProxyService_SSM_Call {
	_c.Call.Return(run)
	return _c
}

// SecretsManager provides a mock function for the type ProxyService
func (_mock *ProxyService) SecretsManager() ports.SecretsManagerPort {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SecretsManager")
	}

	var r0 ports.SecretsManagerPort
	if returnFunc, ok := ret.Get(0).(func() ports.SecretsManagerPort); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ports.SecretsManagerPort)
		}
	}
	return r0
}

// ProxyService_SecretsManager_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SecretsManager'
type ProxyService_SecretsManager_Call struct {
	*mock.Call
}

// SecretsManager is a helper method to define mock.On call
func (_e *ProxyService_Expecter) SecretsManager() *ProxyService_SecretsManager_Call {
	return &ProxyService_SecretsManager_Call{Call: _e.mock.On("SecretsManager")}
}

func (_c *ProxyService_SecretsManager_Call) Run(run func()) *ProxyService_SecretsManager_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_SecretsManager_Call) Return(secretsManagerPort ports.SecretsManagerPort) *ProxyService_SecretsManager_Call {
	_c.Call.Return(secretsManagerPort)
	return _c
}

func (_c *ProxyService_SecretsManager_Call) RunAndReturn(run func() ports.SecretsManagerPort) *ProxyService_SecretsManager_Call {
	_c.Call.Return(run)
	return _c
}

// SetRegion provides a mock function for the type ProxyService
func (_mock *ProxyService) SetRegion(region string) error {
	ret := _mock.Called(region)

	if len(ret) == 0 {
		panic("no return value specified for SetRegion")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(region)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProxyService_SetRegion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetRegion'
type ProxyService_SetRegion_Call struct {
	*mock.Call
}

// SetRegion is a helper method to define mock.On call
//   - region string
func (_e *ProxyService_Expecter) SetRegion(region interface{}) *ProxyService_SetRegion_Call {
	return &ProxyService_SetRegion_Call{Call: _e.mock.On("SetRegion", region)}
}

func (_c *ProxyService_SetRegion_Call) Run(run func(region string)) *ProxyService_SetRegion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *ProxyService_SetRegion_Call) Return(err error) *ProxyService_SetRegion_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProxyService_SetRegion_Call) RunAndReturn(run func(region string) error) *ProxyService_SetRegion_Call {
	_c.Call.Return(run)
	return _c
}

// SetServices provides a mock function for the type ProxyService
func (_mock *ProxyService) SetServices() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SetServices")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// ProxyService_SetServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetServices'
type ProxyService_SetServices_Call struct {
	*mock.Call
}

// SetServices is a helper method to define mock.On call
func (_e *ProxyService_Expecter) SetServices() *ProxyService_SetServices_Call {
	return &ProxyService_SetServices_Call{Call: _e.mock.On("SetServices")}
}

func (_c *ProxyService_SetServices_Call) Run(run func()) *ProxyService_SetServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *ProxyService_SetServices_Call) Return(err error) *ProxyService_SetServices_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *ProxyService_SetServices_Call) RunAndReturn(run func() error) *ProxyService_SetServices_Call {
	_c.Call.Return(run)
	return _c
}
