// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/rds"
	mock "github.com/stretchr/testify/mock"
)

// NewRDSClientPort creates a new instance of RDSClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRDSClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *RDSClientPort {
	mock := &RDSClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RDSClientPort is an autogenerated mock type for the RDSClientPort type
type RDSClientPort struct {
	mock.Mock
}

type RDSClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *RDSClientPort) EXPECT() *RDSClientPort_Expecter {
	return &RDSClientPort_Expecter{mock: &_m.Mock}
}

// CreateDBInstance provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) CreateDBInstance(ctx context.Context, input *rds.CreateDBInstanceInput, opts ...func(*rds.Options)) (*rds.CreateDBInstanceOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateDBInstance")
	}

	var r0 *rds.CreateDBInstanceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.CreateDBInstanceInput, ...func(*rds.Options)) (*rds.CreateDBInstanceOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.CreateDBInstanceInput, ...func(*rds.Options)) *rds.CreateDBInstanceOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.CreateDBInstanceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.CreateDBInstanceInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_CreateDBInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDBInstance'
type RDSClientPort_CreateDBInstance_Call struct {
	*mock.Call
}

// CreateDBInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.CreateDBInstanceInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) CreateDBInstance(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_CreateDBInstance_Call {
	return &RDSClientPort_CreateDBInstance_Call{Call: _e.mock.On("CreateDBInstance",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_CreateDBInstance_Call) Run(run func(ctx context.Context, input *rds.CreateDBInstanceInput, opts ...func(*rds.Options))) *RDSClientPort_CreateDBInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.CreateDBInstanceInput
		if args[1] != nil {
			arg1 = args[1].(*rds.CreateDBInstanceInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_CreateDBInstance_Call) Return(createDBInstanceOutput *rds.CreateDBInstanceOutput, err error) *RDSClientPort_CreateDBInstance_Call {
	_c.Call.Return(createDBInstanceOutput, err)
	return _c
}

func (_c *RDSClientPort_CreateDBInstance_Call) RunAndReturn(run func(ctx context.Context, input *rds.CreateDBInstanceInput, opts ...func(*rds.Options)) (*rds.CreateDBInstanceOutput, error)) *RDSClientPort_CreateDBInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteDBInstance provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) DeleteDBInstance(ctx context.Context, input *rds.DeleteDBInstanceInput, opts ...func(*rds.Options)) (*rds.DeleteDBInstanceOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteDBInstance")
	}

	var r0 *rds.DeleteDBInstanceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DeleteDBInstanceInput, ...func(*rds.Options)) (*rds.DeleteDBInstanceOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DeleteDBInstanceInput, ...func(*rds.Options)) *rds.DeleteDBInstanceOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.DeleteDBInstanceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.DeleteDBInstanceInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_DeleteDBInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteDBInstance'
type RDSClientPort_DeleteDBInstance_Call struct {
	*mock.Call
}

// DeleteDBInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.DeleteDBInstanceInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) DeleteDBInstance(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_DeleteDBInstance_Call {
	return &RDSClientPort_DeleteDBInstance_Call{Call: _e.mock.On("DeleteDBInstance",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_DeleteDBInstance_Call) Run(run func(ctx context.Context, input *rds.DeleteDBInstanceInput, opts ...func(*rds.Options))) *RDSClientPort_DeleteDBInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.DeleteDBInstanceInput
		if args[1] != nil {
			arg1 = args[1].(*rds.DeleteDBInstanceInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_DeleteDBInstance_Call) Return(deleteDBInstanceOutput *rds.DeleteDBInstanceOutput, err error) *RDSClientPort_DeleteDBInstance_Call {
	_c.Call.Return(deleteDBInstanceOutput, err)
	return _c
}

func (_c *RDSClientPort_DeleteDBInstance_Call) RunAndReturn(run func(ctx context.Context, input *rds.DeleteDBInstanceInput, opts ...func(*rds.Options)) (*rds.DeleteDBInstanceOutput, error)) *RDSClientPort_DeleteDBInstance_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeDBEngineVersions provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) DescribeDBEngineVersions(ctx context.Context, input *rds.DescribeDBEngineVersionsInput, opts ...func(*rds.Options)) (*rds.DescribeDBEngineVersionsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeDBEngineVersions")
	}

	var r0 *rds.DescribeDBEngineVersionsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBEngineVersionsInput, ...func(*rds.Options)) (*rds.DescribeDBEngineVersionsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBEngineVersionsInput, ...func(*rds.Options)) *rds.DescribeDBEngineVersionsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.DescribeDBEngineVersionsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.DescribeDBEngineVersionsInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_DescribeDBEngineVersions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDBEngineVersions'
type RDSClientPort_DescribeDBEngineVersions_Call struct {
	*mock.Call
}

// DescribeDBEngineVersions is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.DescribeDBEngineVersionsInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) DescribeDBEngineVersions(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_DescribeDBEngineVersions_Call {
	return &RDSClientPort_DescribeDBEngineVersions_Call{Call: _e.mock.On("DescribeDBEngineVersions",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_DescribeDBEngineVersions_Call) Run(run func(ctx context.Context, input *rds.DescribeDBEngineVersionsInput, opts ...func(*rds.Options))) *RDSClientPort_DescribeDBEngineVersions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.DescribeDBEngineVersionsInput
		if args[1] != nil {
			arg1 = args[1].(*rds.DescribeDBEngineVersionsInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_DescribeDBEngineVersions_Call) Return(describeDBEngineVersionsOutput *rds.DescribeDBEngineVersionsOutput, err error) *RDSClientPort_DescribeDBEngineVersions_Call {
	_c.Call.Return(describeDBEngineVersionsOutput, err)
	return _c
}

func (_c *RDSClientPort_DescribeDBEngineVersions_Call) RunAndReturn(run func(ctx context.Context, input *rds.DescribeDBEngineVersionsInput, opts ...func(*rds.Options)) (*rds.DescribeDBEngineVersionsOutput, error)) *RDSClientPort_DescribeDBEngineVersions_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeDBInstances provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) DescribeDBInstances(ctx context.Context, input *rds.DescribeDBInstancesInput, opts ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DescribeDBInstances")
	}

	var r0 *rds.DescribeDBInstancesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) *rds.DescribeDBInstancesOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.DescribeDBInstancesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.DescribeDBInstancesInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_DescribeDBInstances_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeDBInstances'
type RDSClientPort_DescribeDBInstances_Call struct {
	*mock.Call
}

// DescribeDBInstances is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.DescribeDBInstancesInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) DescribeDBInstances(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_DescribeDBInstances_Call {
	return &RDSClientPort_DescribeDBInstances_Call{Call: _e.mock.On("DescribeDBInstances",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_DescribeDBInstances_Call) Run(run func(ctx context.Context, input *rds.DescribeDBInstancesInput, opts ...func(*rds.Options))) *RDSClientPort_DescribeDBInstances_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.DescribeDBInstancesInput
		if args[1] != nil {
			arg1 = args[1].(*rds.DescribeDBInstancesInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_DescribeDBInstances_Call) Return(describeDBInstancesOutput *rds.DescribeDBInstancesOutput, err error) *RDSClientPort_DescribeDBInstances_Call {
	_c.Call.Return(describeDBInstancesOutput, err)
	return _c
}

func (_c *RDSClientPort_DescribeDBInstances_Call) RunAndReturn(run func(ctx context.Context, input *rds.DescribeDBInstancesInput, opts ...func(*rds.Options)) (*rds.DescribeDBInstancesOutput, error)) *RDSClientPort_DescribeDBInstances_Call {
	_c.Call.Return(run)
	return _c
}

// ModifyDBInstance provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) ModifyDBInstance(ctx context.Context, input *rds.ModifyDBInstanceInput, opts ...func(*rds.Options)) (*rds.ModifyDBInstanceOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ModifyDBInstance")
	}

	var r0 *rds.ModifyDBInstanceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.ModifyDBInstanceInput, ...func(*rds.Options)) (*rds.ModifyDBInstanceOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.ModifyDBInstanceInput, ...func(*rds.Options)) *rds.ModifyDBInstanceOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.ModifyDBInstanceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.ModifyDBInstanceInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_ModifyDBInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ModifyDBInstance'
type RDSClientPort_ModifyDBInstance_Call struct {
	*mock.Call
}

// ModifyDBInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.ModifyDBInstanceInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) ModifyDBInstance(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_ModifyDBInstance_Call {
	return &RDSClientPort_ModifyDBInstance_Call{Call: _e.mock.On("ModifyDBInstance",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_ModifyDBInstance_Call) Run(run func(ctx context.Context, input *rds.ModifyDBInstanceInput, opts ...func(*rds.Options))) *RDSClientPort_ModifyDBInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.ModifyDBInstanceInput
		if args[1] != nil {
			arg1 = args[1].(*rds.ModifyDBInstanceInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_ModifyDBInstance_Call) Return(modifyDBInstanceOutput *rds.ModifyDBInstanceOutput, err error) *RDSClientPort_ModifyDBInstance_Call {
	_c.Call.Return(modifyDBInstanceOutput, err)
	return _c
}

func (_c *RDSClientPort_ModifyDBInstance_Call) RunAndReturn(run func(ctx context.Context, input *rds.ModifyDBInstanceInput, opts ...func(*rds.Options)) (*rds.ModifyDBInstanceOutput, error)) *RDSClientPort_ModifyDBInstance_Call {
	_c.Call.Return(run)
	return _c
}

// RebootDBInstance provides a mock function for the type RDSClientPort
func (_mock *RDSClientPort) RebootDBInstance(ctx context.Context, input *rds.RebootDBInstanceInput, opts ...func(*rds.Options)) (*rds.RebootDBInstanceOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RebootDBInstance")
	}

	var r0 *rds.RebootDBInstanceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.RebootDBInstanceInput, ...func(*rds.Options)) (*rds.RebootDBInstanceOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *rds.RebootDBInstanceInput, ...func(*rds.Options)) *rds.RebootDBInstanceOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rds.RebootDBInstanceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *rds.RebootDBInstanceInput, ...func(*rds.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RDSClientPort_RebootDBInstance_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RebootDBInstance'
type RDSClientPort_RebootDBInstance_Call struct {
	*mock.Call
}

// RebootDBInstance is a helper method to define mock.On call
//   - ctx context.Context
//   - input *rds.RebootDBInstanceInput
//   - opts ...func(*rds.Options)
func (_e *RDSClientPort_Expecter) RebootDBInstance(ctx interface{}, input interface{}, opts ...interface{}) *RDSClientPort_RebootDBInstance_Call {
	return &RDSClientPort_RebootDBInstance_Call{Call: _e.mock.On("RebootDBInstance",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *RDSClientPort_RebootDBInstance_Call) Run(run func(ctx context.Context, input *rds.RebootDBInstanceInput, opts ...func(*rds.Options))) *RDSClientPort_RebootDBInstance_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *rds.RebootDBInstanceInput
		if args[1] != nil {
			arg1 = args[1].(*rds.RebootDBInstanceInput)
		}
		var arg2 []func(*rds.Options)
		var variadicArgs []func(*rds.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*rds.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RDSClientPort_RebootDBInstance_Call) Return(rebootDBInstanceOutput *rds.RebootDBInstanceOutput, err error) *RDSClientPort_RebootDBInstance_Call {
	_c.Call.Return(rebootDBInstanceOutput, err)
	return _c
}

func (_c *RDSClientPort_RebootDBInstance_Call) RunAndReturn(run func(ctx context.Context, input *rds.RebootDBInstanceInput, opts ...func(*rds.Options)) (*rds.RebootDBInstanceOutput, error)) *RDSClientPort_RebootDBInstance_Call {
	_c.Call.Return(run)
	return _c
}
