// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/s3"
	mock "github.com/stretchr/testify/mock"
)

// NewS3ClientPort creates a new instance of S3ClientPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewS3ClientPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *S3ClientPort {
	mock := &S3ClientPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// S3ClientPort is an autogenerated mock type for the S3ClientPort type
type S3ClientPort struct {
	mock.Mock
}

type S3ClientPort_Expecter struct {
	mock *mock.Mock
}

func (_m *S3ClientPort) EXPECT() *S3ClientPort_Expecter {
	return &S3ClientPort_Expecter{mock: &_m.Mock}
}

// CreateBucket provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) CreateBucket(ctx context.Context, input *s3.CreateBucketInput, opts ...func(*s3.Options)) (*s3.CreateBucketOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateBucket")
	}

	var r0 *s3.CreateBucketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateBucketInput, ...func(*s3.Options)) (*s3.CreateBucketOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.CreateBucketInput, ...func(*s3.Options)) *s3.CreateBucketOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.CreateBucketOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.CreateBucketInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_CreateBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBucket'
type S3ClientPort_CreateBucket_Call struct {
	*mock.Call
}

// CreateBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.CreateBucketInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) CreateBucket(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_CreateBucket_Call {
	return &S3ClientPort_CreateBucket_Call{Call: _e.mock.On("CreateBucket",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_CreateBucket_Call) Run(run func(ctx context.Context, input *s3.CreateBucketInput, opts ...func(*s3.Options))) *S3ClientPort_CreateBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.CreateBucketInput
		if args[1] != nil {
			arg1 = args[1].(*s3.CreateBucketInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_CreateBucket_Call) Return(createBucketOutput *s3.CreateBucketOutput, err error) *S3ClientPort_CreateBucket_Call {
	_c.Call.Return(createBucketOutput, err)
	return _c
}

func (_c *S3ClientPort_CreateBucket_Call) RunAndReturn(run func(ctx context.Context, input *s3.CreateBucketInput, opts ...func(*s3.Options)) (*s3.CreateBucketOutput, error)) *S3ClientPort_CreateBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteBucket provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) DeleteBucket(ctx context.Context, input *s3.DeleteBucketInput, opts ...func(*s3.Options)) (*s3.DeleteBucketOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteBucket")
	}

	var r0 *s3.DeleteBucketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteBucketInput, ...func(*s3.Options)) (*s3.DeleteBucketOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteBucketInput, ...func(*s3.Options)) *s3.DeleteBucketOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.DeleteBucketOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.DeleteBucketInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_DeleteBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteBucket'
type S3ClientPort_DeleteBucket_Call struct {
	*mock.Call
}

// DeleteBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.DeleteBucketInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) DeleteBucket(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_DeleteBucket_Call {
	return &S3ClientPort_DeleteBucket_Call{Call: _e.mock.On("DeleteBucket",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_DeleteBucket_Call) Run(run func(ctx context.Context, input *s3.DeleteBucketInput, opts ...func(*s3.Options))) *S3ClientPort_DeleteBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.DeleteBucketInput
		if args[1] != nil {
			arg1 = args[1].(*s3.DeleteBucketInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_DeleteBucket_Call) Return(deleteBucketOutput *s3.DeleteBucketOutput, err error) *S3ClientPort_DeleteBucket_Call {
	_c.Call.Return(deleteBucketOutput, err)
	return _c
}

func (_c *S3ClientPort_DeleteBucket_Call) RunAndReturn(run func(ctx context.Context, input *s3.DeleteBucketInput, opts ...func(*s3.Options)) (*s3.DeleteBucketOutput, error)) *S3ClientPort_DeleteBucket_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) DeleteObject(ctx context.Context, input *s3.DeleteObjectInput, opts ...func(*s3.Options)) (*s3.DeleteObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 *s3.DeleteObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) *s3.DeleteObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.DeleteObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.DeleteObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type S3ClientPort_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.DeleteObjectInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) DeleteObject(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_DeleteObject_Call {
	return &S3ClientPort_DeleteObject_Call{Call: _e.mock.On("DeleteObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_DeleteObject_Call) Run(run func(ctx context.Context, input *s3.DeleteObjectInput, opts ...func(*s3.Options))) *S3ClientPort_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.DeleteObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.DeleteObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_DeleteObject_Call) Return(deleteObjectOutput *s3.DeleteObjectOutput, err error) *S3ClientPort_DeleteObject_Call {
	_c.Call.Return(deleteObjectOutput, err)
	return _c
}

func (_c *S3ClientPort_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, input *s3.DeleteObjectInput, opts ...func(*s3.Options)) (*s3.DeleteObjectOutput, error)) *S3ClientPort_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// GetObject provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) GetObject(ctx context.Context, input *s3.GetObjectInput, opts ...func(*s3.Options)) (*s3.GetObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetObject")
	}

	var r0 *s3.GetObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) (*s3.GetObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) *s3.GetObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.GetObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.GetObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_GetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetObject'
type S3ClientPort_GetObject_Call struct {
	*mock.Call
}

// GetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.GetObjectInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) GetObject(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_GetObject_Call {
	return &S3ClientPort_GetObject_Call{Call: _e.mock.On("GetObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_GetObject_Call) Run(run func(ctx context.Context, input *s3.GetObjectInput, opts ...func(*s3.Options))) *S3ClientPort_GetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.GetObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.GetObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_GetObject_Call) Return(getObjectOutput *s3.GetObjectOutput, err error) *S3ClientPort_GetObject_Call {
	_c.Call.Return(getObjectOutput, err)
	return _c
}

func (_c *S3ClientPort_GetObject_Call) RunAndReturn(run func(ctx context.Context, input *s3.GetObjectInput, opts ...func(*s3.Options)) (*s3.GetObjectOutput, error)) *S3ClientPort_GetObject_Call {
	_c.Call.Return(run)
	return _c
}

// HeadBucket provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) HeadBucket(ctx context.Context, input *s3.HeadBucketInput, opts ...func(*s3.Options)) (*s3.HeadBucketOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadBucket")
	}

	var r0 *s3.HeadBucketOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) (*s3.HeadBucketOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) *s3.HeadBucketOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadBucketOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadBucketInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_HeadBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadBucket'
type S3ClientPort_HeadBucket_Call struct {
	*mock.Call
}

// HeadBucket is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.HeadBucketInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) HeadBucket(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_HeadBucket_Call {
	return &S3ClientPort_HeadBucket_Call{Call: _e.mock.On("HeadBucket",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_HeadBucket_Call) Run(run func(ctx context.Context, input *s3.HeadBucketInput, opts ...func(*s3.Options))) *S3ClientPort_HeadBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.HeadBucketInput
		if args[1] != nil {
			arg1 = args[1].(*s3.HeadBucketInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_HeadBucket_Call) Return(headBucketOutput *s3.HeadBucketOutput, err error) *S3ClientPort_HeadBucket_Call {
	_c.Call.Return(headBucketOutput, err)
	return _c
}

func (_c *S3ClientPort_HeadBucket_Call) RunAndReturn(run func(ctx context.Context, input *s3.HeadBucketInput, opts ...func(*s3.Options)) (*s3.HeadBucketOutput, error)) *S3ClientPort_HeadBucket_Call {
	_c.Call.Return(run)
	return _c
}

// HeadObject provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) HeadObject(ctx context.Context, input *s3.HeadObjectInput, opts ...func(*s3.Options)) (*s3.HeadObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *s3.HeadObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) (*s3.HeadObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) *s3.HeadObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.HeadObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.HeadObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_HeadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadObject'
type S3ClientPort_HeadObject_Call struct {
	*mock.Call
}

// HeadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.HeadObjectInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) HeadObject(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_HeadObject_Call {
	return &S3ClientPort_HeadObject_Call{Call: _e.mock.On("HeadObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_HeadObject_Call) Run(run func(ctx context.Context, input *s3.HeadObjectInput, opts ...func(*s3.Options))) *S3ClientPort_HeadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.HeadObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.HeadObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_HeadObject_Call) Return(headObjectOutput *s3.HeadObjectOutput, err error) *S3ClientPort_HeadObject_Call {
	_c.Call.Return(headObjectOutput, err)
	return _c
}

func (_c *S3ClientPort_HeadObject_Call) RunAndReturn(run func(ctx context.Context, input *s3.HeadObjectInput, opts ...func(*s3.Options)) (*s3.HeadObjectOutput, error)) *S3ClientPort_HeadObject_Call {
	_c.Call.Return(run)
	return _c
}

// ListBuckets provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) ListBuckets(ctx context.Context, input *s3.ListBucketsInput, opts ...func(*s3.Options)) (*s3.ListBucketsOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListBuckets")
	}

	var r0 *s3.ListBucketsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListBucketsInput, ...func(*s3.Options)) (*s3.ListBucketsOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListBucketsInput, ...func(*s3.Options)) *s3.ListBucketsOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListBucketsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListBucketsInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_ListBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBuckets'
type S3ClientPort_ListBuckets_Call struct {
	*mock.Call
}

// ListBuckets is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.ListBucketsInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) ListBuckets(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_ListBuckets_Call {
	return &S3ClientPort_ListBuckets_Call{Call: _e.mock.On("ListBuckets",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_ListBuckets_Call) Run(run func(ctx context.Context, input *s3.ListBucketsInput, opts ...func(*s3.Options))) *S3ClientPort_ListBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.ListBucketsInput
		if args[1] != nil {
			arg1 = args[1].(*s3.ListBucketsInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_ListBuckets_Call) Return(listBucketsOutput *s3.ListBucketsOutput, err error) *S3ClientPort_ListBuckets_Call {
	_c.Call.Return(listBucketsOutput, err)
	return _c
}

func (_c *S3ClientPort_ListBuckets_Call) RunAndReturn(run func(ctx context.Context, input *s3.ListBucketsInput, opts ...func(*s3.Options)) (*s3.ListBucketsOutput, error)) *S3ClientPort_ListBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// ListObjectsV2 provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) ListObjectsV2(ctx context.Context, input *s3.ListObjectsV2Input, opts ...func(*s3.Options)) (*s3.ListObjectsV2Output, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListObjectsV2")
	}

	var r0 *s3.ListObjectsV2Output
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) *s3.ListObjectsV2Output); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.ListObjectsV2Output)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.ListObjectsV2Input, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_ListObjectsV2_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListObjectsV2'
type S3ClientPort_ListObjectsV2_Call struct {
	*mock.Call
}

// ListObjectsV2 is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.ListObjectsV2Input
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) ListObjectsV2(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_ListObjectsV2_Call {
	return &S3ClientPort_ListObjectsV2_Call{Call: _e.mock.On("ListObjectsV2",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_ListObjectsV2_Call) Run(run func(ctx context.Context, input *s3.ListObjectsV2Input, opts ...func(*s3.Options))) *S3ClientPort_ListObjectsV2_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.ListObjectsV2Input
		if args[1] != nil {
			arg1 = args[1].(*s3.ListObjectsV2Input)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_ListObjectsV2_Call) Return(listObjectsV2Output *s3.ListObjectsV2Output, err error) *S3ClientPort_ListObjectsV2_Call {
	_c.Call.Return(listObjectsV2Output, err)
	return _c
}

func (_c *S3ClientPort_ListObjectsV2_Call) RunAndReturn(run func(ctx context.Context, input *s3.ListObjectsV2Input, opts ...func(*s3.Options)) (*s3.ListObjectsV2Output, error)) *S3ClientPort_ListObjectsV2_Call {
	_c.Call.Return(run)
	return _c
}

// PutObject provides a mock function for the type S3ClientPort
func (_mock *S3ClientPort) PutObject(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options)) (*s3.PutObjectOutput, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, input, opts)
	} else {
		tmpRet = _mock.Called(ctx, input)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for PutObject")
	}

	var r0 *s3.PutObjectOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) (*s3.PutObjectOutput, error)); ok {
		return returnFunc(ctx, input, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) *s3.PutObjectOutput); ok {
		r0 = returnFunc(ctx, input, opts...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*s3.PutObjectOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *s3.PutObjectInput, ...func(*s3.Options)) error); ok {
		r1 = returnFunc(ctx, input, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// S3ClientPort_PutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutObject'
type S3ClientPort_PutObject_Call struct {
	*mock.Call
}

// PutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - input *s3.PutObjectInput
//   - opts ...func(*s3.Options)
func (_e *S3ClientPort_Expecter) PutObject(ctx interface{}, input interface{}, opts ...interface{}) *S3ClientPort_PutObject_Call {
	return &S3ClientPort_PutObject_Call{Call: _e.mock.On("PutObject",
		append([]interface{}{ctx, input}, opts...)...)}
}

func (_c *S3ClientPort_PutObject_Call) Run(run func(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options))) *S3ClientPort_PutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *s3.PutObjectInput
		if args[1] != nil {
			arg1 = args[1].(*s3.PutObjectInput)
		}
		var arg2 []func(*s3.Options)
		var variadicArgs []func(*s3.Options)
		if len(args) > 2 {
			variadicArgs = args[2].([]func(*s3.Options))
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *S3ClientPort_PutObject_Call) Return(putObjectOutput *s3.PutObjectOutput, err error) *S3ClientPort_PutObject_Call {
	_c.Call.Return(putObjectOutput, err)
	return _c
}

func (_c *S3ClientPort_PutObject_Call) RunAndReturn(run func(ctx context.Context, input *s3.PutObjectInput, opts ...func(*s3.Options)) (*s3.PutObjectOutput, error)) *S3ClientPort_PutObject_Call {
	_c.Call.Return(run)
	return _c
}
