// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/secretsmanager"
	mock "github.com/stretchr/testify/mock"
)

// NewSecretsManagerPort creates a new instance of SecretsManagerPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSecretsManagerPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SecretsManagerPort {
	mock := &SecretsManagerPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SecretsManagerPort is an autogenerated mock type for the SecretsManagerPort type
type SecretsManagerPort struct {
	mock.Mock
}

type SecretsManagerPort_Expecter struct {
	mock *mock.Mock
}

func (_m *SecretsManagerPort) EXPECT() *SecretsManagerPort_Expecter {
	return &SecretsManagerPort_Expecter{mock: &_m.Mock}
}

// CreateSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) CreateSecret(ctx context.Context, input *secretsmanager.CreateSecretInput) (*secretsmanager.CreateSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateSecret")
	}

	var r0 *secretsmanager.CreateSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.CreateSecretInput) (*secretsmanager.CreateSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.CreateSecretInput) *secretsmanager.CreateSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.CreateSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.CreateSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_CreateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSecret'
type SecretsManagerPort_CreateSecret_Call struct {
	*mock.Call
}

// CreateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.CreateSecretInput
func (_e *SecretsManagerPort_Expecter) CreateSecret(ctx interface{}, input interface{}) *SecretsManagerPort_CreateSecret_Call {
	return &SecretsManagerPort_CreateSecret_Call{Call: _e.mock.On("CreateSecret", ctx, input)}
}

func (_c *SecretsManagerPort_CreateSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.CreateSecretInput)) *SecretsManagerPort_CreateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.CreateSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.CreateSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_CreateSecret_Call) Return(createSecretOutput *secretsmanager.CreateSecretOutput, err error) *SecretsManagerPort_CreateSecret_Call {
	_c.Call.Return(createSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_CreateSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.CreateSecretInput) (*secretsmanager.CreateSecretOutput, error)) *SecretsManagerPort_CreateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) DeleteSecret(ctx context.Context, input *secretsmanager.DeleteSecretInput) (*secretsmanager.DeleteSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSecret")
	}

	var r0 *secretsmanager.DeleteSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.DeleteSecretInput) (*secretsmanager.DeleteSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.DeleteSecretInput) *secretsmanager.DeleteSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.DeleteSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.DeleteSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_DeleteSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSecret'
type SecretsManagerPort_DeleteSecret_Call struct {
	*mock.Call
}

// DeleteSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.DeleteSecretInput
func (_e *SecretsManagerPort_Expecter) DeleteSecret(ctx interface{}, input interface{}) *SecretsManagerPort_DeleteSecret_Call {
	return &SecretsManagerPort_DeleteSecret_Call{Call: _e.mock.On("DeleteSecret", ctx, input)}
}

func (_c *SecretsManagerPort_DeleteSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.DeleteSecretInput)) *SecretsManagerPort_DeleteSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.DeleteSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.DeleteSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_DeleteSecret_Call) Return(deleteSecretOutput *secretsmanager.DeleteSecretOutput, err error) *SecretsManagerPort_DeleteSecret_Call {
	_c.Call.Return(deleteSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_DeleteSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.DeleteSecretInput) (*secretsmanager.DeleteSecretOutput, error)) *SecretsManagerPort_DeleteSecret_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) DescribeSecret(ctx context.Context, input *secretsmanager.DescribeSecretInput) (*secretsmanager.DescribeSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeSecret")
	}

	var r0 *secretsmanager.DescribeSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.DescribeSecretInput) (*secretsmanager.DescribeSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.DescribeSecretInput) *secretsmanager.DescribeSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.DescribeSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.DescribeSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_DescribeSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeSecret'
type SecretsManagerPort_DescribeSecret_Call struct {
	*mock.Call
}

// DescribeSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.DescribeSecretInput
func (_e *SecretsManagerPort_Expecter) DescribeSecret(ctx interface{}, input interface{}) *SecretsManagerPort_DescribeSecret_Call {
	return &SecretsManagerPort_DescribeSecret_Call{Call: _e.mock.On("DescribeSecret", ctx, input)}
}

func (_c *SecretsManagerPort_DescribeSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.DescribeSecretInput)) *SecretsManagerPort_DescribeSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.DescribeSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.DescribeSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_DescribeSecret_Call) Return(describeSecretOutput *secretsmanager.DescribeSecretOutput, err error) *SecretsManagerPort_DescribeSecret_Call {
	_c.Call.Return(describeSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_DescribeSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.DescribeSecretInput) (*secretsmanager.DescribeSecretOutput, error)) *SecretsManagerPort_DescribeSecret_Call {
	_c.Call.Return(run)
	return _c
}

// GetRandomPassword provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) GetRandomPassword(ctx context.Context, input *secretsmanager.GetRandomPasswordInput) (*secretsmanager.GetRandomPasswordOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetRandomPassword")
	}

	var r0 *secretsmanager.GetRandomPasswordOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetRandomPasswordInput) (*secretsmanager.GetRandomPasswordOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetRandomPasswordInput) *secretsmanager.GetRandomPasswordOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetRandomPasswordOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.GetRandomPasswordInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_GetRandomPassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRandomPassword'
type SecretsManagerPort_GetRandomPassword_Call struct {
	*mock.Call
}

// GetRandomPassword is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.GetRandomPasswordInput
func (_e *SecretsManagerPort_Expecter) GetRandomPassword(ctx interface{}, input interface{}) *SecretsManagerPort_GetRandomPassword_Call {
	return &SecretsManagerPort_GetRandomPassword_Call{Call: _e.mock.On("GetRandomPassword", ctx, input)}
}

func (_c *SecretsManagerPort_GetRandomPassword_Call) Run(run func(ctx context.Context, input *secretsmanager.GetRandomPasswordInput)) *SecretsManagerPort_GetRandomPassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.GetRandomPasswordInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.GetRandomPasswordInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_GetRandomPassword_Call) Return(getRandomPasswordOutput *secretsmanager.GetRandomPasswordOutput, err error) *SecretsManagerPort_GetRandomPassword_Call {
	_c.Call.Return(getRandomPasswordOutput, err)
	return _c
}

func (_c *SecretsManagerPort_GetRandomPassword_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.GetRandomPasswordInput) (*secretsmanager.GetRandomPasswordOutput, error)) *SecretsManagerPort_GetRandomPassword_Call {
	_c.Call.Return(run)
	return _c
}

// GetSecretValue provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) GetSecretValue(ctx context.Context, input *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetSecretValue")
	}

	var r0 *secretsmanager.GetSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.GetSecretValueInput) *secretsmanager.GetSecretValueOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.GetSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.GetSecretValueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_GetSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSecretValue'
type SecretsManagerPort_GetSecretValue_Call struct {
	*mock.Call
}

// GetSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.GetSecretValueInput
func (_e *SecretsManagerPort_Expecter) GetSecretValue(ctx interface{}, input interface{}) *SecretsManagerPort_GetSecretValue_Call {
	return &SecretsManagerPort_GetSecretValue_Call{Call: _e.mock.On("GetSecretValue", ctx, input)}
}

func (_c *SecretsManagerPort_GetSecretValue_Call) Run(run func(ctx context.Context, input *secretsmanager.GetSecretValueInput)) *SecretsManagerPort_GetSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.GetSecretValueInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.GetSecretValueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_GetSecretValue_Call) Return(getSecretValueOutput *secretsmanager.GetSecretValueOutput, err error) *SecretsManagerPort_GetSecretValue_Call {
	_c.Call.Return(getSecretValueOutput, err)
	return _c
}

func (_c *SecretsManagerPort_GetSecretValue_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.GetSecretValueInput) (*secretsmanager.GetSecretValueOutput, error)) *SecretsManagerPort_GetSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// ListSecrets provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) ListSecrets(ctx context.Context, input *secretsmanager.ListSecretsInput) (*secretsmanager.ListSecretsOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListSecrets")
	}

	var r0 *secretsmanager.ListSecretsOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.ListSecretsInput) (*secretsmanager.ListSecretsOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.ListSecretsInput) *secretsmanager.ListSecretsOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.ListSecretsOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.ListSecretsInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_ListSecrets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSecrets'
type SecretsManagerPort_ListSecrets_Call struct {
	*mock.Call
}

// ListSecrets is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.ListSecretsInput
func (_e *SecretsManagerPort_Expecter) ListSecrets(ctx interface{}, input interface{}) *SecretsManagerPort_ListSecrets_Call {
	return &SecretsManagerPort_ListSecrets_Call{Call: _e.mock.On("ListSecrets", ctx, input)}
}

func (_c *SecretsManagerPort_ListSecrets_Call) Run(run func(ctx context.Context, input *secretsmanager.ListSecretsInput)) *SecretsManagerPort_ListSecrets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.ListSecretsInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.ListSecretsInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_ListSecrets_Call) Return(listSecretsOutput *secretsmanager.ListSecretsOutput, err error) *SecretsManagerPort_ListSecrets_Call {
	_c.Call.Return(listSecretsOutput, err)
	return _c
}

func (_c *SecretsManagerPort_ListSecrets_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.ListSecretsInput) (*secretsmanager.ListSecretsOutput, error)) *SecretsManagerPort_ListSecrets_Call {
	_c.Call.Return(run)
	return _c
}

// PutSecretValue provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) PutSecretValue(ctx context.Context, input *secretsmanager.PutSecretValueInput) (*secretsmanager.PutSecretValueOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutSecretValue")
	}

	var r0 *secretsmanager.PutSecretValueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.PutSecretValueInput) (*secretsmanager.PutSecretValueOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.PutSecretValueInput) *secretsmanager.PutSecretValueOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.PutSecretValueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.PutSecretValueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_PutSecretValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutSecretValue'
type SecretsManagerPort_PutSecretValue_Call struct {
	*mock.Call
}

// PutSecretValue is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.PutSecretValueInput
func (_e *SecretsManagerPort_Expecter) PutSecretValue(ctx interface{}, input interface{}) *SecretsManagerPort_PutSecretValue_Call {
	return &SecretsManagerPort_PutSecretValue_Call{Call: _e.mock.On("PutSecretValue", ctx, input)}
}

func (_c *SecretsManagerPort_PutSecretValue_Call) Run(run func(ctx context.Context, input *secretsmanager.PutSecretValueInput)) *SecretsManagerPort_PutSecretValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.PutSecretValueInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.PutSecretValueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_PutSecretValue_Call) Return(putSecretValueOutput *secretsmanager.PutSecretValueOutput, err error) *SecretsManagerPort_PutSecretValue_Call {
	_c.Call.Return(putSecretValueOutput, err)
	return _c
}

func (_c *SecretsManagerPort_PutSecretValue_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.PutSecretValueInput) (*secretsmanager.PutSecretValueOutput, error)) *SecretsManagerPort_PutSecretValue_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) RestoreSecret(ctx context.Context, input *secretsmanager.RestoreSecretInput) (*secretsmanager.RestoreSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RestoreSecret")
	}

	var r0 *secretsmanager.RestoreSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.RestoreSecretInput) (*secretsmanager.RestoreSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.RestoreSecretInput) *secretsmanager.RestoreSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.RestoreSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.RestoreSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_RestoreSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreSecret'
type SecretsManagerPort_RestoreSecret_Call struct {
	*mock.Call
}

// RestoreSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.RestoreSecretInput
func (_e *SecretsManagerPort_Expecter) RestoreSecret(ctx interface{}, input interface{}) *SecretsManagerPort_RestoreSecret_Call {
	return &SecretsManagerPort_RestoreSecret_Call{Call: _e.mock.On("RestoreSecret", ctx, input)}
}

func (_c *SecretsManagerPort_RestoreSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.RestoreSecretInput)) *SecretsManagerPort_RestoreSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.RestoreSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.RestoreSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_RestoreSecret_Call) Return(restoreSecretOutput *secretsmanager.RestoreSecretOutput, err error) *SecretsManagerPort_RestoreSecret_Call {
	_c.Call.Return(restoreSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_RestoreSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.RestoreSecretInput) (*secretsmanager.RestoreSecretOutput, error)) *SecretsManagerPort_RestoreSecret_Call {
	_c.Call.Return(run)
	return _c
}

// RotateSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) RotateSecret(ctx context.Context, input *secretsmanager.RotateSecretInput) (*secretsmanager.RotateSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RotateSecret")
	}

	var r0 *secretsmanager.RotateSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.RotateSecretInput) (*secretsmanager.RotateSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.RotateSecretInput) *secretsmanager.RotateSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.RotateSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.RotateSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_RotateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RotateSecret'
type SecretsManagerPort_RotateSecret_Call struct {
	*mock.Call
}

// RotateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.RotateSecretInput
func (_e *SecretsManagerPort_Expecter) RotateSecret(ctx interface{}, input interface{}) *SecretsManagerPort_RotateSecret_Call {
	return &SecretsManagerPort_RotateSecret_Call{Call: _e.mock.On("RotateSecret", ctx, input)}
}

func (_c *SecretsManagerPort_RotateSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.RotateSecretInput)) *SecretsManagerPort_RotateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.RotateSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.RotateSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_RotateSecret_Call) Return(rotateSecretOutput *secretsmanager.RotateSecretOutput, err error) *SecretsManagerPort_RotateSecret_Call {
	_c.Call.Return(rotateSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_RotateSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.RotateSecretInput) (*secretsmanager.RotateSecretOutput, error)) *SecretsManagerPort_RotateSecret_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSecret provides a mock function for the type SecretsManagerPort
func (_mock *SecretsManagerPort) UpdateSecret(ctx context.Context, input *secretsmanager.UpdateSecretInput) (*secretsmanager.UpdateSecretOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSecret")
	}

	var r0 *secretsmanager.UpdateSecretOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.UpdateSecretInput) (*secretsmanager.UpdateSecretOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *secretsmanager.UpdateSecretInput) *secretsmanager.UpdateSecretOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*secretsmanager.UpdateSecretOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *secretsmanager.UpdateSecretInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SecretsManagerPort_UpdateSecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSecret'
type SecretsManagerPort_UpdateSecret_Call struct {
	*mock.Call
}

// UpdateSecret is a helper method to define mock.On call
//   - ctx context.Context
//   - input *secretsmanager.UpdateSecretInput
func (_e *SecretsManagerPort_Expecter) UpdateSecret(ctx interface{}, input interface{}) *SecretsManagerPort_UpdateSecret_Call {
	return &SecretsManagerPort_UpdateSecret_Call{Call: _e.mock.On("UpdateSecret", ctx, input)}
}

func (_c *SecretsManagerPort_UpdateSecret_Call) Run(run func(ctx context.Context, input *secretsmanager.UpdateSecretInput)) *SecretsManagerPort_UpdateSecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *secretsmanager.UpdateSecretInput
		if args[1] != nil {
			arg1 = args[1].(*secretsmanager.UpdateSecretInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SecretsManagerPort_UpdateSecret_Call) Return(updateSecretOutput *secretsmanager.UpdateSecretOutput, err error) *SecretsManagerPort_UpdateSecret_Call {
	_c.Call.Return(updateSecretOutput, err)
	return _c
}

func (_c *SecretsManagerPort_UpdateSecret_Call) RunAndReturn(run func(ctx context.Context, input *secretsmanager.UpdateSecretInput) (*secretsmanager.UpdateSecretOutput, error)) *SecretsManagerPort_UpdateSecret_Call {
	_c.Call.Return(run)
	return _c
}
