// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/sqs"
	mock "github.com/stretchr/testify/mock"
)

// NewSQSPort creates a new instance of SQSPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSQSPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SQSPort {
	mock := &SQSPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SQSPort is an autogenerated mock type for the SQSPort type
type SQSPort struct {
	mock.Mock
}

type SQSPort_Expecter struct {
	mock *mock.Mock
}

func (_m *SQSPort) EXPECT() *SQSPort_Expecter {
	return &SQSPort_Expecter{mock: &_m.Mock}
}

// CreateQueue provides a mock function for the type SQSPort
func (_mock *SQSPort) CreateQueue(ctx context.Context, input *sqs.CreateQueueInput) (*sqs.CreateQueueOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for CreateQueue")
	}

	var r0 *sqs.CreateQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.CreateQueueInput) (*sqs.CreateQueueOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.CreateQueueInput) *sqs.CreateQueueOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.CreateQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.CreateQueueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_CreateQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateQueue'
type SQSPort_CreateQueue_Call struct {
	*mock.Call
}

// CreateQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.CreateQueueInput
func (_e *SQSPort_Expecter) CreateQueue(ctx interface{}, input interface{}) *SQSPort_CreateQueue_Call {
	return &SQSPort_CreateQueue_Call{Call: _e.mock.On("CreateQueue", ctx, input)}
}

func (_c *SQSPort_CreateQueue_Call) Run(run func(ctx context.Context, input *sqs.CreateQueueInput)) *SQSPort_CreateQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.CreateQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.CreateQueueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_CreateQueue_Call) Return(createQueueOutput *sqs.CreateQueueOutput, err error) *SQSPort_CreateQueue_Call {
	_c.Call.Return(createQueueOutput, err)
	return _c
}

func (_c *SQSPort_CreateQueue_Call) RunAndReturn(run func(ctx context.Context, input *sqs.CreateQueueInput) (*sqs.CreateQueueOutput, error)) *SQSPort_CreateQueue_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteMessage provides a mock function for the type SQSPort
func (_mock *SQSPort) DeleteMessage(ctx context.Context, input *sqs.DeleteMessageInput) (*sqs.DeleteMessageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteMessage")
	}

	var r0 *sqs.DeleteMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput) (*sqs.DeleteMessageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteMessageInput) *sqs.DeleteMessageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.DeleteMessageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_DeleteMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteMessage'
type SQSPort_DeleteMessage_Call struct {
	*mock.Call
}

// DeleteMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.DeleteMessageInput
func (_e *SQSPort_Expecter) DeleteMessage(ctx interface{}, input interface{}) *SQSPort_DeleteMessage_Call {
	return &SQSPort_DeleteMessage_Call{Call: _e.mock.On("DeleteMessage", ctx, input)}
}

func (_c *SQSPort_DeleteMessage_Call) Run(run func(ctx context.Context, input *sqs.DeleteMessageInput)) *SQSPort_DeleteMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.DeleteMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.DeleteMessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_DeleteMessage_Call) Return(deleteMessageOutput *sqs.DeleteMessageOutput, err error) *SQSPort_DeleteMessage_Call {
	_c.Call.Return(deleteMessageOutput, err)
	return _c
}

func (_c *SQSPort_DeleteMessage_Call) RunAndReturn(run func(ctx context.Context, input *sqs.DeleteMessageInput) (*sqs.DeleteMessageOutput, error)) *SQSPort_DeleteMessage_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteQueue provides a mock function for the type SQSPort
func (_mock *SQSPort) DeleteQueue(ctx context.Context, input *sqs.DeleteQueueInput) (*sqs.DeleteQueueOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteQueue")
	}

	var r0 *sqs.DeleteQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteQueueInput) (*sqs.DeleteQueueOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.DeleteQueueInput) *sqs.DeleteQueueOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.DeleteQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.DeleteQueueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_DeleteQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteQueue'
type SQSPort_DeleteQueue_Call struct {
	*mock.Call
}

// DeleteQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.DeleteQueueInput
func (_e *SQSPort_Expecter) DeleteQueue(ctx interface{}, input interface{}) *SQSPort_DeleteQueue_Call {
	return &SQSPort_DeleteQueue_Call{Call: _e.mock.On("DeleteQueue", ctx, input)}
}

func (_c *SQSPort_DeleteQueue_Call) Run(run func(ctx context.Context, input *sqs.DeleteQueueInput)) *SQSPort_DeleteQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.DeleteQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.DeleteQueueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_DeleteQueue_Call) Return(deleteQueueOutput *sqs.DeleteQueueOutput, err error) *SQSPort_DeleteQueue_Call {
	_c.Call.Return(deleteQueueOutput, err)
	return _c
}

func (_c *SQSPort_DeleteQueue_Call) RunAndReturn(run func(ctx context.Context, input *sqs.DeleteQueueInput) (*sqs.DeleteQueueOutput, error)) *SQSPort_DeleteQueue_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueAttributes provides a mock function for the type SQSPort
func (_mock *SQSPort) GetQueueAttributes(ctx context.Context, input *sqs.GetQueueAttributesInput) (*sqs.GetQueueAttributesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueAttributes")
	}

	var r0 *sqs.GetQueueAttributesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueAttributesInput) (*sqs.GetQueueAttributesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueAttributesInput) *sqs.GetQueueAttributesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.GetQueueAttributesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.GetQueueAttributesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_GetQueueAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueAttributes'
type SQSPort_GetQueueAttributes_Call struct {
	*mock.Call
}

// GetQueueAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.GetQueueAttributesInput
func (_e *SQSPort_Expecter) GetQueueAttributes(ctx interface{}, input interface{}) *SQSPort_GetQueueAttributes_Call {
	return &SQSPort_GetQueueAttributes_Call{Call: _e.mock.On("GetQueueAttributes", ctx, input)}
}

func (_c *SQSPort_GetQueueAttributes_Call) Run(run func(ctx context.Context, input *sqs.GetQueueAttributesInput)) *SQSPort_GetQueueAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.GetQueueAttributesInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.GetQueueAttributesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_GetQueueAttributes_Call) Return(getQueueAttributesOutput *sqs.GetQueueAttributesOutput, err error) *SQSPort_GetQueueAttributes_Call {
	_c.Call.Return(getQueueAttributesOutput, err)
	return _c
}

func (_c *SQSPort_GetQueueAttributes_Call) RunAndReturn(run func(ctx context.Context, input *sqs.GetQueueAttributesInput) (*sqs.GetQueueAttributesOutput, error)) *SQSPort_GetQueueAttributes_Call {
	_c.Call.Return(run)
	return _c
}

// GetQueueUrl provides a mock function for the type SQSPort
func (_mock *SQSPort) GetQueueUrl(ctx context.Context, input *sqs.GetQueueUrlInput) (*sqs.GetQueueUrlOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetQueueUrl")
	}

	var r0 *sqs.GetQueueUrlOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueUrlInput) (*sqs.GetQueueUrlOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.GetQueueUrlInput) *sqs.GetQueueUrlOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.GetQueueUrlOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.GetQueueUrlInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_GetQueueUrl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQueueUrl'
type SQSPort_GetQueueUrl_Call struct {
	*mock.Call
}

// GetQueueUrl is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.GetQueueUrlInput
func (_e *SQSPort_Expecter) GetQueueUrl(ctx interface{}, input interface{}) *SQSPort_GetQueueUrl_Call {
	return &SQSPort_GetQueueUrl_Call{Call: _e.mock.On("GetQueueUrl", ctx, input)}
}

func (_c *SQSPort_GetQueueUrl_Call) Run(run func(ctx context.Context, input *sqs.GetQueueUrlInput)) *SQSPort_GetQueueUrl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.GetQueueUrlInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.GetQueueUrlInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_GetQueueUrl_Call) Return(getQueueUrlOutput *sqs.GetQueueUrlOutput, err error) *SQSPort_GetQueueUrl_Call {
	_c.Call.Return(getQueueUrlOutput, err)
	return _c
}

func (_c *SQSPort_GetQueueUrl_Call) RunAndReturn(run func(ctx context.Context, input *sqs.GetQueueUrlInput) (*sqs.GetQueueUrlOutput, error)) *SQSPort_GetQueueUrl_Call {
	_c.Call.Return(run)
	return _c
}

// ListQueues provides a mock function for the type SQSPort
func (_mock *SQSPort) ListQueues(ctx context.Context, input *sqs.ListQueuesInput) (*sqs.ListQueuesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListQueues")
	}

	var r0 *sqs.ListQueuesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueuesInput) (*sqs.ListQueuesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ListQueuesInput) *sqs.ListQueuesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ListQueuesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ListQueuesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_ListQueues_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListQueues'
type SQSPort_ListQueues_Call struct {
	*mock.Call
}

// ListQueues is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.ListQueuesInput
func (_e *SQSPort_Expecter) ListQueues(ctx interface{}, input interface{}) *SQSPort_ListQueues_Call {
	return &SQSPort_ListQueues_Call{Call: _e.mock.On("ListQueues", ctx, input)}
}

func (_c *SQSPort_ListQueues_Call) Run(run func(ctx context.Context, input *sqs.ListQueuesInput)) *SQSPort_ListQueues_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ListQueuesInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ListQueuesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_ListQueues_Call) Return(listQueuesOutput *sqs.ListQueuesOutput, err error) *SQSPort_ListQueues_Call {
	_c.Call.Return(listQueuesOutput, err)
	return _c
}

func (_c *SQSPort_ListQueues_Call) RunAndReturn(run func(ctx context.Context, input *sqs.ListQueuesInput) (*sqs.ListQueuesOutput, error)) *SQSPort_ListQueues_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeQueue provides a mock function for the type SQSPort
func (_mock *SQSPort) PurgeQueue(ctx context.Context, input *sqs.PurgeQueueInput) (*sqs.PurgeQueueOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PurgeQueue")
	}

	var r0 *sqs.PurgeQueueOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.PurgeQueueInput) (*sqs.PurgeQueueOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.PurgeQueueInput) *sqs.PurgeQueueOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.PurgeQueueOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.PurgeQueueInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_PurgeQueue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeQueue'
type SQSPort_PurgeQueue_Call struct {
	*mock.Call
}

// PurgeQueue is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.PurgeQueueInput
func (_e *SQSPort_Expecter) PurgeQueue(ctx interface{}, input interface{}) *SQSPort_PurgeQueue_Call {
	return &SQSPort_PurgeQueue_Call{Call: _e.mock.On("PurgeQueue", ctx, input)}
}

func (_c *SQSPort_PurgeQueue_Call) Run(run func(ctx context.Context, input *sqs.PurgeQueueInput)) *SQSPort_PurgeQueue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.PurgeQueueInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.PurgeQueueInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_PurgeQueue_Call) Return(purgeQueueOutput *sqs.PurgeQueueOutput, err error) *SQSPort_PurgeQueue_Call {
	_c.Call.Return(purgeQueueOutput, err)
	return _c
}

func (_c *SQSPort_PurgeQueue_Call) RunAndReturn(run func(ctx context.Context, input *sqs.PurgeQueueInput) (*sqs.PurgeQueueOutput, error)) *SQSPort_PurgeQueue_Call {
	_c.Call.Return(run)
	return _c
}

// ReceiveMessage provides a mock function for the type SQSPort
func (_mock *SQSPort) ReceiveMessage(ctx context.Context, input *sqs.ReceiveMessageInput) (*sqs.ReceiveMessageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ReceiveMessage")
	}

	var r0 *sqs.ReceiveMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput) (*sqs.ReceiveMessageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.ReceiveMessageInput) *sqs.ReceiveMessageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.ReceiveMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.ReceiveMessageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_ReceiveMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReceiveMessage'
type SQSPort_ReceiveMessage_Call struct {
	*mock.Call
}

// ReceiveMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.ReceiveMessageInput
func (_e *SQSPort_Expecter) ReceiveMessage(ctx interface{}, input interface{}) *SQSPort_ReceiveMessage_Call {
	return &SQSPort_ReceiveMessage_Call{Call: _e.mock.On("ReceiveMessage", ctx, input)}
}

func (_c *SQSPort_ReceiveMessage_Call) Run(run func(ctx context.Context, input *sqs.ReceiveMessageInput)) *SQSPort_ReceiveMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.ReceiveMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.ReceiveMessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_ReceiveMessage_Call) Return(receiveMessageOutput *sqs.ReceiveMessageOutput, err error) *SQSPort_ReceiveMessage_Call {
	_c.Call.Return(receiveMessageOutput, err)
	return _c
}

func (_c *SQSPort_ReceiveMessage_Call) RunAndReturn(run func(ctx context.Context, input *sqs.ReceiveMessageInput) (*sqs.ReceiveMessageOutput, error)) *SQSPort_ReceiveMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function for the type SQSPort
func (_mock *SQSPort) SendMessage(ctx context.Context, input *sqs.SendMessageInput) (*sqs.SendMessageOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 *sqs.SendMessageOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput) (*sqs.SendMessageOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SendMessageInput) *sqs.SendMessageOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SendMessageOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SendMessageInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type SQSPort_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.SendMessageInput
func (_e *SQSPort_Expecter) SendMessage(ctx interface{}, input interface{}) *SQSPort_SendMessage_Call {
	return &SQSPort_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, input)}
}

func (_c *SQSPort_SendMessage_Call) Run(run func(ctx context.Context, input *sqs.SendMessageInput)) *SQSPort_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SendMessageInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SendMessageInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_SendMessage_Call) Return(sendMessageOutput *sqs.SendMessageOutput, err error) *SQSPort_SendMessage_Call {
	_c.Call.Return(sendMessageOutput, err)
	return _c
}

func (_c *SQSPort_SendMessage_Call) RunAndReturn(run func(ctx context.Context, input *sqs.SendMessageInput) (*sqs.SendMessageOutput, error)) *SQSPort_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SetQueueAttributes provides a mock function for the type SQSPort
func (_mock *SQSPort) SetQueueAttributes(ctx context.Context, input *sqs.SetQueueAttributesInput) (*sqs.SetQueueAttributesOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SetQueueAttributes")
	}

	var r0 *sqs.SetQueueAttributesOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SetQueueAttributesInput) (*sqs.SetQueueAttributesOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqs.SetQueueAttributesInput) *sqs.SetQueueAttributesOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sqs.SetQueueAttributesOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *sqs.SetQueueAttributesInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SQSPort_SetQueueAttributes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetQueueAttributes'
type SQSPort_SetQueueAttributes_Call struct {
	*mock.Call
}

// SetQueueAttributes is a helper method to define mock.On call
//   - ctx context.Context
//   - input *sqs.SetQueueAttributesInput
func (_e *SQSPort_Expecter) SetQueueAttributes(ctx interface{}, input interface{}) *SQSPort_SetQueueAttributes_Call {
	return &SQSPort_SetQueueAttributes_Call{Call: _e.mock.On("SetQueueAttributes", ctx, input)}
}

func (_c *SQSPort_SetQueueAttributes_Call) Run(run func(ctx context.Context, input *sqs.SetQueueAttributesInput)) *SQSPort_SetQueueAttributes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqs.SetQueueAttributesInput
		if args[1] != nil {
			arg1 = args[1].(*sqs.SetQueueAttributesInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SQSPort_SetQueueAttributes_Call) Return(setQueueAttributesOutput *sqs.SetQueueAttributesOutput, err error) *SQSPort_SetQueueAttributes_Call {
	_c.Call.Return(setQueueAttributesOutput, err)
	return _c
}

func (_c *SQSPort_SetQueueAttributes_Call) RunAndReturn(run func(ctx context.Context, input *sqs.SetQueueAttributesInput) (*sqs.SetQueueAttributesOutput, error)) *SQSPort_SetQueueAttributes_Call {
	_c.Call.Return(run)
	return _c
}
