// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package ports

import (
	"context"

	"github.com/aws/aws-sdk-go-v2/service/ssm"
	mock "github.com/stretchr/testify/mock"
)

// NewSSMPort creates a new instance of SSMPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSSMPort(t interface {
	mock.TestingT
	Cleanup(func())
}) *SSMPort {
	mock := &SSMPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// SSMPort is an autogenerated mock type for the SSMPort type
type SSMPort struct {
	mock.Mock
}

type SSMPort_Expecter struct {
	mock *mock.Mock
}

func (_m *SSMPort) EXPECT() *SSMPort_Expecter {
	return &SSMPort_Expecter{mock: &_m.Mock}
}

// AddTagsToResource provides a mock function for the type SSMPort
func (_mock *SSMPort) AddTagsToResource(ctx context.Context, input *ssm.AddTagsToResourceInput) (*ssm.AddTagsToResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for AddTagsToResource")
	}

	var r0 *ssm.AddTagsToResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.AddTagsToResourceInput) (*ssm.AddTagsToResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.AddTagsToResourceInput) *ssm.AddTagsToResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.AddTagsToResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.AddTagsToResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_AddTagsToResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTagsToResource'
type SSMPort_AddTagsToResource_Call struct {
	*mock.Call
}

// AddTagsToResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.AddTagsToResourceInput
func (_e *SSMPort_Expecter) AddTagsToResource(ctx interface{}, input interface{}) *SSMPort_AddTagsToResource_Call {
	return &SSMPort_AddTagsToResource_Call{Call: _e.mock.On("AddTagsToResource", ctx, input)}
}

func (_c *SSMPort_AddTagsToResource_Call) Run(run func(ctx context.Context, input *ssm.AddTagsToResourceInput)) *SSMPort_AddTagsToResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.AddTagsToResourceInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.AddTagsToResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_AddTagsToResource_Call) Return(addTagsToResourceOutput *ssm.AddTagsToResourceOutput, err error) *SSMPort_AddTagsToResource_Call {
	_c.Call.Return(addTagsToResourceOutput, err)
	return _c
}

func (_c *SSMPort_AddTagsToResource_Call) RunAndReturn(run func(ctx context.Context, input *ssm.AddTagsToResourceInput) (*ssm.AddTagsToResourceOutput, error)) *SSMPort_AddTagsToResource_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteParameter provides a mock function for the type SSMPort
func (_mock *SSMPort) DeleteParameter(ctx context.Context, input *ssm.DeleteParameterInput) (*ssm.DeleteParameterOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DeleteParameter")
	}

	var r0 *ssm.DeleteParameterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.DeleteParameterInput) (*ssm.DeleteParameterOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.DeleteParameterInput) *ssm.DeleteParameterOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.DeleteParameterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.DeleteParameterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_DeleteParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteParameter'
type SSMPort_DeleteParameter_Call struct {
	*mock.Call
}

// DeleteParameter is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.DeleteParameterInput
func (_e *SSMPort_Expecter) DeleteParameter(ctx interface{}, input interface{}) *SSMPort_DeleteParameter_Call {
	return &SSMPort_DeleteParameter_Call{Call: _e.mock.On("DeleteParameter", ctx, input)}
}

func (_c *SSMPort_DeleteParameter_Call) Run(run func(ctx context.Context, input *ssm.DeleteParameterInput)) *SSMPort_DeleteParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.DeleteParameterInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.DeleteParameterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_DeleteParameter_Call) Return(deleteParameterOutput *ssm.DeleteParameterOutput, err error) *SSMPort_DeleteParameter_Call {
	_c.Call.Return(deleteParameterOutput, err)
	return _c
}

func (_c *SSMPort_DeleteParameter_Call) RunAndReturn(run func(ctx context.Context, input *ssm.DeleteParameterInput) (*ssm.DeleteParameterOutput, error)) *SSMPort_DeleteParameter_Call {
	_c.Call.Return(run)
	return _c
}

// DescribeParameters provides a mock function for the type SSMPort
func (_mock *SSMPort) DescribeParameters(ctx context.Context, input *ssm.DescribeParametersInput) (*ssm.DescribeParametersOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for DescribeParameters")
	}

	var r0 *ssm.DescribeParametersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.DescribeParametersInput) (*ssm.DescribeParametersOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.DescribeParametersInput) *ssm.DescribeParametersOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.DescribeParametersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.DescribeParametersInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_DescribeParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DescribeParameters'
type SSMPort_DescribeParameters_Call struct {
	*mock.Call
}

// DescribeParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.DescribeParametersInput
func (_e *SSMPort_Expecter) DescribeParameters(ctx interface{}, input interface{}) *SSMPort_DescribeParameters_Call {
	return &SSMPort_DescribeParameters_Call{Call: _e.mock.On("DescribeParameters", ctx, input)}
}

func (_c *SSMPort_DescribeParameters_Call) Run(run func(ctx context.Context, input *ssm.DescribeParametersInput)) *SSMPort_DescribeParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.DescribeParametersInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.DescribeParametersInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_DescribeParameters_Call) Return(describeParametersOutput *ssm.DescribeParametersOutput, err error) *SSMPort_DescribeParameters_Call {
	_c.Call.Return(describeParametersOutput, err)
	return _c
}

func (_c *SSMPort_DescribeParameters_Call) RunAndReturn(run func(ctx context.Context, input *ssm.DescribeParametersInput) (*ssm.DescribeParametersOutput, error)) *SSMPort_DescribeParameters_Call {
	_c.Call.Return(run)
	return _c
}

// GetParameter provides a mock function for the type SSMPort
func (_mock *SSMPort) GetParameter(ctx context.Context, input *ssm.GetParameterInput) (*ssm.GetParameterOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetParameter")
	}

	var r0 *ssm.GetParameterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput) (*ssm.GetParameterOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterInput) *ssm.GetParameterOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParameterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParameterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_GetParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameter'
type SSMPort_GetParameter_Call struct {
	*mock.Call
}

// GetParameter is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.GetParameterInput
func (_e *SSMPort_Expecter) GetParameter(ctx interface{}, input interface{}) *SSMPort_GetParameter_Call {
	return &SSMPort_GetParameter_Call{Call: _e.mock.On("GetParameter", ctx, input)}
}

func (_c *SSMPort_GetParameter_Call) Run(run func(ctx context.Context, input *ssm.GetParameterInput)) *SSMPort_GetParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParameterInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParameterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_GetParameter_Call) Return(getParameterOutput *ssm.GetParameterOutput, err error) *SSMPort_GetParameter_Call {
	_c.Call.Return(getParameterOutput, err)
	return _c
}

func (_c *SSMPort_GetParameter_Call) RunAndReturn(run func(ctx context.Context, input *ssm.GetParameterInput) (*ssm.GetParameterOutput, error)) *SSMPort_GetParameter_Call {
	_c.Call.Return(run)
	return _c
}

// GetParameterHistory provides a mock function for the type SSMPort
func (_mock *SSMPort) GetParameterHistory(ctx context.Context, input *ssm.GetParameterHistoryInput) (*ssm.GetParameterHistoryOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetParameterHistory")
	}

	var r0 *ssm.GetParameterHistoryOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterHistoryInput) (*ssm.GetParameterHistoryOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParameterHistoryInput) *ssm.GetParameterHistoryOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParameterHistoryOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParameterHistoryInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_GetParameterHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameterHistory'
type SSMPort_GetParameterHistory_Call struct {
	*mock.Call
}

// GetParameterHistory is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.GetParameterHistoryInput
func (_e *SSMPort_Expecter) GetParameterHistory(ctx interface{}, input interface{}) *SSMPort_GetParameterHistory_Call {
	return &SSMPort_GetParameterHistory_Call{Call: _e.mock.On("GetParameterHistory", ctx, input)}
}

func (_c *SSMPort_GetParameterHistory_Call) Run(run func(ctx context.Context, input *ssm.GetParameterHistoryInput)) *SSMPort_GetParameterHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParameterHistoryInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParameterHistoryInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_GetParameterHistory_Call) Return(getParameterHistoryOutput *ssm.GetParameterHistoryOutput, err error) *SSMPort_GetParameterHistory_Call {
	_c.Call.Return(getParameterHistoryOutput, err)
	return _c
}

func (_c *SSMPort_GetParameterHistory_Call) RunAndReturn(run func(ctx context.Context, input *ssm.GetParameterHistoryInput) (*ssm.GetParameterHistoryOutput, error)) *SSMPort_GetParameterHistory_Call {
	_c.Call.Return(run)
	return _c
}

// GetParameters provides a mock function for the type SSMPort
func (_mock *SSMPort) GetParameters(ctx context.Context, input *ssm.GetParametersInput) (*ssm.GetParametersOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetParameters")
	}

	var r0 *ssm.GetParametersOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersInput) (*ssm.GetParametersOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersInput) *ssm.GetParametersOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParametersOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParametersInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_GetParameters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParameters'
type SSMPort_GetParameters_Call struct {
	*mock.Call
}

// GetParameters is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.GetParametersInput
func (_e *SSMPort_Expecter) GetParameters(ctx interface{}, input interface{}) *SSMPort_GetParameters_Call {
	return &SSMPort_GetParameters_Call{Call: _e.mock.On("GetParameters", ctx, input)}
}

func (_c *SSMPort_GetParameters_Call) Run(run func(ctx context.Context, input *ssm.GetParametersInput)) *SSMPort_GetParameters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParametersInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParametersInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_GetParameters_Call) Return(getParametersOutput *ssm.GetParametersOutput, err error) *SSMPort_GetParameters_Call {
	_c.Call.Return(getParametersOutput, err)
	return _c
}

func (_c *SSMPort_GetParameters_Call) RunAndReturn(run func(ctx context.Context, input *ssm.GetParametersInput) (*ssm.GetParametersOutput, error)) *SSMPort_GetParameters_Call {
	_c.Call.Return(run)
	return _c
}

// GetParametersByPath provides a mock function for the type SSMPort
func (_mock *SSMPort) GetParametersByPath(ctx context.Context, input *ssm.GetParametersByPathInput) (*ssm.GetParametersByPathOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for GetParametersByPath")
	}

	var r0 *ssm.GetParametersByPathOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersByPathInput) (*ssm.GetParametersByPathOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.GetParametersByPathInput) *ssm.GetParametersByPathOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.GetParametersByPathOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.GetParametersByPathInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_GetParametersByPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParametersByPath'
type SSMPort_GetParametersByPath_Call struct {
	*mock.Call
}

// GetParametersByPath is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.GetParametersByPathInput
func (_e *SSMPort_Expecter) GetParametersByPath(ctx interface{}, input interface{}) *SSMPort_GetParametersByPath_Call {
	return &SSMPort_GetParametersByPath_Call{Call: _e.mock.On("GetParametersByPath", ctx, input)}
}

func (_c *SSMPort_GetParametersByPath_Call) Run(run func(ctx context.Context, input *ssm.GetParametersByPathInput)) *SSMPort_GetParametersByPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.GetParametersByPathInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.GetParametersByPathInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_GetParametersByPath_Call) Return(getParametersByPathOutput *ssm.GetParametersByPathOutput, err error) *SSMPort_GetParametersByPath_Call {
	_c.Call.Return(getParametersByPathOutput, err)
	return _c
}

func (_c *SSMPort_GetParametersByPath_Call) RunAndReturn(run func(ctx context.Context, input *ssm.GetParametersByPathInput) (*ssm.GetParametersByPathOutput, error)) *SSMPort_GetParametersByPath_Call {
	_c.Call.Return(run)
	return _c
}

// ListTagsForResource provides a mock function for the type SSMPort
func (_mock *SSMPort) ListTagsForResource(ctx context.Context, input *ssm.ListTagsForResourceInput) (*ssm.ListTagsForResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for ListTagsForResource")
	}

	var r0 *ssm.ListTagsForResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.ListTagsForResourceInput) (*ssm.ListTagsForResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.ListTagsForResourceInput) *ssm.ListTagsForResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.ListTagsForResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.ListTagsForResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_ListTagsForResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTagsForResource'
type SSMPort_ListTagsForResource_Call struct {
	*mock.Call
}

// ListTagsForResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.ListTagsForResourceInput
func (_e *SSMPort_Expecter) ListTagsForResource(ctx interface{}, input interface{}) *SSMPort_ListTagsForResource_Call {
	return &SSMPort_ListTagsForResource_Call{Call: _e.mock.On("ListTagsForResource", ctx, input)}
}

func (_c *SSMPort_ListTagsForResource_Call) Run(run func(ctx context.Context, input *ssm.ListTagsForResourceInput)) *SSMPort_ListTagsForResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.ListTagsForResourceInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.ListTagsForResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_ListTagsForResource_Call) Return(listTagsForResourceOutput *ssm.ListTagsForResourceOutput, err error) *SSMPort_ListTagsForResource_Call {
	_c.Call.Return(listTagsForResourceOutput, err)
	return _c
}

func (_c *SSMPort_ListTagsForResource_Call) RunAndReturn(run func(ctx context.Context, input *ssm.ListTagsForResourceInput) (*ssm.ListTagsForResourceOutput, error)) *SSMPort_ListTagsForResource_Call {
	_c.Call.Return(run)
	return _c
}

// PutParameter provides a mock function for the type SSMPort
func (_mock *SSMPort) PutParameter(ctx context.Context, input *ssm.PutParameterInput) (*ssm.PutParameterOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for PutParameter")
	}

	var r0 *ssm.PutParameterOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.PutParameterInput) (*ssm.PutParameterOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.PutParameterInput) *ssm.PutParameterOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.PutParameterOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.PutParameterInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_PutParameter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PutParameter'
type SSMPort_PutParameter_Call struct {
	*mock.Call
}

// PutParameter is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.PutParameterInput
func (_e *SSMPort_Expecter) PutParameter(ctx interface{}, input interface{}) *SSMPort_PutParameter_Call {
	return &SSMPort_PutParameter_Call{Call: _e.mock.On("PutParameter", ctx, input)}
}

func (_c *SSMPort_PutParameter_Call) Run(run func(ctx context.Context, input *ssm.PutParameterInput)) *SSMPort_PutParameter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.PutParameterInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.PutParameterInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_PutParameter_Call) Return(putParameterOutput *ssm.PutParameterOutput, err error) *SSMPort_PutParameter_Call {
	_c.Call.Return(putParameterOutput, err)
	return _c
}

func (_c *SSMPort_PutParameter_Call) RunAndReturn(run func(ctx context.Context, input *ssm.PutParameterInput) (*ssm.PutParameterOutput, error)) *SSMPort_PutParameter_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveTagsFromResource provides a mock function for the type SSMPort
func (_mock *SSMPort) RemoveTagsFromResource(ctx context.Context, input *ssm.RemoveTagsFromResourceInput) (*ssm.RemoveTagsFromResourceOutput, error) {
	ret := _mock.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for RemoveTagsFromResource")
	}

	var r0 *ssm.RemoveTagsFromResourceOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.RemoveTagsFromResourceInput) (*ssm.RemoveTagsFromResourceOutput, error)); ok {
		return returnFunc(ctx, input)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *ssm.RemoveTagsFromResourceInput) *ssm.RemoveTagsFromResourceOutput); ok {
		r0 = returnFunc(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ssm.RemoveTagsFromResourceOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *ssm.RemoveTagsFromResourceInput) error); ok {
		r1 = returnFunc(ctx, input)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// SSMPort_RemoveTagsFromResource_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveTagsFromResource'
type SSMPort_RemoveTagsFromResource_Call struct {
	*mock.Call
}

// RemoveTagsFromResource is a helper method to define mock.On call
//   - ctx context.Context
//   - input *ssm.RemoveTagsFromResourceInput
func (_e *SSMPort_Expecter) RemoveTagsFromResource(ctx interface{}, input interface{}) *SSMPort_RemoveTagsFromResource_Call {
	return &SSMPort_RemoveTagsFromResource_Call{Call: _e.mock.On("RemoveTagsFromResource", ctx, input)}
}

func (_c *SSMPort_RemoveTagsFromResource_Call) Run(run func(ctx context.Context, input *ssm.RemoveTagsFromResourceInput)) *SSMPort_RemoveTagsFromResource_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *ssm.RemoveTagsFromResourceInput
		if args[1] != nil {
			arg1 = args[1].(*ssm.RemoveTagsFromResourceInput)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *SSMPort_RemoveTagsFromResource_Call) Return(removeTagsFromResourceOutput *ssm.RemoveTagsFromResourceOutput, err error) *SSMPort_RemoveTagsFromResource_Call {
	_c.Call.Return(removeTagsFromResourceOutput, err)
	return _c
}

func (_c *SSMPort_RemoveTagsFromResource_Call) RunAndReturn(run func(ctx context.Context, input *ssm.RemoveTagsFromResourceInput) (*ssm.RemoveTagsFromResourceOutput, error)) *SSMPort_RemoveTagsFromResource_Call {
	_c.Call.Return(run)
	return _c
}
